### ISSUE TITLE
"Finance" is misspelled in the Xcode project exporter's "App categories" 

### ISSUE THREAD

**Issue by mmomentum** [juce-framework/JUCE#1003]
Just noticed this.
https://github.com/juce-framework/JUCE/blob/9055820a30770479e30994c9a91029474cf60f7d/extras/Projucer/Source/ProjectSaving/jucer_ProjectExport_Xcode.h#L362

**Comment by tpoole** [comment]
Thank you for reporting. We'll get that fixed.
