### ISSUE TITLE
Output with crackling noise or no output at all with macOS 12.1 and Airpod Pros

### ISSUE THREAD

**Issue by pdehne** [juce-framework/JUCE#1004]
To reproduce connect Airpod Pros to the Mac, start the DemoRunner and choose AudioSettingsDemo.h.

In the DemoRunner choose Airpod Pro as Output and MacBook Pro Microphone as input. Then click "Test". This will give crackling output.

Choose Airpod Pro as Output and Airpod Pro as Input. Then click "Test". There will be no output at all.

Environment is macOS 12.1, Intel 64 bit.

**Comment by tpoole** [comment]
Is this using the `develop` or `master` branch?

We've just made a Airpod Pros related change to the former, so this may be
fixed already or we need to revert that commit.

**Comment by pdehne** [comment]
I double checked. No crackling noises with develop, then I double check master branch again and DemoRunner has no more crackling noises there too.

My own app still has crackling audio with Airpods though, but I use a much older version of JUCE. My code has probably put the audio device in a state that confused the DemoRunner.

It's the strangest thing, when I use the Audio-MIDI-Setup to switch the Airpods to 16000 hz and then back to 48000 while my apps audio is playing the crackling goes away. I assume the older JUCE is doing something different when opening the audio device output format.

But feel free to close the issue, I understand that you can't support ancient JUCE versions.

**Comment by tpoole** [comment]
Thank you for checking.

**Comment by kmatheussen** [comment]
JUCE doesn't enable proper realtime priority for the audio processing threads on macos, so I guess that could be the reason. It only uses SCHED_RR, which isn't always good enough (SCHED_RRR is good enough on Linux, but doesn't seem to be good enough on macos). You can check if this is the problem by calling 'MACH_THREADS_jack_acquire_real_time_scheduling' (found in this file: https://github.com/kmatheussen/radium/blob/master/macosx/machthreads.mm) one time inside your audio callback.

**Comment by kmatheussen** [comment]
(You also have to call 'MACH_THREADS_set_period_and_buffer_size' before calling 'MACH_THREADS_jack_acquire_real_time_scheduling')

**Comment by tpoole** [comment]
How is the code in the file you linked different to what JUCE is doing? It looks like the same invocation of `thread_policy_set`: https://github.com/juce-framework/JUCE/blob/master/modules/juce_core/native/juce_posix_SharedCode.h#L1384

**Comment by kmatheussen** [comment]
That code is used to set realtime priority for the high resolution timer.
It's not used to set realtime priority for audio processing thread.

**Comment by pdehne** [comment]
@tpoole I was able to identify the actual problem. I'd say this is a bug that is in current JUCE as well.

@kmatheussen Many thanks for the tip, I will keep in mind to try this, in case I run into glitches in the future.

The default buffer size for CoreAudio is 512: https://github.com/juce-framework/JUCE/blob/fc6bfaf79ebc3be0d3a9df937f845915b0668dac/modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp#L846

When the available buffer sizes for an audio device are filled the current buffer size is added as well (see lines 352-353):
https://github.com/juce-framework/JUCE/blob/fc6bfaf79ebc3be0d3a9df937f845915b0668dac/modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp#L336-L354

Airpod Pro's if connected to macOS 12.1, have a maximum buffer size of 480. The default value of 512 is invalid.

So, if the device manager is opened with the default configuration the output device is opened with the invalid buffer size of 512. This results in crackling audio output.

You should be able to reproduce this by connecting Airpod Pros, then initialize the device manager like so:
```
deviceManager->initialise(0, 2, "", true);
```

The fix is to set the default value of bufferSize to 0 instead of 512. Then the allowed bufferSize of 480 will be chosen for Airpod Pro's during device manager initialization.
