### ISSUE TITLE
Add support for observing MIDI setup changes

### ISSUE THREAD

**Issue by adamnemecek** [juce-framework/JUCE#1006]
Right now, it's impossible to observe changes to midi setup changes

https://github.com/juce-framework/JUCE/blob/0bac0e78c815d9b6328e238fefc2bb151a5163ec/modules/juce_audio_devices/native/juce_mac_CoreMidi.mm#L587

E.g. this method should be implemented. I can try putting something together if there's interest.

**Comment by adamnemecek** [comment]
I mean I'm aware of how to subscribe to the notifications, what I was saying is that this should be a juce feature, I don't really want to maintain my fork. There's no need to use the CFNotificationCenter, you can just use NSNotificationCenter.

**Comment by designerfuzzi** [comment]
indeed NSNotificationCenter is the wrapper around CFNotificationCenter. 
But then your own extension needs objective-c runtime as well. good luck
