### ISSUE TITLE
Please enable address sanitizer in Projucer debug builds.

### ISSUE THREAD

**Issue by keinstein** [juce-framework/JUCE#1007]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

- Build a Program with Projucer in debug build on a Linux x86_64 system.
- Run the program to make ensure that it seems to be working correctly
- Figure out how to to pass command line Parameters for the compiler
- Find out which parameters are necessary to enable address sanitizer
- Compile the Program in any mode with enabled address sanitizer
- Use the program extensively
- The program may crash due to 20 years old bugs.

  2) the expected behaviour
- Projucer offers the possiblilty to enable the address sanitizer in all GCC and Clang based configurations (including MacOS, Linux, MingW, ...)
- Projucer offers the possibility to inject compiler and preprocessor command line options per configuration, not only per exporter
- The address sanitizer is enabled in all suitable debug configuration templates
- The address sanitizer is disabled in all release configuration templates

  3) the operating system
Linux
  4) the architecture (32-bit or 64-bit)
x86_64
  5) a stack trace - if the bug causes a crash
Solving the bug transforms Heisenbugs that hits the user every now and then into reliable Crashes with up to three meaningful backtraces.

  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
not applicable
  7) which DAW you observed the bug in - if applicable
not applicable

I intentionally omitted the stacktraces and references found by this procedure. My last bug report on this topic was closed unsolved because I mentioned one of the bugs I found when enabling the address sanitizer. So I want to make clear the general problem of not testing with address sanitizer is understood before I give further hints to the additional instances of the above mentioned problem.

Note that its not advisable to enforce the address sanitizer in all debug builds as in rare cases the performance drop could ruin the realtime behaviour. On the other hand it is advisable to reproduce strange crashes in the stable build using the address or thread sanitizer when all other means fail.

**Comment by reuk** [comment]
Simply enabling address sanitizer is only part of the problem - we'd also need to test all possible interactions with the app. We do currently test with address sanitizer, but it's not feasible for us to in-depth manual testing of full applications on all platforms on every commit, so it's possible that issues may be introduced over time.

Normally, enabling address sanitizer is fairly straightforward (i.e. just add `-fsanitize=address` to your compiler flags) so I'm not sure that a dedicated Projucer feature is necessary.

> I intentionally omitted the stacktraces and references found by this procedure.

If you encounter issues, _please_ include stack traces and steps to reproduce the problem, so that we can be sure we've fixed the same issue.

> My last bug report on this topic was closed unsolved because I mentioned one of the bugs I found when enabling the address sanitizer.

If you encounter more problems, please create separate issues for each crash, and include stack traces and the steps you followed to trigger the problem. The JUCE team is quite busy, and we'll be able to fix problems much more quickly if we know exactly what to look for.

**Comment by keinstein** [comment]
I want to emphasize that I complained about long standing bugs and not about regressions.

The easier it is to use memory debuggers the more JUCE users will use them. As JUCE is a source code library they will also find and report errors. So providing the mentioned features with Projucer will increase the test base and find the errors much more early. And providing GUI support would encourage the JUCE users to use the memory debugger a little bit. So the software written with JUCE and JUCE itself will gain a little bit of better quality.

The best way against regressions would be test based development with a test case for every bug that has been reported so far. But that's another topic.

With "-fsanitize=address" you should at least provide "-fno-omit-frame-pointer" in order to get useful stack traces.
I tried adding the flags to the build configuration. But this is simply not possible – at least for LinuxMakefile. Compiler flags can be defined only at Exporter level, which leads to maintenance problems. This is one of the points I mentioned above.

**Comment by keinstein** [comment]
Just for the records:

> ii\. the expected behaviour
> 
> […]
> 
> * Projucer offers the possibility to inject compiler and preprocessor command line options per configuration, not only per exporter
> 
> […]

**Comment by tpoole** [comment]
We can't have the sanitizers enabled by default, even if it were just restricted to debug builds. A lot of our users use custom toolchains for embedded devices that don't have that functionality.
