### ISSUE TITLE
Copied text has an additional \0 character

### ISSUE THREAD

**Issue by keinstein** [juce-framework/JUCE#1009]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

- Run DemoRunner
- Activate the CodeEditor demo
- Open a another editor that can handle texts including \0 like Emacs.
- Select some text in the CodeEditor.
- Hit Ctrl+Ins to copy the text
- Activate the Emacs window
- Hit Ctrl+Y to insert the text from the clipboard
- The text appears and an additional \0 is appended
Only JUCE applications show this behaviour. No other applications.

Note: Many Programs use C strings for everything.  So they cannot represent texts containing null characters. This means it is important to choose the right application for testing.

  2) the expected behaviour
the selected text appears without appended null characters
  3) the operating system
Linux
  4) the architecture (32-bit or 64-bit)
x86_64
  5) a stack trace - if the bug causes a crash
no crash
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
not applicable
  7) which DAW you observed the bug in - if applicable
not applicable

**Comment by tpoole** [comment]
Thank you for reporting. Fixed in https://github.com/juce-framework/JUCE/commit/3366ad4ed4fadbbf28600e887c6f12566e98d588.
