### ISSUE TITLE
[Bug]: String::getHexValue32() does not ignore non-hexadecimal characters since Juce 6.1.4

### ISSUE THREAD

**Issue by sebastianarnold** [juce-framework/JUCE#1012]
### Detailed steps on how to reproduce the bug

CharacterFunctions::HexParser was changed in https://github.com/juce-framework/JUCE/commit/6244fc293fe9ee3cde8674ed933c69ebbcf551b7 so that String::getHexValue32() does not work as documented.

The documentation (https://docs.juce.com/master/classString.html#aabd5ab574e90ad82058de70b01ed0843) states:

> Non-hexadecimal characters in the string are ignored.

See the following minimal Example, which does not pass on current master branch on my system, because the "x" leads to an undefined behavior:

```
assert(String("0x00").getHexValue32() == 0);
```

Instead, I get `-256` as a result from `String("0x00").getHexValue32() `.

### What is the expected behaviour?

I expect that either:
- the example assertion above passes, i.e. hex values prefixed with "0x" can be parsed correctly, or
- the documentation and BREAKING-CHANGES.txt is updated to reflect this change

### Operating systems

Linux

### What versions of the operating systems?

Linux version 5.4.0-92-generic (buildd@lgw01-amd64-016) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))

### Architectures

64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting this issue. I've added a fix, along with some tests, here: https://github.com/juce-framework/JUCE/commit/fdfc279bea84810e00f9c3b65f6e58785f803486

Please let us know if you encounter further issues with this change, and I'll reopen this issue.
