### ISSUE TITLE
[Bug]: Compiling vst3 with `JUCE_VST3_CAN_REPLACE_VST2=1` fails on Windows

### ISSUE THREAD

**Issue by kokounet** [juce-framework/JUCE#1016]
### Detailed steps on how to reproduce the bug

* In projucer, set up the global vst2 sdk path to your vst2 sdk location
* Open the `GainPlugin` example with projucer, and set the `Modules>juce_audio_plugin_client>JUCE_VST3_CAN_REPLACE_VST2` to enabled
* Try to compile the `GainPlugin_VST3` project in Visual Studio, it should fail because `'fxBank' is not a member of namespace 'Vst2'`.

In fact I was not able to find any declaration of `fxBank` anywhere in the Juce code, in the vst2 sdk or in the vst3 sdk, so I'm a bit lost here.

### What is the expected behaviour?

The project should be able to compile in compatibility mode, meaning that the vst2 version of the plugin can be replaced with the vst3 one with its state restored.

### Operating systems

Windows

### What versions of the operating systems?

Windows 10 64-bits

### Architectures

x86_64

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

Cubase is the only DAW I know of that does the state restoration correctly if there is need to test the feature

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
As far as I can tell, references to `fxBank` were introduced four years ago in cf4f12a452611e46d29e4549ce69adac345706b7. The copy of the VSTSDK we use for testing definitely contains a definition of this type, in `vstfxstore.h` (version 2.4).

What version of the VST2 SDK are you using? Is there a chance it's outdated or incomplete?

**Comment by kokounet** [comment]
I'm using the VST SDK version 2.4 dated 2006/07/05

**Comment by reuk** [comment]
Does it include the header file I mentioned?

**Comment by kokounet** [comment]
So looking at the content of the [vstsdk 2.4 on archive.org](https://archive.org/download/VST2SDK) there seems to be 2 revisions which modify this file. So indeed there seems to exist 2 version at least of the 2.4 sdk that are not compatible only in this particular file.

**Comment by kokounet** [comment]
Updating my vstsdk2.4 to the rev2 fixed the compilation indeed, thank you for the prompt response!

**Comment by reuk** [comment]
Cool, glad you found a solution 👍
