### ISSUE TITLE
Typo: MidiFile::findAllKeySigEvents() description

### ISSUE THREAD

**Issue by ishinomaru** [juce-framework/JUCE#1021]
### Detailed steps on how to reproduce the bug

Here.
https://github.com/juce-framework/JUCE/blob/4cf036bb8bdee65dd2a946f481d0c14aea00b23f/modules/juce_audio_basics/midi/juce_MidiFile.h#L136

Incorrect: Makes a list of all the **time**-signature meta-events from all tracks in the midi file.
Correct: Makes a list of all the **key**-signature meta-events from all tracks in the midi file.

Thanks.

### What is the expected behaviour?

The Document description is also wrong.
https://docs.juce.com/master/classMidiFile.html#aadf60b9be97a44d09f5f4ec244767687

### Operating systems

Other

### What versions of the operating systems?

OS-independent.

### Architectures

Other

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
This is fixed in the latest release. Thank you for reporting.
