### ISSUE TITLE
[Bug]: Standalone plugin window flickers when resizing with setFixedAspectRatio

### ISSUE THREAD

**Issue by jacobweberbowery** [juce-framework/JUCE#1026]
### Detailed steps on how to reproduce the bug

Start with `juce/examples/CMake/AudioPlugin`, and update the PluginEditor.cpp constructor with:
```
    juce::ignoreUnused (processorRef);
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
-    setSize (400, 300);
+    setSize (500, 500);
+    setResizable(true, true);
+    setResizeLimits(400, 400, 800, 800);
+    getConstrainer()->setFixedAspectRatio(1);
```

When you run the Standalone target, there will be a resizable border, and a resize control on the bottom right. If you drag by the border, the window will flicker. If you drag by the control, it looks fine.

https://user-images.githubusercontent.com/97635922/153766969-7a59f70f-0b7c-41d7-b2f9-6c833a4ccb0d.mov

### What is the expected behaviour?

Dragging by the border works as well as dragging by the control.

Or there's a way to disable the border dragging.

### Operating systems

macOS

### What versions of the operating systems?

12.2.1

### Architectures

x86_64, ARM

### Plug-in formats (if applicable)

VST3

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting this problem. I've added a fix for the problem here:

https://github.com/juce-framework/JUCE/commit/c0b78adcdad72c68c6c593e7bf835f3978be4c6c

Please try updating and let us know if you still run into problems.

**Comment by jacobweberbowery** [comment]
Awesome, thanks! Will give it a try.
