### ISSUE TITLE
[Bug]: Plugins do not fully unload when removed from a session on Windows

### ISSUE THREAD

**Issue by devinkerr** [juce-framework/JUCE#1034]
### Detailed steps on how to reproduce the bug

see: https://github.com/juce-framework/JUCE/commit/3d282c10784661789881a835779d76f606556465#commitcomment-67248699

### What is the expected behaviour?

Plugins should fully unload / release resources when removed in a DAW

### Operating systems

Windows

### What versions of the operating systems?

Windows 10

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting. The issue should be fixed by this commit:

https://github.com/juce-framework/JUCE/commit/c9997bd613281f7f0ecf1ffeab18c7422aabf7cf
