### ISSUE TITLE
[Bug]: Randomly invisible Popup submenus (6.1.x develop branch)

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#1035]
### Detailed steps on how to reproduce the bug

Create a popupmenu with submenus (even one level is enough).
When hovering on the first level of the menu, the submenu is [sometimes] only showing the drop-shadow, but not the actual submenu content. When moving the mouse over the area where the submenu should be, it magically appears.

Not sure if this bug is always there, but you can check it quite easily with the software I'm building : https://benjamin.kuperberg.fr/chataigne 
I'm not using anything fancy around popups, just basic menu and submenus.
I switched all my code to async to not use modal loops to see it changed anything, but the bug's still there. 

 tried doing screen capture / screen shots, but everytime I try, the behaviour doesn’t happen.
I had to take pictures from my phone to actually see the behaviour :
In the first one you can see the submenu only showing a dropshadow, and then when moving the mouse on the menu, it magically appears (photo 2)

![e280f84d409ca39089fc6d395e08eba5597710b9_2_225x500](https://user-images.githubusercontent.com/1291595/156566414-a633be11-a134-4905-8559-6706ede12f42.jpeg)
![ea06a54b5505d9a6c62144665b9d7deef6317d5d_2_225x500](https://user-images.githubusercontent.com/1291595/156566420-908e07f1-211c-46b9-9f1a-de25d9ed1ee0.jpeg)

### What is the expected behaviour?

Submenu content should always appear

### Operating systems

Windows

### What versions of the operating systems?

Windows 11 x64 (not tested with other systems)

### Architectures

64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
This this problem still present in the latest JUCE `develop` branch? We're unable to reproduce it.

**Comment by benkuper** [comment]
Didn't see it for quite a while now
