### ISSUE TITLE
[Bug]: cmake configuration of JUCE is extremely slow

### ISSUE THREAD

**Issue by jjYBdx4IL** [juce-framework/JUCE#1042]
### Detailed steps on how to reproduce the bug

I have a Ryzen 5600X with dual-rank RAM. And every update to a CMakeLists.txt file triggers a reconfiguration incl. JUCE which I added via "add_subdirectory". This reconfiguration takes 70 seconds to complete (cmake 3.22.3 on Win11/64, 32GB RAM, SSD).

Is that normal? If so, what is the issue here?

### What is the expected behaviour?

Be fast.

### Operating systems

Windows

### What versions of the operating systems?

11

### Architectures

x86_64

### Plug-in formats (if applicable)

VST3

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by McMartin** [comment]
You can pass `--trace-format=json-v1 --trace-redirect=trace.json` to cmake to make it write a JSON file that will list each CMake command that was called, its file, its line and its timestamp. This should help you pin-point which command call(s) take so long.

**Comment by jjYBdx4IL** [comment]
no clue why, but it's way faster today........
