### ISSUE TITLE
[Bug]: OpenGL: openGLContextClosing() called inconsistently in Logic Pro on M1

### ISSUE THREAD

**Issue by devinkerr** [juce-framework/JUCE#1046]
### Detailed steps on how to reproduce the bug

Using Logic Pro 10.7.3 on an M1 Mac:

1. Instantiate a JUCE-made AU plugin
2. Trigger a top-level popup menu 
3. Close/dismiss popup menu
4. Close plugin UI
5. Observe that openGLContextClosing() is not called and openGL callbacks still occur (needlessly wasting CPU/GPU cycles)

### What is the expected behaviour?

Expect openGLContextClosing() to be called when the UI closes.

### Operating systems

macOS

### What versions of the operating systems?

12.1+

### Architectures

ARM

### Plug-in formats (if applicable)

AU

### Plug-in host applications (DAWs) (if applicable)

Logic Pro

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
See the corresponding issue on the JUCE forum here: https://forum.juce.com/t/plugin-editors-still-redraw-even-when-closed-on-m1-logic/45268
