### ISSUE TITLE
[Bug]: Apple store warning for using Non Public APIs blocks the app distribution

### ISSUE THREAD

**Issue by arihjain28** [juce-framework/JUCE#1047]
### Detailed steps on how to reproduce the bug

Integrate JUCE 6.1.0 > build ios app > upload to itunes for distribution

### What is the expected behaviour?

No apple warning

### Operating systems

iOS

### What versions of the operating systems?

ios 14+
<img width="697" alt="Screenshot 2022-03-30 at 1 04 50 PM" src="https://user-images.githubusercontent.com/70574987/160777275-5786e9a8-faf9-4a7f-ac17-c1995baf05de.png">

### Architectures

64-bit

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by McMartin** [comment]
> The bug is present on the `develop` branch

@arihjain28 did you really test with the `develop` branch? Or any JUCE version more recent than 6.1.0?

**Comment by arihjain28** [comment]
> > The bug is present on the `develop` branch
> 
> @arihjain28 did you really test with the `develop` branch? Or any JUCE version more recent than 6.1.0?

I only checked with 6.1.0 not tested with develop branch

**Comment by arihjain28** [comment]
Removed that section altogether to stop creating miscommunication

**Comment by tpoole** [comment]
> it was a mandatory dropdown to select from

Yes, but it allows you to select 'I have not tested agains the develop branch'.

In any case, this issue should be addressed in JUCE 6.1.6.
