### ISSUE TITLE
[Bug]: invalid use of getBusCount in VST3

### ISSUE THREAD

**Issue by jpcima** [juce-framework/JUCE#1079]
### Detailed steps on how to reproduce the bug

Given an arbitrary VST3 plugin, hosted in the audio plugin host of JUCE, the plugin seems to break the thread specification indicated in the [workflow diagram].

More precisely, JUCE invokes `IComponent::getBusCount` in the *Processing thread*, while the component is in the *Processing* state. The documentation specifies *UI thread* instead.

This follows from this call sequence, inside `juce_VST3PluginFormat.cpp`
- [associateWith](https://github.com/juce-framework/JUCE/blob/0e85fec4a2e93a6cc92688251dcfc760d2d568c3/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L2574)
- [acceptsMidi](https://github.com/juce-framework/JUCE/blob/0e85fec4a2e93a6cc92688251dcfc760d2d568c3/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L3338)
- [getNumSingleDirectionBusesFor](https://github.com/juce-framework/JUCE/blob/0e85fec4a2e93a6cc92688251dcfc760d2d568c3/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L2775)

[workflow diagram]: https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Workflow+Diagrams/Audio+Processor+Call+Sequence.html

### What is the expected behaviour?

The audio thread would not invoke `IComponent::getBusCount`.

### Operating systems

Windows

### What versions of the operating systems?

Windows 10

### Architectures

x86_64

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

JUCE AudioPluginHost

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, fixed here:

https://github.com/juce-framework/JUCE/commit/0e33d4509deed6b0366a6cb62208ac95e512c97a
