### ISSUE TITLE
[Bug]: Read of nullptr causes read access violation in HWNDCompnentPeer constructor on Windows

### ISSUE THREAD

**Issue by braxtons12** [juce-framework/JUCE#1083]
### Detailed steps on how to reproduce the bug

1. Build plugin using new JUCE 7
2. Instantiate plugin on a track
3. If your DAW doesn't automatically open the plugin UI, open it
4. Delete that instance of the plugin
5. Create new instance of the plugin on any track
6. If your DAW doesn't automatically open the plugin UI, open it
5. Crash

### What is the expected behaviour?

No crash

### Operating systems

Windows

### What versions of the operating systems?

Windows 10 21H2 Build 19044.1706

### Architectures

x86_64

### Stacktrace

```shell
juce::HWNDComponentPeer::HWNDComponentPeer(juce::Component & comp, int windowStyleFlags, HWND__ * parent, bool nonRepainting) Line 1660
	at D:\JUCE\modules\juce_gui_basics\native\juce_win32_Windowing.cpp(1660)
juce::Component::createNewPeer(int styleFlags, void * parentHWND) Line 4611
	at D:\JUCE\modules\juce_gui_basics\native\juce_win32_Windowing.cpp(4611)
juce::Component::addToDesktop(int styleWanted, void * nativeWindowToAttachTo) Line 721
	at D:\JUCE\modules\juce_gui_basics\components\juce_Component.cpp(721)
juce::JuceVST3EditController::JuceVST3Editor::attached(void * parent, const char * type) Line 1752
	at D:\JUCE\modules\juce_audio_plugin_client\VST3\juce_VST3_Wrapper.cpp(1752)
```

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

Tested in REAPER and the JUCE AudioPluginHost

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks, fixed here:

https://github.com/juce-framework/JUCE/commit/2f0a0e938750a693ebdf2f3d38981e3764515a58
