### ISSUE TITLE
[Bug]: Cannot build new ARA Plugin from Projucer

### ISSUE THREAD

**Issue by mikelange49** [juce-framework/JUCE#1087]
### Detailed steps on how to reproduce the bug

Hi JUCE team.

AAX_SDK_2p3p2
Juce 7 Projucer
New Project > Plugin > ARA
Open in Visual Studio
Build VST3 
Several compilation errors
![image](https://user-images.githubusercontent.com/34253501/177017843-a21cb875-864a-4237-b2f3-b08a07543b58.png)

### What is the expected behaviour?

It builds

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/5cfef709943285e92aec43e05eb9e42e8cf6b049.

Thank you for reporting.
