### ISSUE TITLE
[Bug]: Is there a memory leak in this function?

### ISSUE THREAD

**Issue by jiemojiemo** [juce-framework/JUCE#1103]
### Detailed steps on how to reproduce the bug

```cpp
void Thread::launch (std::function<void()> functionToRun)
{
    auto anon = new LambdaThread (functionToRun);
    anon->deleteOnThreadEnd = true;
    anon->startThread();
}
```
JUCE new a LambdaThread in Thread::launch, but never delete it ,so is it a memory leak?

### What is the expected behaviour?

need someway to delete LambdaThread, maybe we can add `delete this` in the end of LambdaThread::run()

```cpp
void run() override
    {
        fn();
        fn = nullptr; // free any objects that the lambda might contain while the thread is still active
        delete this;
    }
```

### Operating systems

macOS

### What versions of the operating systems?

macOs Monterey 12.2
Apple M1 pro

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
This is not a leak. When `deleteOnThreadEnd` is set, the thread will delete itself after it has called its `run` method.
