### ISSUE TITLE
[Bug]: default Linux font has the wrong style

### ISSUE THREAD

**Issue by jpcima** [juce-framework/JUCE#1104]
### Detailed steps on how to reproduce the bug

Create a window and put a `Label` inside, in the most basic way possible.
The label should display in the defaut font with regular style, instead it displays in italics.

I experience this bug directly, and observe it in reports from others as well:
(eg. https://github.com/jpcima/ysfx/issues/65#issue-1329668501)

I have the problem narrowed down to here:
https://github.com/juce-framework/JUCE/blob/965d0ca4be178c4a0000b116d460e15c30311992/modules/juce_graphics/native/juce_linux_Fonts.cpp#L225

An empty style array is obtained when `name` is the placeholder name `<Sans-Serif>`.
Replacing with `characteristics.name`, containing the actual font name, appears to fix the problem.

### What is the expected behaviour?

The default label shows regular characters.

### Operating systems

Linux

### What versions of the operating systems?

Fedora 36

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting! https://github.com/juce-framework/JUCE/commit/c920eb95fd94839a1b34bd0797e2ba5f85aed331
