### ISSUE TITLE
[Bug]: Calf LV2 plugins don't have its native GUI

### ISSUE THREAD

**Issue by akimaze** [juce-framework/JUCE#1123]
### Detailed steps on how to reproduce the bug

Hi, 

I'm using Radium that uses JUCE to support plugins and it looks like the new LV2 support does not support GTK UI in plugins?
Is it a bug or is that an assumption made in the JUCE project?

Radium bug report about that: https://github.com/kmatheussen/radium/issues/1382

### What is the expected behaviour?

See original GTK UI in Calf plugins

### Operating systems

Linux

### What versions of the operating systems?

Linux Mint 21

### Architectures

x86_64

### Plug-in formats (if applicable)

LV2

### Plug-in host applications (DAWs) (if applicable)

Radium - https://github.com/kmatheussen/radium

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by KottV** [comment]
at present JUCE can display plugins with X11 GUI only, adding non-native toolkits (GTK, Qt) might be a significant work

**Comment by akimaze** [comment]
@KottV Thank you for the information, I should close this issue?

**Comment by KottV** [comment]
I don't know, really. Is there a plan to add external GTK UI support for LV2 host part in JUCE?
Calf seems to be the only one reason for that. Anyway these plugins works with https://github.com/DISTRHO/Ildaeil bridge.

**Comment by tpoole** [comment]
I'm afraid we don't have any immediate plans to support non-X11 plug-in GUIs, and without significantly more demand from the community it's unlikely that this will change,
