### ISSUE TITLE
[Bug]: GDI leak on Windows

### ISSUE THREAD

**Issue by ValentynPavliuchenkoA** [juce-framework/JUCE#1130]
### Detailed steps on how to reproduce the bug

Check WindowClassHolder class from modules/juce_gui_basics/native/juce_win32_Windowing.cpp:
2 icons are created by ExtractAssociatedIcon and none are freed.

See https://github.com/juce-framework/JUCE/pull/1129 for a fix. For some reason the check-CLA has failed authorize this, while recognizing that I did sign the CLA (another bug).

### What is the expected behaviour?

No GDI leaks

### Operating systems

Windows

### What versions of the operating systems?

Any

### Architectures

64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Fixed here: https://github.com/juce-framework/JUCE/commit/59a47a463873ad2a3515506ae983e430e2b6aba7
