### ISSUE TITLE
[Bug]: Symbol juce::AnimatedAppComponent not exported when build dll

### ISSUE THREAD

**Issue by FangCunWuChang** [juce-framework/JUCE#1136]
### Detailed steps on how to reproduce the bug

1. I complied JUCE as DLL  
2. I created a class inherited from juce::AnimatedAppComponent  
3. I complied my code with JUCE.dll linked  
4. I got error LNK2019  
5. I found juce::AnimatedAppComponent symbol in modules\juce_gui_extra\misc\juce_AnimatedAppComponent.h has not exported.  

### What is the expected behaviour?

error LNK2019: 无法解析的外部符号 "public: __cdecl juce::AnimatedAppComponent::AnimatedAppComponent(void)" (??0AnimatedAppComponent@juce@@QEAA@XZ)，函数 "public: __cdecl Splash::Splash(class juce::String const &,class juce::String const &)" (??0Splash@@QEAA@AEBVString@juce@@0@Z) 中引用了该符号  
error LNK2019: 无法解析的外部符号 "public: void __cdecl juce::AnimatedAppComponent::setFramesPerSecond(int)" (?setFramesPerSecond@AnimatedAppComponent@juce@@QEAAXH@Z)，函数 "public: void __cdecl Splash::closeSplash(void)" (?closeSplash@Splash@@QEAAXXZ) 中引用了该符号  
error LNK2001: 无法解析的外部符号 "private: virtual void __cdecl juce::AnimatedAppComponent::timerCallback(void)" (?timerCallback@AnimatedAppComponent@juce@@EEAAXXZ)

### Operating systems

Windows

### What versions of the operating systems?

10.0.22621.521

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by FangCunWuChang** [comment]
I have already signed the CLA but I can't pass the CLA-check action.
![image](https://user-images.githubusercontent.com/40859406/195570720-46791ae6-c99f-42b6-a3d8-1d4d051e371f.png)

**Comment by tpoole** [comment]
Added in https://github.com/juce-framework/JUCE/commit/6c415e16e1bb62533fd01cb745ba1044bba61414. Thank you for reporting.
