### ISSUE TITLE
[Bug]: plug-in host window in AudioPluginHost size/position is not persisted when filtergraph is saved

### ISSUE THREAD

**Issue by Luke-kb** [juce-framework/JUCE#1137]
### Detailed steps on how to reproduce the bug

1. create a new filtergraph using AudioPluginHost (preferably with at least one plugin for comparison) 
2. resize and position the plug-in host window off the side. Do the same for the plugin.
3. save the filtergraph then close and reopen the filtergraph. the plugin retains its position and size, but the plugin-in window does not.

### What is the expected behaviour?

plug-in window should retain the size and position that it was when filtergraph was saved.

### Operating systems

macOS

### What versions of the operating systems?

12.6
JUCE 7.0.2

### Architectures

ARM

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
This is much more of a feature request than a bug report. Please create a topic on the JUCE forum: https://forum.juce.com/c/feature-requests
