### ISSUE TITLE
Error with all VST3 examples when build

### ISSUE THREAD

**Issue by alecss131** [juce-framework/JUCE#1141]
### Detailed steps on how to reproduce the bug

Just configure in cmake for msvc 2022, select JUCE_ENABLE_MODULE_SOURCE_GROUPS JUCE_COPY_PLUGIN_AFTER_BUILD JUCE_BUILD_EXTRAS JUCE_BUILD_EXAMPLES.
And in release build have error, setlocale return 1

### What is the expected behaviour?

Buld successfull

### Operating systems

Windows

### What versions of the operating systems?

Windows 10 22H2 19045.2130

### Architectures

64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Have you checked that the plug-in directories exist, and that you have permission to write to those locations?

**Comment by alecss131** [comment]
where is this folder?

**Comment by reuk** [comment]
For VST3 plugins, it's `C:\Program Files\Common Files\VST3`: https://helpcenter.steinberg.de/hc/en-us/articles/115000177084-VST-plug-in-locations-on-Windows

You'll need to make sure that the permissions of that folder are set such that your build can write there. You can change these permissions from the properties pane for the folder.

**Comment by alecss131** [comment]
> For VST3 plugins, it's `C:\Program Files\Common Files\VST3`: https://helpcenter.steinberg.de/hc/en-us/articles/115000177084-VST-plug-in-locations-on-Windows
> 
> You'll need to make sure that the permissions of that folder are set such that your build can write there. You can change these permissions from the properties pane for the folder.

fixed
