### ISSUE TITLE
[Bug]: drawImage() ignores fillAlphaChannelWithCurrentBrush

### ISSUE THREAD

**Issue by alexrodi** [juce-framework/JUCE#1143]
### Detailed steps on how to reproduce the bug

When drawing a transparent image using  juce::Graphics::drawImage(), the current brush's alpha is always applied:

```C++
auto img = juce::ImageCache::getFromMemory(BinaryData::img_png, BinaryData::img_pngSize);
auto colour = juce::Colours::transparentBlack;

void paint(juce::Graphics& g) override {
    g.setColour(colour);
    g.drawImage(img, bounds); // fillAlphaChannelWithCurrentBrush defaults to false
    // or be explicit
    g.drawImage(img, bounds, juce::RectanglePlacement::stretchToFit, false);
}
```

Results in `img` being drawn with 0 opacity (not visible)

When
```C++
auto colour = juce::Colours::black.withAlpha(0.5f);
```

Results in `img` being drawn with half opacity
  
  
The only way to mitigate this behavior is to use `g.setOpacity(1.0f)` before drawing the image
  
  
  
I'm on macOS 12.6 (21G115), MacBook Pro (13-inch, M1, 2020)
JUCE v7.0.2

### What is the expected behaviour?

When `fillAlphaChannelWithCurrentBrush` is defaulted to `false` or explicitly set to `false`, the image should draw with its original/full opacity

### Operating systems

macOS

### What versions of the operating systems?

12.6 (21G115)

### Architectures

ARM

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
This is by design. See the docs:

https://github.com/juce-framework/JUCE/blob/master/modules/juce_graphics/contexts/juce_GraphicsContext.h#L481
