### ISSUE TITLE
[Bug]:  The darkModeSettingChanged() callback function is not being called anymore

### ISSUE THREAD

**Issue by tonytorm** [juce-framework/JUCE#1144]
### Detailed steps on how to reproduce the bug

Simply register one of your top components as DarkModeSettingListener.

### What is the expected behaviour?

callback should be triggered by OS dark/light mode changes

### Operating systems

macOS

### What versions of the operating systems?

Mojave and Monterrey

### Architectures

x86_64, ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
I think this issue may have been fixed by this commit: https://github.com/juce-framework/JUCE/commit/c9ebb167a3a938dbf2285a09b483f79022ef636e.

I'm closing this issue for now, please let us know if you're still seeing this issue.
