### ISSUE TITLE
[Bug]: generated Documentation not reproducible

### ISSUE THREAD

**Issue by umlaeute** [juce-framework/JUCE#1148]
### Detailed steps on how to reproduce the bug

building the documentation (`docs/doxygen`) will produce different results, depending on how the filesystem.

the easiest way to reproduce this, is probably using the `disorderfs` tool as found in popular Linux distributions (e.d. Debian, Ubuntu,...):

```
git clone  https://github.com/juce-framework/JUCE
# create the reference documentation
cp -r JUCE JUCE-ordered
make -C JUCE-ordered/docs/doxygen/
# re-create the documentation on a filesystem with different ordering
mkdir JUCE-disordered
disorderfs --shuffle-dirents=yes JUCE JUCE-disordered
make -C JUCE-disordered/docs/doxygen/
# compare the two
diff -qr JUCE-ordered/docs/doxygen/doc/ JUCE-disordered/docs/doxygen/doc/
```

### What is the expected behaviour?

the generated documentation should be bit-for-bit identical

### Operating systems

Linux

### What versions of the operating systems?

Debian/bookworm

### Architectures

x86_64

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by umlaeute** [comment]
the easiest fix for this is probably to just sort the directory entries when processing them.

E.g. replace `os.listdir()` wuth `sorted(os.listdir())` in https://github.com/juce-framework/JUCE/blob/965d0ca4be178c4a0000b116d460e15c30311992/docs/doxygen/process_source_files.py#L90 and https://github.com/juce-framework/JUCE/blob/965d0ca4be178c4a0000b116d460e15c30311992/docs/doxygen/process_source_files.py#L139

**Comment by tpoole** [comment]
Thank you for reporting. Fixed here: https://github.com/juce-framework/JUCE/commit/e669fb117eebf496a85de10cbba39cf9feeef69b.
