### ISSUE TITLE
[Bug]: MacOS 13 returns UnknownOS in SystemStats::getOperatingSystemType()

### ISSUE THREAD

**Issue by hautetechnique** [juce-framework/JUCE#1154]
### Detailed steps on how to reproduce the bug

Apple has changed the way it's using OS numbering on MacOS, and has started to use the Major number for each years new release, starting with MacOS 11. 

Juce has added support for the versions 11 and 12 manually, but lacks support for future version. The function simply returns UnknownOS in juce_mac_SystemStats.cpp at line 119.

This causes unexpected behauvour, since on the fly operating system checking should be done with:

`getOperatingSystemType() & SystemStats::MacOSX` 

I've checked the Develop branche, and 13 is now added, but:

I think this function should be re-designed so that it will work for future versions as well. At this moment, Juce is behind on the current version, and Beta's of future version will also be invalid. 

Adding the new version each year is not a sustainable solution.

A quick fix for me now is to use ENV variables en check with ifdefs.

### What is the expected behaviour?

function should return the correct os version in newer version, despite the literal implementation

### Operating systems

macOS

### What versions of the operating systems?

13

### Architectures

x86_64, ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
https://github.com/juce-framework/JUCE/commit/83cd6dfc80ca7b74671630d6a7477285e378f559
