### ISSUE TITLE
[Bug]: LV2 plug-ins on macOS crashes DAW when removing with open editor

### ISSUE THREAD

**Issue by fholzm** [juce-framework/JUCE#1174]
### Detailed steps on how to reproduce the bug

When trying to remove a LV2 plug-in in Reaper on macOS (Intel and ARM), the DAW crashes due to a segfault. This occurs only if the editor is open, it doesn't crash if the editor is closed or the whole track is being removed. This behavior can be observed with different plug-ins (I've tested it with the [IEM Plug-in Suite](https://git.iem.at/audioplugins/IEMPluginSuite) on v7.0.3 and the empty [pamplejuce](https://github.com/sudara/pamplejuce) template on v7.0.2 and the latest JUCE commit on the develop branch). It happens during or shortly after `LV2_SYMBOL_EXPORT const LV2_Descriptor* lv2_descriptor (uint32_t index)` is called in `juce_LV2_Client.cpp`.

### What is the expected behaviour?

Removing the plug-in without a crash

### Operating systems

macOS

### What versions of the operating systems?

13.0.1 (M1 Pro)
12.6.2 (Intel)

### Architectures

Other

### Plug-in formats (if applicable)

LV2

### Plug-in host applications (DAWs) (if applicable)

Reaper

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
I've debugged this a bit. At the moment, it's unclear whether the problem is in JUCE or in REAPER.

I've submitted an issue on the REAPER forum. Hopefully someone with access to the REAPER source will be able to provide a few more details.

https://forum.cockos.com/showthread.php?p=2630874#post2630874

**Comment by fholzm** [comment]
The issue seems to be fixed with the REAPER 0106 [development build](https://www.landoleet.org), so I'll close this issue

**Comment by reuk** [comment]
I can confirm that the issue seems to be resolved in 6.73+dev0109
