### ISSUE TITLE
[Bug]: SCHED_IDLE isn't defined on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [juce-framework/JUCE#1178]
### Detailed steps on how to reproduce the bug

[here](https://github.com/juce-framework/JUCE/blob/master/modules/juce_core/native/juce_posix_SharedCode.h#L932)

### What is the expected behaviour?

n/a

### Operating systems

Other

### What versions of the operating systems?

7.0.3

### Architectures

x86_64

### Stacktrace

```shell
n/a
```

### Plug-in host applications (DAWs) (if applicable)

n/a

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/29a90a0231b1e1a9fa5878aba880fb8fcd979624.

Thank you for reporting.
