### ISSUE TITLE
[Bug]: Linux linker error when JUCE_USE_CURL and JUCE_LOAD_CURL_SYMBOLS_LAZLY are both disabled

### ISSUE THREAD

**Issue by reales** [juce-framework/JUCE#1180]
### Detailed steps on how to reproduce the bug

Any project with JUCE_USE_CURL and JUCE_LOAD_CURL_SYMBOLS_LAZLY disabled will result in linker error under Linux.

### What is the expected behaviour?

Compiler error.

To compile correctly, simply **enabling** JUCE_LOAD_CURL_SYMBOLS_LAZLY and leaving JUCE_USE_CURL **disabled** does the trick, but Projucer should handle the issue automatically before exporting the makefile.

### Operating systems

Linux

### What versions of the operating systems?

Ubuntu 20 LTS.

### Architectures

x86_64

### Stacktrace

```shell
/usr/bin/ld: /tmp/MyPlugin.so.4zCwzM.ltrans59.ltrans.o: in function `juce::WebInputStream::WebInputStream(juce::URL const&, bool)':
<artificial>:(.text+0x63cc): undefined reference to `curl_easy_init'
/usr/bin/ld: <artificial>:(.text+0x63d3): undefined reference to `curl_version_info'
/usr/bin/ld: <artificial>:(.text+0x63e9): undefined reference to `curl_easy_setopt'
/usr/bin/ld: <artificial>:(.text+0x63f8): undefined reference to `curl_easy_cleanup'
/usr/bin/ld: <artificial>:(.text+0x6407): undefined reference to `curl_easy_getinfo'
/usr/bin/ld: <artificial>:(.text+0x641b): undefined reference to `curl_multi_add_handle'
/usr/bin/ld: <artificial>:(.text+0x642a): undefined reference to `curl_multi_cleanup'
/usr/bin/ld: <artificial>:(.text+0x6440): undefined reference to `curl_multi_fdset'
/usr/bin/ld: <artificial>:(.text+0x6447): undefined reference to `curl_multi_info_read'
/usr/bin/ld: <artificial>:(.text+0x6453): undefined reference to `curl_multi_init'
/usr/bin/ld: <artificial>:(.text+0x645a): undefined reference to `curl_multi_perform'
/usr/bin/ld: <artificial>:(.text+0x6466): undefined reference to `curl_multi_remove_handle'
/usr/bin/ld: <artificial>:(.text+0x646d): undefined reference to `curl_multi_timeout'
/usr/bin/ld: <artificial>:(.text+0x6479): undefined reference to `curl_slist_append'
/usr/bin/ld: <artificial>:(.text+0x6480): undefined reference to `curl_slist_free_all'
collect2: error: ld returned 1 exit status
```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
I'm unable to reproduce this issue on develop. The only references to the curl symbols that I can see are in juce_curl_Network.cpp, which is only built if `JUCE_USE_CURL` is enabled. Did you definitely remember to `make clean` after re-saving the Projucer project?

**Comment by reales** [comment]
> Did you definitely remember to `make clean` after re-saving the Projucer project?

Yes, full clean was made. Will try with develop as soon as possible, thanks.

**Comment by reales** [comment]
Just compiled using JUCE 7.0.4 released a few hours ago and the issue has been fixed. Excellent work!
