### ISSUE TITLE
[Bug]: Detecting Logic doesn't work after Logic version 10.7.5

### ISSUE THREAD

**Issue by maxjvh** [juce-framework/JUCE#1186]
### Detailed steps on how to reproduce the bug

```c++
auto daw = juce::PluginHostType();
daw.isLogic(); // returns false in Logic
```

### What is the expected behaviour?

i'd expect `daw.isLogic()` to return `true` when running the plugin in Logic

### Operating systems

macOS 12.5.1 (ARM, haven't tested on Intel)

### Plug-in formats (if applicable)

AU

### Plug-in host applications (DAWs) (if applicable)

Logic Pro 10.7.5, Logic Pro 10.7.6

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
This is a known bug in Logic 10.7.5 and 10.7.6.

https://forum.juce.com/t/logic-10-7-5-reporting-wrong-host/53658/10?u=reuk
