### ISSUE TITLE
[Bug]: Juceaide fails due to icon generation when cross-compiling for Windows ARM64 on Azure Agent

### ISSUE THREAD

**Issue by Sidelobe** [juce-framework/JUCE#1188]
### Detailed steps on how to reproduce the bug

To reproduce:  
* copy to `examples/Cmake/GuiApp` to a new directory
* clone JUCE to a dir called `JUCE`
* `CmakeLists.txt`:  uncomment `add_subdirectory(JUCE)`
* `CmakeLists.txt`:  add `ICON_BIG` property to `juce_add_gui_app()`, e.g.  `JUCE/extras/AudioPluginHost/Source/JUCEAppIcon.png`
* `mkdir build; cd build; cmake .. -G "Visual Studio 17 2022" -DCMAKE_GENERATOR_PLATFORM=arm64` in this new directory

Azure pipeline job:
```
  - job: WindowsARM64
    pool:
      name: Azure Pipelines
      vmImage: 'windows-2022'
    steps:
    - script: |
        if not exist "build" mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -DCMAKE_GENERATOR_PLATFORM=arm64 ..\dependencies
```
---

Locally, I can build fine with `Windows SDK version 10.0.22621.0 to target Windows 10.0.25272` with visual Studio 2022 for ARM (Version 17.4.3).

I've tried with `windows-latest` and Visual Studio 2022 (v17) and `windows-2019` with Visual Studio 2019 (v16), same error.

`CMakeOutput.log` and `CMakeError.log` do not provide any additional information.

### What is the expected behaviour?

Cmake is able to generate the Visual Studio solution succesfully.

### Operating systems

Windows

### What versions of the operating systems?

Fails with:
* Microsoft Windows Server 2019:  10.0.17763, `windows-latest` and Visual Studio 2022 (v17) 
* Microsoft Windows Server 2022: 10.0.20348, `windows-2019` with Visual Studio 2019 (v16)

### Architectures

ARM

### Stacktrace

```shell
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
CMake Error at dependencies/JUCE/extras/Build/CMake/JUCEUtils.cmake:459 (message):
  Running juceaide failed:

Call Stack (most recent call first):
  dependencies/JUCE/extras/Build/CMake/JUCEUtils.cmake:515 (_juce_execute_juceaide)
  dependencies/JUCE/extras/Build/CMake/JUCEUtils.cmake:567 (_juce_generate_icon)
-- Configuring incomplete, errors occurred!
See also "D:/a/1/s/deploy/build/CMakeFiles/CMakeOutput.log".
  dependencies/JUCE/extras/Build/CMake/JUCEUtils.cmake:1759 (_juce_configure_bundle)
See also "D:/a/1/s/deploy/build/CMakeFiles/CMakeError.log".
  CMakeLists.txt:191 (juce_add_gui_app)

##[error]Cmd.exe exited with code '1'.
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Sidelobe** [comment]
UPDATE: If I remove the icon, I can generate the solution with cmake. 
During build, however, I get the following message, which IMO could point to juceaide being built for x64 instead of arm64:

`This version of D:\a\1\s\deploy\build\dependencies\JUCE\tools\extras\Build\juceaide\juceaide_artefacts\Debug\juceaide.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

**Comment by Sidelobe** [comment]
I've come to the conclusion that this is probably not a 'bug', but rather a lack of support of cross-compilation in JUCE... please correct me if I'm wrong

**Comment by reuk** [comment]
Thanks for reporting. The following change should allow JUCE projects to be cross-compiled from x64 to arm64 on Windows:

https://github.com/juce-framework/JUCE/commit/070a6b35e93ca15deed8b059dfa0d491488f0519
