### ISSUE TITLE
[Bug]: GenericAudioProcessorEditor seems to always reset Choice parameters to their default values

### ISSUE THREAD

**Issue by YPares** [juce-framework/JUCE#1191]
### Detailed steps on how to reproduce the bug

In several projects using the GenericAudioProcessorEditor, on Windows, both on Bitwig and Ableton, the values of AudioParameterChoice parameters are reset to their default values when the VST3 plugin reloads.

See https://forum.juce.com/t/choice-parameters-are-not-reloaded-correctly-in-bitwig-when-plugin-restarts/54719 and https://forum.juce.com/t/recalling-choice-parameter-state-with-genericaudioprocessoreditor-in-ableton/54137

Just create a dummy new project with the GenericAudioProcessorEditor and one AudioParameterChoice. Build it to VST3, load the VST3 in a new Ableton or Bitwig project on Windows, change the value of that parameter in the GUI. Save your project, quit & reopen it, the change to the parameter will be overriden, and back to its initial default value.

### What is the expected behaviour?

When reopening a Bitwig/Ableton project on Windows, VST3 choice parameters should be restored to their latest value, instead of the default one.

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

x86_64

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

Ableton, Bitwig

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Looks to me like this line might be missing a `dontSendNotification`. You could try adding that in and see whether it solves the problem for you. If it does, we can get that merged shortly.

**Comment by YPares** [comment]
@reuk Hi! Funny, I was looking at the code and it's exactly what I ended up wondering :)

And indeed that just led me to try `        box.setSelectedItemIndex (index, dontSendNotification);` and it works!

**Comment by reuk** [comment]
Fixed here: https://github.com/juce-framework/JUCE/commit/ff534baf5f5d83e69cb7e5f4b8acfcbcbfdaaec6
