### ISSUE TITLE
[Bug]: Audio Processor crashes when using FL Studio's patcher.

### ISSUE THREAD

**Issue by Speechrezz** [juce-framework/JUCE#1193]
### Detailed steps on how to reproduce the bug

This bug happens on both Windows and MacOS, only with effects plugins made with JUCE 7 (JUCE 6 and older work fine).

**How to reproduce:**
1) Open the plugin in any effects slot in a mixer channel.
2) Delete that plugin from the mixer channel.
3) Open patcher and load the same plugin.
4) The plugin may crash (tends to happen on MacOS) or just not process the audio (typical on Windows).

**Example of the issue on Windows 10:**
![FL64_wNy598HkBt](https://user-images.githubusercontent.com/27645650/216215869-9c98904e-712f-47db-9d15-1aeeeb4deb3f.png)

**Here is FL Studio's debug log:**
```
Patcher says: Rezonator says: "Rezonator" crashed while processing. Disabled.
Patcher says: Rezonator says: EXCEPTION (Eff_Render) Access violation at address 00007FFB84B9483D in module 'Rezonator.vst3'. Read of address 0000000000000000
```

We've tested many of our various effects plugins with very different code and the problem always occurs. The problem may be something to do with JUCE incorrectly reading the audio input configuration from patcher.

**Some screenshots of Visual Studio's stack traces:**
![image](https://user-images.githubusercontent.com/27645650/216217957-4feddd4b-b3ff-4ccc-9716-1bdae02a7763.png)
![image](https://user-images.githubusercontent.com/27645650/216217988-e2285ae7-47e1-4b07-8964-95da15fa36e7.png)

### What is the expected behaviour?

For the plugin to work as normal in FL Studio's patcher.

### Operating systems

Windows, macOS

### What versions of the operating systems?

Windows 10 Home
Version: 22H2
OS Build: 19045.2486
Processor: Ryzen 5800X

MacOS Ventura 13.2
Macbook Pro 14" with an M2 Pro.

### Architectures

x86_64, ARM

### Stacktrace

The stacktrace differs on every run, but a friend and I may have nailed it down to:
```
modules\juce_audio_processors\format_types\juce_VST3Common.h 
```
Somewhere in the class
```
ClientBufferMapperData
```
Though we aren't sure.

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

FL Studio 20 & 21

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
I believe this is a bug in the FL Patcher. Debugging this issue, I can see that the hosted VST3's `process` is called before (or during) `setActive`, but this is not allowed according to the VST3 documentation:

https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Workflow+Diagrams/Audio+Processor+Call+Sequence.html

I recommend filing a bug report with Image Line.

**Comment by Speechrezz** [comment]
Thanks for looking into this, I will file a bug report with Image-Line!

**Comment by reuk** [comment]
A workaround was added to JUCE here: https://github.com/juce-framework/JUCE/commit/13d27987f49914be1ca7672c4da0818872eddfb0

**Comment by Speechrezz** [comment]
Thank you, I will give this commit a spin ASAP!
I have also filed a bug report with Image-Line, I will keep everyone posted if anything happens.

**Comment by Speechrezz** [comment]
I tested it both on my Windows and Mac machines, and the bug still persists, even when using the latest commit. This is a pretty puzzling bug, really has me scratching my head.

**Comment by Speechrezz** [comment]
I think I've actually solved it: https://github.com/juce-framework/JUCE/pull/1196

I've tested this workaround many times in FL Studio and it seems to work! Sometimes FL Studio's patcher just calls `process()` and `setActive()` in the wrong order in a way that a mutex doesn't seem to fix.
