### ISSUE TITLE
[Bug]: Android: HeapBlock::calloc() is called on every Oboe audio callback

### ISSUE THREAD

**Issue by atsushieno** [juce-framework/JUCE#1206]
### Detailed steps on how to reproduce the bug

I have been debugging `extras/AudioPluginHost` on Android and noticed that the Oboe audio callback implementation ([`OboeAudioIODevice::OboeSessionImpl::onAudioReady()`](https://github.com/juce-framework/JUCE/blob/6df7e46e2617694907378ea84ae978b0ec3039f9/modules/juce_audio_devices/native/juce_android_Oboe.cpp#L789)) calls `juce::HeapBlock::calloc()` :

>                 inputStreamNativeBuffer.calloc (static_cast<size_t> (numInputChannels * bufferSize));

As long as I observed on Android Studio debugger it is indeed called on every Oboe audio callback.

### What is the expected behaviour?

Allocation should be performed only once.

### Operating systems

Android

### What versions of the operating systems?

tried on Android 33 arm64 emulator, but it should apply to any version that can perform Oboe.

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, that should be fixed here:

https://github.com/juce-framework/JUCE/commit/76589ee8005dd76c9628429440363d086d1ca8cf
