### ISSUE TITLE
[Bug]: warning: unknown pragma ignored [-Wunknown-pragmas]

### ISSUE THREAD

**Issue by yurivict** [juce-framework/JUCE#1208]
### Detailed steps on how to reproduce the bug

There's a wrong pragma statement in the code:

```
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26:
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:42:
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_processors/format_types/juce_VST3Headers.h:116:
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/vst/vsttypes.h:19:
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/base/fstrdefs.h:19:
In file included from /usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/base/ftypes.h:19:
/usr/ports/devel/juce/work/JUCE-7.0.5/modules/juce_audio_processors/format_types/VST3_SDK/pluginterfaces/base/fplatform.h:215:10: warning: unknown pragma ignored [-Wunknown-pragmas]
        #pragma error unknown platform
                ^
```

Version: 7.0.5

### What is the expected behaviour?

n/a

### Operating systems

Linux

### What versions of the operating systems?

n/a

### Architectures

ARM

### Stacktrace

```shell
x
```

### Plug-in host applications (DAWs) (if applicable)

x

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
See https://github.com/juce-framework/JUCE/pull/881.

**Comment by yurivict** [comment]
The compiler error says "warning: unknown pragma ignored".
This pragma is not a valid C++ construct.

**Comment by tpoole** [comment]
This is a warning from within the official, bundled VST3 SDK which we will not modify.

Please read the content of the thread I linked, which explains how this should be worked around.
