### ISSUE TITLE
[Bug]: Building with Code::Blocks fails with an error regarding juce_LinuxSubprocessHelperBinaryData.cpp

### ISSUE THREAD

**Issue by probonopd** [juce-framework/JUCE#1212]
### Detailed steps on how to reproduce the bug

Try to build a plugin for Windows with Code::Blocks.

### What is the expected behaviour?

Compilation succeeds.

### Operating systems

Windows

### What versions of the operating systems?

Windows 10

### Architectures

x86_64

### Additional information

Manually editing the `.cbp` file and deleting the section

```
    <Unit filename="pre_build/juce_LinuxSubprocessHelperBinaryData.cpp">
      <Option target="Shared Code | Debug"/>
      <Option target="Shared Code | Release"/>
    </Unit>
```

resolves this. I wonder what this Linux specific part is doing in builds for Windows in the first place. I think it should not be there.

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by szarvas** [comment]
Thank you for reporting.

This issue is now fixed by 
https://github.com/juce-framework/JUCE/commit/921baaeb57842de0266f7ff88b205532e674014e
