### ISSUE TITLE
[Bug]: The whole UI gets repainted constantly in the latest develop

### ISSUE THREAD

**Issue by jesusginard** [juce-framework/JUCE#1217]
### Detailed steps on how to reproduce the bug

No need to do anything special, building the default app or plugin and set the ENABLE_REPAINTING_DEBUGGING flag shows it.

### What is the expected behaviour?

Only paint when necessary.

### Operating systems

macOS

### What versions of the operating systems?

Ventura 13.2.1

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, fixed here: https://github.com/juce-framework/JUCE/commit/68beb74820db3d29caf5863b3464551f9c4e38fb
