### ISSUE TITLE
[Bug]: juce::dsp::DelayLine Wraps Early using Lagrange3rd Interpolation

### ISSUE THREAD

**Issue by leonp-s** [juce-framework/JUCE#1252]
### Detailed steps on how to reproduce the bug

When using the DSP Delay with Lagrange3rd interpolation where the fractional delay length is within 1 sample of the maximum delay length, the dry signal is audible (attenuated) along with the delayed signal.

This behaviour is not observed when using other interpolation types.

Steps to reproduce:

- Create a juce::dsp::DelayLine<…, Lagrange3rd> setting the maximum delay length in samples to a length N. 
- Call prepare on the processor. 
- Set the delay length to within 1 sample less than the maximum delay length N. (e.g. N - 0.5f)
- Call process.

This should cause the dry signal to be heard at an attenuated level along with the delayed signal.

We believe this is a result of Lagrange3rd requiring 4 samples i.e. 2 samples more than the maximum delay length N. However, in the current implementation only a single extra sample is accounted for. This results in an early wrap of 4th interpolation sample index to the current write position causing the dry signal to be heard. 

### What is the expected behaviour?

Only the delayed signal should be heard, as is the case with the other interpolation methods with this configuration.

### Operating systems

macOS

### What versions of the operating systems?

Monterey 12.6.3

### Architectures

64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Thank you. Fixed here: https://github.com/juce-framework/JUCE/commit/0037e44a23a1fb60e974498abf198cd25eb7ee5a
