### ISSUE TITLE
[Bug]: CMake Instructions not working with VSCode OSX

### ISSUE THREAD

**Issue by hhaudio** [juce-framework/JUCE#1256]
### Detailed steps on how to reproduce the bug

I downloaded this JUCE cmake project: https://github.com/stekyne/PhaseVocoder/tree/master

and tried to build it in VSCode after using the following instructions from the JUCE repo: https://github.com/juce-framework/JUCE/blob/master/docs/CMake%20API.md

Using find_package
To install JUCE globally on your system, you'll need to tell CMake where to place the installed files.

# Go to JUCE directory
cd /path/to/clone/JUCE
# Configure build with library components only
cmake -B cmake-build-install -DCMAKE_INSTALL_PREFIX=/path/to/JUCE/install
# Run the installation
cmake --build cmake-build-install --target install
In your project which consumes JUCE, make sure the project CMakeLists.txt contains the line find_package(JUCE CONFIG REQUIRED). This will make the JUCE modules and CMake helper functions available for use in the rest of your build. Then, run the build like so:

# Go to project directory
cd /path/to/my/project
# Configure build, passing the JUCE install path you used earlier
cmake -B cmake-build -DCMAKE_PREFIX_PATH=/path/to/JUCE/install
# Build the project
cmake --build cmake-build

When I try to run in VSCode I then get the following error:

CMake Error at CMakeLists.txt:7 (find_package):Could not find a package configuration file provided by "JUCE" with any of
the following names:

  JUCEConfig.cmake
  juce-config.cmake

Add the installation prefix of "JUCE" to CMAKE_PREFIX_PATH or set
"JUCE_DIR" to a directory containing one of the above files.  If "JUCE"
provides a separate development package or SDK, be sure it has been
installed.

### What is the expected behaviour?

JUCE Project Builds in CMAKE

### Operating systems

macOS

### What versions of the operating systems?

13.0

### Architectures

64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
https://forum.juce.com/t/juce-cmake-instruction-not-working-with-vscode-osx/57404
