### ISSUE TITLE
[Bug]: Setting JUCE_COPY_PLUGIN_AFTER_BUILD as false does not function

### ISSUE THREAD

**Issue by himwho** [juce-framework/JUCE#1258]
### Detailed steps on how to reproduce the bug

using cmake i have tested the following in the project's CMakeLists.txt:
- `set_property(GLOBAL PROPERTY JUCE_COPY_PLUGIN_AFTER_BUILD OFF)`
- `set_directory_properties(PROPERTIES JUCE_COPY_PLUGIN_AFTER_BUILD OFF)`
- `set(JUCE_COPY_PLUGIN_AFTER_BUILD OFF)`

however building the project still attempts to install the plugins in the dir, specifically this is an issue for me setting up build machines and cmake not being able to copy the AAX plugin to the installation folder

### What is the expected behaviour?

I would expect that setting `JUCE_COPY_PLUGIN_AFTER_BUILD` to false would mean that the plugins are not attempted to be installed anywhere and just reside in the _artefacts dir of the build directory of that project

### Operating systems

macOS

### What versions of the operating systems?

macOS 13.4.1

### Architectures

ARM

### Stacktrace

```shell
/Volumes/git/plugin/build/plugin_artefacts/Debug/AAX/plugin.aaxplugin: code has no resources but signature indicates they must be present
-- Replacing invalid signature with ad-hoc signature
-- Up-to-date: /Library/Application Support/Avid/Audio/Plug-Ins/plugin.aaxplugin
CMake Error at /Volumes/git/plugin/JUCE/extras/Build/CMake/copyDir.cmake:24 (file):
  file INSTALL cannot set permissions on "/Library/Application
  Support/Avid/Audio/Plug-Ins/plugin.aaxplugin": Operation not permitted.


Command PhaseScriptExecution failed with a nonzero exit code
```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Have you set `COPY_PLUGIN_AFTER_BUILD` in the `juce_add_plugin` call?

**Comment by himwho** [comment]
wow, @reuk good callout! you were right, i had that which was obviously overriding my other attempts; I guess we can close this as there really is no bug at all
