### ISSUE TITLE
[Bug]: WebInputStream::parseHttpHeaders discards the first header

### ISSUE THREAD

**Issue by audiovention** [juce-framework/JUCE#1260]
### Detailed steps on how to reproduce the bug

Create a juce::URL for whatever webpage you wish.
Create juce::URL::InputStreamOptions and request to see the response headers (using withResponseHeaders).
createInputStream from the URL using the options.
Inspect the response headers returned and compare them to the headers obtained by running "curl -v" on the same webpage. 
Notice in juce the first header is missing. 

Likely culprit is the WebInputStream::parseHttpHeaders method, and specifically the lines:
`    // ignore the first line as this is the status line `
`    for (int i = 1; i < headerLines.size(); ++i)`

although I'm not sure what's the behaviour on other OSs.

### What is the expected behaviour?

You should get the same number of headers in juce. 

### Operating systems

Linux

### What versions of the operating systems?

Ubuntu 22.10

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by audiovention** [comment]
reading through the code it's likely only the curl implementation is affected, as the others don't use that method.
However, getRequestHeaders() is probably broken on every platform as it uses that method and discards the first header.

**Comment by reuk** [comment]
Thanks for reporting! That's fixed here: https://github.com/juce-framework/JUCE/commit/a5b74332c203701c90f57499feaa0e346dfa91b4
