### ISSUE TITLE
[Bug]: Typo in CMake API.md

### ISSUE THREAD

**Issue by Paulybri** [juce-framework/JUCE#1273]
### Detailed steps on how to reproduce the bug

In the `VST2_CATEGORY ` section, in the options it says `kPlugCategMatering ` instead of `kPlugCategMastering `

### What is the expected behaviour?

To have no typo

### Operating systems

macOS

### What versions of the operating systems?

N/A

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Fixed here: https://github.com/juce-framework/JUCE/commit/1eea4766ceb47948d102f94538ec66c73aa135cd

Thank you for reporting.
