### ISSUE TITLE
[Bug]: AU example plugins crash on M1 in reaper/logic, when arming/unarming track

### ISSUE THREAD

**Issue by onar3d** [juce-framework/JUCE#1276]
### Detailed steps on how to reproduce the bug

This happens with the unmodified Example AU plugins - not my own code:

I just pulled and built the latest JUCE develop branch to make sure - commit:
a4dfd8d6c6f499b9016157b9411653923eace215

I built (debug) with the following flags:
-G Xcode -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DJUCE_COPY_PLUGIN_AFTER_BUILD=ON -DCMAKE_OSX_ARCHITECTURES=arm64

I then start Reaper and attach to process.
I add a JUCE AU plugin to an audio track - any plugin, even the simplest example will do.

Then, I “mash” the arm-record button on the track - be it Reaper or Logic, the crash is the same.

I know that stack trace isn’t too informative, but I can’t find what process I need to be attaching to to get the actual plugin one - is there another process for Reaper as for Logic’s “AUHostingServiceXPC_arrow”?
(I can’t test with Logic on my machine, I have no license…)

### What is the expected behaviour?

That it would not crash - as is the case with e.g. Apple's AU plugins.

### Operating systems

macOS

### What versions of the operating systems?

Ventura

### Architectures

ARM

### Stacktrace

```shell
_os_object_retain 0x0000000190dcee24
RenderContextChangeGenerator::checkChange() 0x0000000192c04a4c
AudioUnitRender 0x0000000192deb720
AU_Plugin::ProcessSamplesImpl(float*, float*, int, int, int, int, double, MIDI_eventlist*, int) 0x0000000102a02b34
AU_Plugin::ProcessSamples(double*, int, int, int, int, double, MIDI_eventlist*, double, double, bool, bool) 0x0000000102a02288
FxDsp::processFxDsp(int, double*, int, int, int, int, double, midi_List*, double, bool, double, double, double, double, int) 0x000000010287abe8
FxChain::ProcessChainDsp(FxDsp*, int&, int, int, double*, int, int, midi_List*, double, double, double, double, double, int, double, int, bool, bool, int&, int&, int) 0x00000001028a218c
FxChain::ProcessChain(int, double*, int, int, int, int, double, midi_List*, double, bool, int) 0x00000001028a188c
MediaTrack::RenderSamples_nocache(double, long long, double*, int, int, double, MediaTrack* const*, int, int*, bool, int, int, bool*, SyncSMP_Context*) 0x0000000102623e48
MediaTrack::RenderSamples(double, long long, int, Track_RS_Output*, int, double, MediaTrack* const*, int, midi_List*, int, int, int, int, int, MediaTrack::Track_SendRec*, bool*, SyncSMP_Context*) 0x00000001026196dc
MediaTrack::RenderSamples_nocache(double, long long, double*, int, int, double, MediaTrack* const*, int, int*, bool, int, int, bool*, SyncSMP_Context*) 0x0000000102621614
ProcessProject(ReaProject*, int, int) 0x000000010268e584
audiostream_onsamples(double**, int, double**, int, int, int) 0x000000010268d498
audioStreamer_CoreAudio::onsamples(AudioBufferList const*, float*) 0x00000001026f4e74
caInproc(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) 0x00000001026f5d74
HALC_ProxyIOContext::IOWorkLoop() 0x000000019325793c
invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) 0x000000019325587c
HALB_IOThread::Entry(void*) 0x00000001933b8564
_pthread_start 0x0000000190f7ffa8
```

### Plug-in host applications (DAWs) (if applicable)

Logic and Reaper

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Anthony-Nicholls** [comment]
Thanks for reporting. This should be fixed in the latest version of JUCE available on both the master and develop branches.
