### ISSUE TITLE
[Bug]: JUCE failed to cmake with error C2084 on ARM64EC configuration on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [juce-framework/JUCE#1278]
### Detailed steps on how to reproduce the bug

Hi All,

**Environment:**
VS 2022 + Windows Server 2022 Datacenter

JUCE failed to cmake with 'error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file' on ARM64EC configuration on windows with MSVC. It can be reproduced on latest commit 22df0d2 on master branch. Could you please help look at this issue? Thanks in advance.

**Steps to reproduce the behavior:**
1. git clone https://github.com/juce-framework/JUCE F:\gitP\juce-framework\JUCE
2. Open a VS2022 x64 cmd && "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. cd F:\gitP\juce-framework\JUCE && mkdir build_arm64ec && cd build_arm64ec
4. cmake -G "Visual Studio 17 2022" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON ..

**Error Message:**

cmake -G "Visual Studio 17 2022" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON ..

-- The C compiler identification is MSVC 19.38.33123.96
-- The CXX compiler identification is MSVC 19.38.33123.96
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring juceaide
-- Building juceaide
CMake Error at extras/Build/juceaide/CMakeLists.txt:139 (message):
  Failed to build juceaide

  MSBuild version 17.7.2+d6990bcfa for .NET Framework

    Checking File Globs
    Checking Build System
    Building Custom Rule F:/gitP/juce-framework/JUCE/extras/Build/juceaide/CMakeLists.txt
    Main.cpp
    juce_build_tools.cpp
    juce_gui_basics.cpp
    juce_graphics.cpp
    juce_events.cpp
    juce_core.cpp
    juce_data_structures.cpp

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]

-- Configuring incomplete, errors occurred!
See also "F:/gitP/juce-framework/JUCE/build_arm64ec/CMakeFiles/CMakeOutput.log".

### What is the expected behaviour?

cmake pass.

### Operating systems

Windows

### What versions of the operating systems?

VS 2022 + Windows Server 2022 Datacenter

### Architectures

64-bit

### Stacktrace

```shell
cmake -G "Visual Studio 17 2022" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON ..
-- The C compiler identification is MSVC 19.38.33123.96
-- The CXX compiler identification is MSVC 19.38.33123.96
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring juceaide
-- Building juceaide
CMake Error at extras/Build/juceaide/CMakeLists.txt:139 (message):
  Failed to build juceaide

  MSBuild version 17.7.2+d6990bcfa for .NET Framework



    Checking File Globs
    Checking Build System
    Building Custom Rule F:/gitP/juce-framework/JUCE/extras/Build/juceaide/CMakeLists.txt
    Main.cpp
    juce_build_tools.cpp
    juce_gui_basics.cpp
    juce_graphics.cpp
    juce_events.cpp
    juce_core.cpp
    juce_data_structures.cpp

  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_core\juce_core.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_events\juce_events.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_gui_basics\juce_gui_basics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6300,1): error C2084: function
  'LONG64 MultiplyExtract128(LONG64,LONG64,BYTE)' already has a body
  (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3913,1): message : see previous
  definition of 'MultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(6338,1): error C2084: function
  'DWORD64 UnsignedMultiplyExtract128(DWORD64,DWORD64,BYTE)' already has a
  body (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]


  C:\Program Files (x86)\Windows
  Kits\10\Include\10.0.22621.0\um\winnt.h(3951,1): message : see previous
  definition of 'UnsignedMultiplyExtract128' (compiling source file
  F:\gitP\juce-framework\JUCE\modules\juce_graphics\juce_graphics.cpp)
  [F:\gitP\juce-framework\JUCE\build_arm64ec\tools\extras\Build\juceaide\juceaide.vcxproj]




-- Configuring incomplete, errors occurred!
See also "F:/gitP/juce-framework/JUCE/build_arm64ec/CMakeFiles/CMakeOutput.log".
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting. This issue should be fixed by this commit: https://github.com/juce-framework/JUCE/commit/6b54d2722b8108806cda479a3796e22b27e1b841
