### ISSUE TITLE
[Bug]: GUI Editor - Can't resize slider in 7.0.6 and 7.0.7

### ISSUE THREAD

**Issue by realshafer** [juce-framework/JUCE#1283]
### Detailed steps on how to reproduce the bug

In the GUI Editor, slider cannot adopt new size by using attributes pane. If using mouse click-and-drag, slider visually fights any changes. Rolling back to 7.0.5, the slider resizes as expected.

### What is the expected behaviour?

The slider should resize when changing from attributes pane or mouse click-and-drag.

### Operating systems

macOS

### What versions of the operating systems?

I tried on two systems:
iMac Intel i9, MacOS 14.0
Macbook Pro M2, MacOS 13.2.1

### Architectures

x86_64, ARM

### Stacktrace

```shell
n/a
```

### Plug-in host applications (DAWs) (if applicable)

n/a

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by soundsbyjs** [comment]
Hello! I'm going to see if I can reproduce the bug on Linux. Followup shortly.

**Comment by reuk** [comment]
That's right. To confirm, we are no longer maintaining the GUI editor in the Projucer. It will be removed in a future version of JUCE.
