### ISSUE TITLE
[Bug]: Projucer: "Incorrect path" message when running from cloned repo

### ISSUE THREAD

**Issue by drkvogel** [juce-framework/JUCE#1284]
### Detailed steps on how to reproduce the bug

I upgraded my MacBook to macOS Somona recently, which required an upgrade of Xcode to version 15 (from 14).

When I tried building Projucer 7.0.7 projects in Xcode 15, I got various "Cycle inside... building could produce unreliable results." errors. 

This thread: [VST/AU builds fail after upgrading to Xcode 15 - JUCE ](https://forum.juce.com/t/vst-au-builds-fail-after-upgrading-to-xcode-15/57936/3) suggested building Projucer from source on the `develop` branch, which I did, and which avoided the errors so it was possible to build successfully.

But now when I start a new project, I get a message: "The path to your JUCE folder is incorrect".

I checked the path, and it is is correct for my machine (`~/JUCE`, which is where then now cloned JUCE repo is).

I chose "Ignore" and everything seems to work as normal.

### What is the expected behaviour?

When creating a new project in Projucer, if the path to JUCE is correct (*including the cloned repo of JUCE*), the message "The path to your JUCE folder is incorrect" should not appear.

### Operating systems

macOS

### What versions of the operating systems?

macOS Somona 14.0

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drkvogel** [comment]
I saw someone else had this issue when running JUCE and Projucer from a cloned repo: [Why am I seeing: The path to your JUCE folder is incorrect?](https://forum.juce.com/t/why-am-i-seeing-the-path-to-your-juce-folder-is-incorrect/45238/3)

So that makes me wonder if, when Projucer is creating a new project, it checks not only that the path to JUCE exists, but does a sanity check of what's inside the JUCE folder - and perhaps this check does not expect files that are in the JUCE repo.

**Comment by tpoole** [comment]
I'm unable to reproduce this problem. Are you 100% certain that you are using a Projucer compiled from the contents of the JUCE directory?

The following works as expected for me:

    cd ~
    git clone https://github.com/juce-framework/JUCE.git
    cd JUCE
    git checkout --track origin/develop
    open extras/Projucer/Builds/MacOSX/Projucer.xcodeproj

Then compile and run the Projucer.

 - Create a new project
 - Save it on the Desktop (allowing access permission to Xcode if required)
 - Open the Project in Xcode from the button in the Projucer exporter

Please reopen this issue if this procedure doesn't work for you.

**Comment by drkvogel** [comment]
I tried the steps as describe and couldn't recreate it either.
