### ISSUE TITLE
[Bug]: [LV2] dsp.ttl has wrong comma in scalePoint since 3451d97

### ISSUE THREAD

**Issue by KottV** [juce-framework/JUCE#1285]
### Detailed steps on how to reproduce the bug

get JUCE with https://github.com/juce-framework/JUCE/commit/3451d97277c4eeca16e2bea5dd0fd36d51e410a4

compile LV2 plugin with `scale point` parameters
try to load in LV2-capable host or validate with lv2lint

dsp.ttl has bunch of errors, due wrong commas in fields:

old behaviour:

```
plug:m_uPolyMode
        a lv2:Parameter ;
        rdfs:label "Poly mode: Mono mode - one note at a time, Poly4 mode - four notes at at timePoly16 mode - onemax. 16 notes at at time" ;
        rdfs:range atom:Float ;
        lv2:default 2 ;
        lv2:minimum 0 ;
        lv2:maximum 2    ;
        lv2:portProperty lv2:enumeration ;
        lv2:scalePoint [
                rdfs:label "Mono" ;
                rdf:value 0 ;
        ], [
                rdfs:label "Poly4" ;
                rdf:value 0.5 ;
        ], [
                rdfs:label "Poly16" ;
                rdf:value 1 ;
        ] .
```

new:
```
plug:m_uPolyMode
        a lv2:Parameter ;
        rdfs:label "Poly mode: Mono mode - one note at a time, Poly4 mode - four notes at at timePoly16 mode - onemax. 16 notes at at time" ;
        rdfs:range atom:Float ;
        lv2:default 2 ;
        lv2:minimum 0 ;
        lv2:maximum 2    ;
        lv2:portProperty lv2:enumeration ;
        lv2:scalePoint , [
                rdfs:label "Mono" ;
                rdf:value 0 ;
        ], [
                rdfs:label "Poly4" ;
                rdf:value 1 ;
        ], [
                rdfs:label "Poly16" ;
                rdf:value 2 ;
        ] .
```

### What is the expected behaviour?

working LV2 plugin

### Operating systems

Linux

### What versions of the operating systems?

openSUSE Tumbleweed

### Architectures

x86_64

### Plug-in formats (if applicable)

LV2

### Plug-in host applications (DAWs) (if applicable)

any LV2 capable

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, that should be fixed here: https://github.com/juce-framework/JUCE/commit/1eed07528e9b5b6fc414e5e8aced6dfbe8ce6d25
