### ISSUE TITLE
[Bug]: iOS app crashes when input channel count is set to 0

### ISSUE THREAD

**Issue by aardvarkk** [juce-framework/JUCE#1294]
### Detailed steps on how to reproduce the bug

- Build a new Audio Application
- In MainComponent, use `setAudioChannels (0, 2);`
- Run on iOS device
- App crashes when setting audio category with error -50

I will submit a PR with a fix.

### What is the expected behaviour?

- App should not crash

### Operating systems

iOS

### What versions of the operating systems?

16.6.1

### Architectures

ARM, 64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Thank you for reporting.

Fixed here: https://github.com/juce-framework/JUCE/pull/1295#issuecomment-1780644417
