### ISSUE TITLE
[Bug]: Mac AudioDeviceSelectorComponent input/output selector problem after recent commit 

### ISSUE THREAD

**Issue by essej** [juce-framework/JUCE#1300]
### Detailed steps on how to reproduce the bug

After the commit https://github.com/juce-framework/JUCE/commit/3540152d717c22e7382e5a9acce65e2aa1bcdf86 , the output selector combobox in AudioDeviceSelectorComponent cannot distinguish the actual current output device when the selected input device is one where there is also a matching named output device on the system (because the CoreAudioIODeviceType::getIndexOfDevice() does not properly distinguish input vs output when dealing with AudioIODeviceCombiner).

The result is that selecting the output device isn't reflected in the combobox correctly, instead always showing the value matching the index of the selected input device, regardless of what the actual selected output is.

This can be reproduced while a USB audio device is attached that has matching names as inputs and outputs.

### What is the expected behaviour?

That the output device combobox always correctly shows the current selected output device.

The following modification of `CoreAudioIODeviceType::getIndexOfDevice()` in `juce_CoreAudio_mac.cpp` fixes the issue here:
```
    int getIndexOfDevice (AudioIODevice* device, bool asInput) const override
    {
        jassert (hasScanned); // need to call scanForDevices() before doing this

        if (auto* d = dynamic_cast<CoreAudioIODevice*> (device))
            return d->getIndexOfDevice (asInput);

        if (auto* d = dynamic_cast<AudioIODeviceCombiner*> (device))
            for (auto* dev : d->getDeviceWrappers()) {
                if (dev->isInput() != asInput) continue; // THIS IS THE FIX <-------
                if (const auto index = dev->getIndexOfDevice (asInput); index >= 0)
                    return index;
            }

        return -1;
    }
```

### Operating systems

macOS

### What versions of the operating systems?

13.6

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Anthony-Nicholls** [comment]
@essej thanks fro reporting, I've got a fix for this incoming.

**Comment by Anthony-Nicholls** [comment]
Sorry for the wait on this we were having some issues with CI last week that was stopped commits from being pushed to develop. This should now be addressed on develop in [this](https://github.com/juce-framework/JUCE/commit/e8d221ccb363fd7ae26fe47c141f768cef6b3ddb) commit, let me know if you experience any more issues.
