### ISSUE TITLE
[Bug]: juceNotificationToNSUserNotification assertion failure on call to varObjectToNSDictionary

### ISSUE THREAD

**Issue by danra** [juce-framework/JUCE#1302]
### Detailed steps on how to reproduce the bug

Regression since 42ab5404c8f47c398d5aa2b619a7328de53b688f.
`PushNotificationsDelegateDetailsOsx::juceNotificationToNSUserNotification` unconditionally calls `varObjectToNSDictionary (n.properties)`, but `n.properties` is documented to be optional and indeed we witnessed it to be `isVoid()`, causing the new assertion `jassert (varToParse.isObject())` at the start of `varObjectToNSDictionary` to fail.

### What is the expected behaviour?

No assertion

Either widen `varObjectToNSDictionary`'s contract to allow `isVoid()`, or test for `isVoid()` in `juceNotificationToNSUserNotification` before calling `varObjectToNSDictionary`

### Operating systems

macOS

### What versions of the operating systems?

-

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Anthony-Nicholls** [comment]
Thanks for reporting @danra we had another report about this too, a fix is working it's way through CI now.
