### ISSUE TITLE
[Bug]: Input method not working properly in Win10/Win11 with juce::TextEditor

### ISSUE THREAD

**Issue by FangCunWuChang** [juce-framework/JUCE#1318]
### Detailed steps on how to reproduce the bug

- Input method word alternative box not displaying on Win11.  
- Input method word alternative box not displaying in correct position on Win10.  

### What is the expected behaviour?

- Input method word alternative box not displaying on Win11.  
- Input method word alternative box not displaying in correct position on Win10.  

**I've run tests with DemoRunner on three versions of the OS and all of these tests have this problem.**  
Word alternative boxes are not displayed on these versions:  
- Microsoft Windows [Version 10.0.22621.2715]  
- Microsoft Windows [Version 10.0.22631.2861]  

The word alternative box is displayed in an incorrect position on these versions:  
- Microsoft Windows [Version 10.0.19044.1288]  

### Operating systems

Windows

### What versions of the operating systems?

- Microsoft Windows [Version 10.0.22621.2715]  
- Microsoft Windows [Version 10.0.22631.2861]  
- Microsoft Windows [Version 10.0.19044.1288]  

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, these issues are fixed here:
https://github.com/juce-framework/JUCE/commit/cfee7cfc9388c69b881c96f1f01abf13dc35ec72
https://github.com/juce-framework/JUCE/commit/038b0d6c9ee652437cae3cbc0aa08f295ca30b1b
