### ISSUE TITLE
[Bug]: Program freezes when clicking note B8 in MPEDemo, but DemoRunner is fine

### ISSUE THREAD

**Issue by kweiwen** [juce-framework/JUCE#1369]
### Detailed steps on how to reproduce the bug

Steps to Reproduce:

1. Open MPEDemo.jucer.
2. Compile the source code.
3. Run the application.
4. Interact with the notes sequentially from low to high.
5. Observe the behavior for each note.

Additional Information:
This issue does not occur in the DemoRunner.app environment. Following similar steps within DemoRunner.app > Browse Demo > Audio > MPEDemo.h, clicking note B8 behaves as expected without causing a freeze.

### What is the expected behaviour?

-  All notes up to B7 behave as expected.
-  Upon clicking note number B8 (the rightmost one), the program freezes. It appears to register a note number of 128, which exceeds the expected range.

### Operating systems

Windows, macOS

### What versions of the operating systems?

Apple M1, 14.1.1 Xcode, JUCE 7.0.11.
Win 10, Visual Studio 2022, JUCE 7.0.11.

### Architectures

x86_64, ARM

### Plug-in formats (if applicable)

Standalone

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting, this issue is fixed here: https://github.com/juce-framework/JUCE/commit/34adc504726c8dd10fae8ef8874e0ab5a061fb7e
