### ISSUE TITLE
Add LICENSE-GPL file to repostiory

### ISSUE THREAD

**Issue by blacklightpy** [juce-framework/JUCE#1373]
### Detailed steps on how to reproduce the bug

Clone/Download the repository.

Cloned repository doesn't have accompanying GPL license clause, only a non-free EULA.

### What is the expected behaviour?

Either an explicit GPL license is provided by the project or the EULA clearly defines the scope of GPL instead of forcing anyone who uses the project to submit the rest of their lives to GPL.

Currently the EULA says you should distribute 'your programs' under GPL. It doesn't say 'our program' or 'your programs depending on our program'.

### Operating systems

Windows, macOS, Linux, iOS, Android, Other

### What versions of the operating systems?

Alpha to Omega

### Architectures

x86_64, ARM, Other, 64-bit, 32-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by blacklightpy** [comment]
This problem was first noted by Void Linux team, who refused to package Helio Sequencer which was dependent on JUCE. I think that's a good problem to solve. My [thread](https://forum.juce.com/t/fix-juce-eulas-dual-licensing-clause/60659) at the forum recieved no response.

**Comment by mohd-akram** [comment]
Was planning to package this for MacPorts but ran into the same issue.

**Comment by tpoole** [comment]
This is addressed in the JUCE 8 release: https://github.com/juce-framework/JUCE/tree/juce8
