### ISSUE TITLE
[Bug]: AudioFormatReaderSource::getNextAudioBlock() incorrect when looping short files

### ISSUE THREAD

**Issue by jcoalson** [juce-framework/JUCE#1384]
### Detailed steps on how to reproduce the bug

`AudioFormatReaderSource::getNextAudioBlock()` does not properly handle looping when the source file is shorter than the buffer.

The issue was [described on the forum in 2016](https://forum.juce.com/t/short-audio-file-looping-long-buffer-garbage-patch-included/17803) and I wanted to raise it again here since I am running into it. The forum thread includes the patch to fix it.

### What is the expected behaviour?

A short file should loop the same as a long one does.

### Operating systems

Other

### What versions of the operating systems?

All, independent of OS

### Architectures

Other

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by jcoalson** [comment]
BTW I selected "The bug is present on the `develop` branch" when creating the issue.

**Comment by szarvas** [comment]
Thank you for reporting. 5b604e6d3c47c89ccd96a6c1b090a787b58604d4 fixes this issue.
