### ISSUE TITLE
[Bug]: AUResources.r Dependency Link in the Readme leads to a 404 page not found

### ISSUE THREAD

**Issue by mossivy** [juce-framework/JUCE#1387]
### Detailed steps on how to reproduce the bug

Just seems like an old link that didn't get taken away. 
Listed under JUCE Framework Dependencies
https://github.com/juce-framework/JUCE/blob/master/modules/juce_audio_plugin_client/AUResources.r
<img width="621" alt="Screenshot 2024-06-05 at 4 50 31 PM" src="https://github.com/juce-framework/JUCE/assets/54687955/5f345e09-1ec7-4e22-a837-ed2b771069d2">

### What is the expected behaviour?

Remove broken link or add a page

### Operating systems

macOS

### What versions of the operating systems?

N/A

### Architectures

ARM

### Stacktrace

```shell
n/a
```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting. On the JUCE 8 branch, the dependency info has moved into LICENSE.md, and the old link to AUResources.r has been removed. This issue will be resolved when JUCE 8 is merged to master. I'm marking this issue as closed because there's a fix on the way.
