### ISSUE TITLE
[Bug]: (JUCE 8) WebSliderParameterAttachment returns INT_MAX for numSteps 

### ISSUE THREAD

**Issue by caenopy** [juce-framework/JUCE#1390]
### Detailed steps on how to reproduce the bug

Build the WebViewPluginDemo in the JUCE 8 preview and look at

- In the js frontend: `properties.numSteps` in `JuceSlider()`
- In the backend: anywhere `getNumSteps()` is called, like in `juce_ParameterAttachments.cpp` here:

```
void WebSliderParameterAttachment::sendInitialUpdate()
{
    const auto range = parameter.getNormalisableRange();
    DynamicObject::Ptr object { new DynamicObject };
    object->setProperty (detail::WebSliderRelayEvents::Event::eventTypeKey, "propertiesChanged");
    object->setProperty ("start", range.start);
    object->setProperty ("end", range.end);
    object->setProperty ("skew", range.skew);
    object->setProperty ("name", parameter.getName (100));
    object->setProperty ("label", parameter.getLabel());
    object->setProperty ("numSteps", parameter.getNumSteps());
    object->setProperty ("interval", range.interval);
    sliderState.emitEvent (object.get());
    attachment.sendInitialUpdate();
}
```

### What is the expected behaviour?

`getNumSteps()` should return something like `((range.end - range.start) / range.interval) + 1).`

### Operating systems

macOS

### What versions of the operating systems?

Ventura 13.3

### Architectures

64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by szarvas** [comment]
Thank you for reporting the issue.

A fix is now available on the `develop` branch d2f3e920f7335e6daa70251fbc453c77137f01f9.
