### ISSUE TITLE
[Bug]: JUCE 8: Subpaths Behaving Incorrectly

### ISSUE THREAD

**Issue by BOBONA** [juce-framework/JUCE#1398]
### Detailed steps on how to reproduce the bug

I apologize if this has already been patched in the develop branch, but I couldn't find any closed path related issues.

In any component, try the following code out:
```C
juce::Path path;
path.startNewSubPath(0, 0);
path.lineTo(getWidth() / 2.f, getHeight() / 2.f);
path.addEllipse(getWidth() / 2.f, getHeight() / 2.f, 5, 5);
path.lineTo(getWidth(), getHeight());
g.strokePath(path, juce::PathStrokeType(1.f));
```

addEllipse specifies that existing subpaths should not be closed. In JUCE 7, this snippet behaved as expected: It drew a line crossing the center with a circle in the middle. In JUCE 8, the path stops after addEllipse is called. 

![image](https://github.com/juce-framework/JUCE/assets/25057945/3c8bda60-a604-44a0-a230-72b018508ce9)

I might be misunderstanding how subpaths are supposed to behave and this is not a glitch, but the behavior before was more intuitive. 

### What is the expected behaviour?

^

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

x86_64, 64-bit

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for reporting. I can repro the issue and there's a fix on the way. I'll update here once the fix is public.

**Comment by reuk** [comment]
Thanks again. The fix for this issue is now available here: https://github.com/juce-framework/JUCE/commit/7bb71cc1ba4275ac86a744fd084706c39b393a9e
