### ISSUE TITLE
VST3 Samplitude X2/X3 black screen

### ISSUE THREAD

**Issue by talaviram** [juce-framework/JUCE#140]
Steps to reproduce:
  1) build juce demo plugin as VST3
  2) open samplitude X2 or X3 (x64)
  3) make sure VST plug-ins show up correctly.
  4) insert the JuceDemoPlugin.
  5) right-click it few times.
  Result:
  - Eventually you get a black view instead of drawing the view.

BEFORE:
![image](https://cloud.githubusercontent.com/assets/6911158/21096693/9e6b8964-c069-11e6-9cf6-e1c3daf84d0c.png)

AFTER: (where something goes wrong)
![image](https://cloud.githubusercontent.com/assets/6911158/21096769/e1c21250-c069-11e6-8b18-b00aa8ce0b1b.png)

  Insights:
  - There is no destruction/constructing of AudioProcessorEditor during those redraws.
  - This does NOT happen with VST2 plug-ins.
  - This is NOT OpenGL related*.
  - It worked as expected with Voxengo SPAN v3.0 under VST3.
  - It's for a while now (I've tested older JUCE commits) but yet to bisect it if it got broken (or was there since the beginning). 
  - Happens with latest head.

**Comment by JimiHFord** [comment]
I'm curious, is this still happening?

**Comment by talaviram** [comment]
Yes, this is STILL happening.
For making sure this isn't fixed I've used latest develop branch (tip - #8a680bc) with latest VST3 SDK.
I've also built a fresh Projucer and plug-in...
(Reproduced with VST3 x64)

**Comment by JimiHFord** [comment]
Hmm, does this only happen in Samplitude?

Could you let us know what happens when you try using the plugin in the provided **audio plugin host** application? [This tutorial](https://www.juce.com/doc/tutorial_create_projucer_basic_plugin) on the JUCE.com website shows you how to use the provided host app.

Also what are you right-clicking?

**Comment by talaviram** [comment]
@JimiHFord , this is reproducible so I guess it should be addressed by the JUCE team.
I've already provided enough details.

I don't understand what plugin are you talking about and why should I regress this against juce audio plugin host which we know isn't effected (as many others DAWs work as expected).

**Comment by 0joshuaolson1** [comment]
@talaviram talaviram

> juce audio plugin host which we know isn't effected

Have you tried?

> this is reproducible

In $400 software.

**Comment by TheSlowGrowth** [comment]
Thread necro for future reference: 
To my knowledge this was a bug in Samplitude. It was fixed in Samplitude Pro X4 Version 15.4.0.642.

**Comment by talaviram** [comment]
Cannot reproduce no more on `15.4.2.650 (DP3) ` so it seems indeed this was fix.
Also JUCE had many changes (even in the past days) related to HWND/VST3.

Closing.
Thanks @TheSlowGrowth
