### ISSUE TITLE
[Bug]: Possible Typo in Juce Ladder Filter BPF12 coefficients

### ISSUE THREAD

**Issue by jmelas** [juce-framework/JUCE#1408]
### Detailed steps on how to reproduce the bug

```
case Mode::BPF12:   A = {{ SampleType (0), SampleType (0), SampleType (-1), SampleType (1),  SampleType (0) }}; comp = SampleType (0.5);  break;
```

### What is the expected behaviour?

According to Vesa Välimäki paper the coefficients for BPF12 should be

```
case Mode::BPF12:   A = {{ SampleType (0), SampleType (1), SampleType (-1), SampleType (0),  SampleType (0) }}; comp = SampleType (0.5);  break;
```

NB: All other coefficients in A table for the other Modes seem to follow the paper correctly.

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by szarvas** [comment]
Just to be sure, could you please quote the full title of the Valimaki paper you're referring to?

**Comment by jmelas** [comment]
Sure it's "Oscillator and Filter Algorithms for Virtual Analog Synthesis" 2006, page 29!

**Comment by szarvas** [comment]
A fix has been released on `develop`. Thank you for reporting the issue.
https://github.com/juce-framework/JUCE/commit/c1ae3ab7aef8c6876e9ea09cf323531d244946fc

**Comment by jmelas** [comment]
Thank you very much for the fix!
