### ISSUE TITLE
[Bug]: /`juce_Windowing_mac.mm:532:33` CGWindowListCreateImage is obsolete in OSX 15.x

### ISSUE THREAD

**Issue by cwmoriarty** [juce-framework/JUCE#1414]
### Detailed steps on how to reproduce the bug

cmake -B build -DMAC_OS_VERSION_14_0=TRUE -DMAC_OS_X_VERSION_MAX_ALLOWED=MAC_OS_VERSION_14_0

### What is the expected behaviour?

Build would complete. I'm not sure how the weak-linking is supposed to work or how to bypass CGWindowListCreateImage when building.

### Operating systems

macOS

### What versions of the operating systems?

15.0

### Architectures

ARM

### Stacktrace

```shell
~/dev/adlplug/ADLplug-AE/external/JUCE/modules/juce_gui_basics/native/juce_Windowing_mac.mm:532:33:
  error: 'CGWindowListCreateImage' is unavailable: obsoleted in macOS 15.0 -
  Please use ScreenCaptureKit instead.

    532 |         CGImageRef screenShot = CGWindowListCreateImage (CGRectNull,
        |                                 ^
  
  /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGWindow.h:271:33:
  note: 'CGWindowListCreateImage' has been explicitly marked unavailable here

    271 | CG_EXTERN CGImageRef __nullable CGWindowListCreateImage(CGRect screenBounds,
        |
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Anthony-Nicholls** [comment]
I don't think you should need to set `MAC_OS_VERSION_14_0` or `MAC_OS_X_VERSION_MAX_ALLOWED`, what version of Xcode do you have installed? and what deployment target are you using? I assume macOS 15? could you use an older version for example `cmake -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0`?

**Comment by cwmoriarty** [comment]
Yea, this machine is 15.x where they dropped `CGWindowListCreateImage` entirely. It appears in `juce_Windowing.mac.mm` the logic just ignores the warning. Figured I'd raise a bug.


`cmake -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0` is the same result.

I'll find another mac to do this build on.

**Comment by BabelsonAudio** [comment]
I get the same error and also tried cmake -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 but nothing fixed yet.

**Comment by Anthony-Nicholls** [comment]
We are currently working on a fix for this. In the short term I'm not sure why setting the deployment target isn't working for you, but I assume you're using a beta version of Xcode? if so are you able to switch to a stable version of Xcode instead?

**Comment by Anthony-Nicholls** [comment]
Thanks for reporting this should be fixed on the latest tip of develop.

https://github.com/juce-framework/JUCE/commit/b083d3c6d83a24444fe32d81d116d44b67291073
https://github.com/juce-framework/JUCE/commit/cddd43891dbef1431ffda5e631dba9a8401d7976
https://github.com/juce-framework/JUCE/commit/b77249ad52c96ef7293d5ef9518aabb793c5ac92
