### ISSUE TITLE
[Bug]: WebView crashing every few reloads

### ISSUE THREAD

**Issue by BLCK-B** [juce-framework/JUCE#1415]
### Detailed steps on how to reproduce the bug

I learned to set up the WebView2 thanks to Jan Wilczek's [tutorial](https://github.com/JanWilczek/juce-webview-tutorial), and I effectively have identical code.

Clicking "Reset to default state" several times crashes the standalone. In a DAW, reloading the plugin window does the same.
Weirdly, the issue occurs only when these two conditions are met:
- a WebSliderRelay is used in PluginEditor (to receive parameters from frontend)
- project is built with a CMake release flag

So, it works fine without a release flag. Or with a release flag but no relays.
The issue arose in this call:
```
  void evaluateJavascript (const String& script, EvaluationCallback callback)
    {
        platform->evaluateJavascript (script, std::move (callback));
    }
```

![image](https://github.com/user-attachments/assets/7170e1a4-8235-42ae-98e2-7e41f6026a13)

JUCE 8.0.1
compiler: LLVM/bin/clang-cl.exe -G "NMake Makefiles"

### What is the expected behaviour?

Reloading WebView with release flag and WebSliderRelay should not crash.

### Operating systems

Windows

### What versions of the operating systems?

11 (10.0.22635 Build 22635)

### Architectures

x86_64

### Stacktrace

```shell
[Inlined] juce::WebBrowserComponent::Impl::evaluateJavascript(const juce::String &, function<…>) juce_WebBrowserComponent.cpp:464
juce::WebBrowserComponent::Impl::emitEvent(const juce::Identifier &, const juce::var &) juce_WebBrowserComponent.cpp:427
juce::WebSliderParameterAttachment::sendInitialUpdate() juce_ParameterAttachments.cpp:314
juce::WebSliderParameterAttachment::WebSliderParameterAttachment(juce::RangedAudioParameter &, juce::WebSliderRelay &, juce::UndoManager *) juce_ParameterAttachments.cpp:286
MyAudioProcessorEditor::MyAudioProcessorEditor(MyAudioProcessor &) PluginEditor.cpp:110
MyAudioProcessor::createEditor() PluginProcessor.cpp:169
juce::AudioProcessor::createEditorIfNeeded() juce_AudioProcessor.cpp:905
juce::StandaloneFilterWindow::MainContentComponent::MainContentComponent(juce::StandaloneFilterWindow &) juce_StandaloneFilterWindow.h:919
[Inlined] juce::StandaloneFilterWindow::updateContent() juce_StandaloneFilterWindow.h:882
juce::StandaloneFilterWindow::resetToDefaultState() juce_StandaloneFilterWindow.h:839
juce::ModalComponentManager::handleAsyncUpdate() juce_ModalComponentManager.cpp:211
juce::AsyncUpdater::AsyncUpdaterMessage::messageCallback() juce_AsyncUpdater.cpp:46
[Inlined] juce::InternalMessageQueue::dispatchMessage(juce::MessageManager::MessageBase *) juce_Messaging_windows.cpp:203
juce::InternalMessageQueue::dispatchMessages() juce_Messaging_windows.cpp:245
juce::InternalMessageQueue::dispatchNextMessage(bool) juce_Messaging_windows.cpp:130
juce::detail::dispatchNextMessageOnSystemQueue(bool) juce_Messaging_windows.cpp:274
juce::MessageManager::runDispatchLoop() juce_MessageManager.cpp:124
juce::JUCEApplicationBase::main() juce_ApplicationBase.cpp:277
[Inlined] invoke_main() 0x00007ff636448b62
__scrt_common_main_seh() 0x00007ff636448b41
<unknown> 0x00007ffed6ab257d
<unknown> 0x00007ffed7ccaf28
```

### Minimal example

~~[minimalExample.zip]~~
see lower still

### Plug-in formats (if applicable)

VST3, Standalone

### Testing on the `develop` branch

I HAVE tested against the `develop` branch

### Code of Conduct

- [x] I agree to follow the Code of Conduct

**Comment by szarvas** [comment]
The issue I'm seeing here, is that the `WebSliderParameterAttachment` is initialised before the `WebBrowserComponent`.

The `WebSliderParameterAttachment`'s lifetime should be nested inside the lifetime of the `WebBrowserComponent`, so in your case, the order of these class members should be reversed.

This is done correctly in the WebViewPluginDemo, but I can see the same issue exists in the linked tutorial.

We will
- call this requirement out in the documentation
- reach out to Jan to update the tutorial code.

Thank you for the report and the reproduction example.

**Comment by BLCK-B** [comment]
Can confirm the order is:
WebSliderRelay
WebBrowserComponent
WebSliderParameterAttachment
