### ISSUE TITLE
[Bug]: Updating to JUCE 8.0.2 breaks initial loading of OpenGL component 

### ISSUE THREAD

**Issue by leonp-s** [juce-framework/JUCE#1428]
### Detailed steps on how to reproduce the bug

After updating a plugin from JUCE `7.0.6` to `8.0.2`, my OpenGL component does not render until the plugin window is resized.

- No `newOpenGLContextCreated` or `renderOpenGL` calls occur until after resizing the window, at which point everything works as expected.
- The issue does not occur in standalone builds, where everything functions normally.

This issue begins after commit 555b667d228439e36cbcd8f820090c1882ce3d76. Prior to this commit, everything works as expected.

### OpenGL Setup:
```cpp
void ...::SetupOpenGl ()
{
    open_gl_context_.setOpenGLVersionRequired (juce::OpenGLContext::openGL4_1);

    if (auto * peer = getPeer ())
        peer->setCurrentRenderingEngine (0);

    open_gl_context_.setComponentPaintingEnabled (true);
    open_gl_context_.setContinuousRepainting (true);
    open_gl_context_.setRenderer (&renderer_);

    open_gl_context_.attachTo (*this);
}
```

### What is the expected behaviour?

Both `newOpenGLContextCreated` and `renderOpenGL` should be called without requiring a resize.

### Operating systems

macOS

### What versions of the operating systems?

14.6 (23G80)

### Architectures

ARM

### Plug-in formats (if applicable)

VST3, AU

### Plug-in host applications (DAWs) (if applicable)

Reaper, Logic

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
See also: https://forum.juce.com/t/component-isshowing-broken-in-ableton-live/62712/4

**Comment by anjaldoshi** [comment]
@reuk 

Regarding `ComponentPeer::isShowing()`: 

In JUCE 8.0.2, I've encountered a problem with standalone application windows on Linux. They fail to repaint correctly, and also leads to disabled widgets. The issue stems from the `LinuxComponentPeer::isShowing()` method returning an incorrect value. Currently, it uses:

```cpp
return XWindowSystem::getInstance()->isMinimised(windowH);
```

However, it should instead be:

```cpp
return ! XWindowSystem::getInstance()->isMinimised(windowH);
```

This change ensures that the method returns the inverse of `isMinimised()`. After applying this modification, my standalone application's window functioned properly on Linux.

**Comment by Laguna1989** [comment]
Can confirm this issue. It seems the `Standalone` targets are not affected, but VST3 and clap (via https://github.com/free-audio/clap-juce-extensions) show this behavior

**Comment by Laguna1989** [comment]
@reuk I have seen in [this forum post](https://forum.juce.com/t/component-isshowing-broken-in-ableton-live/62712/8) that the change was reverted. :+1: 

Will this be ported back to 8.0.2? Rationale is that 8.0.2 is quite unusable. I can not ship with such a bug in place.
If no backport is planned, can you give an estimation, when 8.0.3 will be released?

**Comment by tpoole** [comment]
We're aiming to get 8.0.3 out in a couple of weeks, but it could be pushed back by some other bug fixes.

Why not use the `develop` branch with the fix already in place?

**Comment by Laguna1989** [comment]
I would like to have a pinned version for my releases, so I can uniquely restore that state, e.g. when a bug report comes in.

However I can just use a pinned commit via the hash, instead of the latest tag. Although a tag is clearly preferred on my side as semantic versioning implies ordering, while commit hashes do not. 😅
