### ISSUE TITLE
[Bug]: JUCE 8 Direct2D standalone app repaint flashing

### ISSUE THREAD

**Issue by SslTomH** [juce-framework/JUCE#1434]
### Detailed steps on how to reproduce the bug

With the new Direct2D renderer for Windows in JUCE 8 (tested with 8.0.2), we are seeing undesirable graphical issues with standalone apps when moving the window around.

The whole GUI seems to repaint from scratch on V-Blank when moving the window this way (which doesn't happen with an OpenGL context). This works okay so long as GUI is fast to render, but for complicated GUIs this can cause jittery movement at best, or the GUI to flash stroboscopically at worse. The latter in particular seems to occur if anything within the GUI is repainting on a timer, be that a visualisation or a meter of some kind.

https://github.com/user-attachments/assets/94f86e74-0375-468f-9be1-d91bb11c1503

This behaviour can be seen to some extent in the DemoRunner, and the Projucer feels laggy to move around as well but does not flash (presumably as nothing is repainting itself between VBlanks). To make the flashing more obvious, it helps to go to the Settings tab and back to the demo before moving the window.

https://github.com/user-attachments/assets/59f83eac-ef4d-4d07-86d8-25d43d055c25

This behaviour is worse in debug builds (as expected), though can be seen in release builds.

Plugin GUIs do not seem to suffer from the same issue, presumably because their window handles are managed differently by their hosts. Using a different renderer (software or OpenGL) also does not exhibit the same problem.

Obviously, we cannot move to JUCE 8 until this is resolved.

System specs used for the videos above (though all systems we've tried exhibit the same issue depending on performance):
```
Windows 11,
Intel Core i7 13700k,
Integrated Intel UHD graphics,
32GB RAM
Display: 3840x2160 at 150% scaling factor
```

### What is the expected behaviour?

The window should drag without fully repainting, or at least move without flashing as with the other rendering contexts (software, or with a global OpenGL context).

### Operating systems

Windows

### What versions of the operating systems?

Tested on Windows 11.

### Architectures

x86_64

### Plug-in formats (if applicable)

Standalone

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by SslTomH** [comment]
I've noticed the flashing does **not** occur if I grab the title bar of a maximised window and move it once it pops out. If I then let go and then drag it again, starts flashing. Definitely something weird going on.

**Comment by SslTomH** [comment]
Hi @reuk, I can confirm that that fix stops the flashing and fixes the performance regression, thank you for investigating!

Re my follow up comment, with the fix included it seems that grabbing a maximised window's title bar and moving it around is still slow (jittery), until I let go and drag it again, at which point it is very smooth. I haven't tried this with all of the new develop changes though, so please let me know if you can see the same thing. It's not as severe an issue of course.

**Comment by reuk** [comment]
I suspect what's happening is that when the maximised window is dragged, this begins a resize event, which then doesn't end until the mouse is released. During a resize, we repaint the window continuously, which is probably why the performance is temporarily degraded.

I'll have a think about whether we can improve performance in this situation.

**Comment by SslTomH** [comment]
With the latest develop (14/10/24) I appear to be seeing what looks like this issue again.

**Comment by reuk** [comment]
> With the latest develop (14/10/24) I appear to be seeing what looks like this issue again.

- There are a few issues discussed in this thread. Please can you clarify which issue you're seeing?
- Are you definitely using the very latest develop? We pushed a change in this area earlier today.

For me, I haven't been able to force any flashing when resizing or moving the DemoRunner window while the GraphicsDemo is running.

**Comment by SslTomH** [comment]
Ah, false alarm, had the wrong branch downloaded for some reason. I'd specifically wanted to try today's change, I must have used the wrong browser tab. All seems well, was just the master that still has the issue (as expected).
