### ISSUE TITLE
[Bug]: Standalone Direct2D GUI does not repaint after locking and unlocking the PC

### ISSUE THREAD

**Issue by SslTomH** [juce-framework/JUCE#1435]
### Detailed steps on how to reproduce the bug

Another standalone app Direct2D issue I'm afraid:

1. Open Standalone JUCE 8 GUI app on Windows.
2. Lock the PC (win + L).
3. Unlock the PC.
4. The GUI is black, except for any components that have repainted themselves.
5. Mousing over components that repaint or forcing a repaint by adjusting the window fixes things.

![image](https://github.com/user-attachments/assets/6a11cc47-0779-494b-ad77-2134936b1859)

There may be other ways of getting the app into a similar state, like leaving it in the background for a while. The above steps are 100% repeatable in JUCE 8.0.2. Unsure if this only affects standalone apps, or whether there are some DAWs where plugin GUIs could be affected too.

### What is the expected behaviour?

The JUCE app should not un-paint when left alone, or should repaint itself somehow when appropriate.

### Operating systems

Windows

### What versions of the operating systems?

Windows 11

### Architectures

x86_64

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
> The above steps are 100% repeatable in JUCE 8.0.2.

I've tried this on a couple of machines, one laptop and one desktop machine over remote desktop. I'm not able to trigger the behaviour when testing with the DemoRunner with 8.0.2.

- Do you see the same behaviour in any of the JUCE examples built from the develop branch?
- Does the issue appear immediately after locking the screen, or do you need to wait for the screen to turn off or some other event before the drawing becomes glitchy?
- Is the issue present on other machines?
- Are you using setBufferedToImage anywhere in your application?
- Is your UI mostly made up pre-rendered Images, or are you rendering everything from scratch using Graphics primitives?

**Comment by SslTomH** [comment]
I'm not waiting very long between locking and unlocking Windows, a couple of seconds on average perhaps.

I can see the problem with the DemoRunner and Projucer in 8.0.2, though not quite as reliably. I tried a couple of different demo pages until I got one that did this (in this case, the fonts demo did it):

![image](https://github.com/user-attachments/assets/0bdb7ad7-8eba-43f0-92aa-8fcde65ecc32)

On the develop branch, a similar thing happened first try:

![image](https://github.com/user-attachments/assets/126d11f2-1984-44e1-87f6-e1143e919d91)

Other demos exhibit the issue as well, though it might require some GUI interaction to happen first. Hard to say as it does sometimes get in a state where the issue no longer happens until I restart the app.

As for other machines, I'm trying to get the issue to occur on a different but very similar machine (i7 13700 vs i7 13700k) and have yet to have luck. Will be trying more machines tomorrow hopefully.

**Comment by SslTomH** [comment]
Update, I have managed to repro this issue on another PC (laptop this time) here with the develop DemoRunner. Only affects Direct2D renderer. Will keep investigating to see if there are any common factors that could affect both of these machines.

**Comment by SslTomH** [comment]
Have seen two systems that have the problem so far, but have also seen three that do not exhibit it. Not been able to identify a culprit yet. Doesn't appear to be related to graphics drivers, monitor configuration or other software.

**Comment by reuk** [comment]
In testing on a Windows 10 desktop PC with a GeForce GT 1030, I managed to reproduce the problem in the DemoRunner.

We've pushed some changes in this area: https://github.com/juce-framework/JUCE/commit/c57041e5bc3057d901eed34b8d412f5053037ea1

The changes were intended to fix another issue where glitches were very occasionally produced when resizing the window. However, in testing, the change also appears to resolve the lock/unlock issue on my Windows 10 computer.

Please could you try updating and let us know whether the problem is resolved for you? Thanks!

**Comment by SslTomH** [comment]
Hi @reuk, I'm happy to confirm that I can no longer repro the lock issue with the latest develop code.

However, I've noticed I often hit a jassert in juce_Direct2DHwndContext_windows.cpp when shrinking the size of the window quickly:
![image](https://github.com/user-attachments/assets/55981514-f0a9-4773-90a2-2887511b431a)

When resizing, it looks like the right and lower edges of the window show a white square the size of the initial window hiding behind the GUI, which gets replaced with black as it gets resized over. Something swap buffer related perhaps?

https://github.com/user-attachments/assets/3732b2a4-68b7-4d93-8562-e945f48f52aa

Without debugging attached, we saw a glitch one time when a desktop notification popped up while resizing the DemoRunner, where the GUI briefly didn't paint and showed a portion of the black and white buffer uncovered.

It's develop code of course, so I'm not going to get too worried about this for now, it's already much improved. I look forward to seeing the final result!

**Comment by reuk** [comment]
> However, I've noticed I often hit a jassert in juce_Direct2DHwndContext_windows.cpp when shrinking the size of the window quickly:

Thanks for bringing this to our attention. A fix has been published: https://github.com/juce-framework/JUCE/commit/d22d287c6fe4a03c64290795c01fc908b883b5fd

I wasn't able to repro the issue with desktop notification windows. I'm happy to take another look if you can reproduce the issue consistently with the newest fixes applied.

**Comment by SslTomH** [comment]
> > However, I've noticed I often hit a jassert in juce_Direct2DHwndContext_windows.cpp when shrinking the size of the window quickly:
> 
> Thanks for bringing this to our attention. A fix has been published: [d22d287](https://github.com/juce-framework/JUCE/commit/d22d287c6fe4a03c64290795c01fc908b883b5fd)
> 
> I wasn't able to repro the issue with desktop notification windows. I'm happy to take another look if you can reproduce the issue consistently with the newest fixes applied.

No more jasserts, thank you for investigating. Looking forward to 8.0.3!
