### ISSUE TITLE
[Bug]: JUCE does not find gtk headers on arch linux

### ISSUE THREAD

**Issue by sainteckes** [juce-framework/JUCE#1438]
### Detailed steps on how to reproduce the bug

as soon as I integrate JUCE_WEB_BROWSER=1, juce can't be build anymore because it does not find the gtk headers.
Tested with the current JUCE version 8.0.2.

```bash
/.../build/_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.cpp:127:11: fatal error: gtk/gtk.h: No such file or directory
  127 |  #include <gtk/gtk.h>
      |           ^~~~~~~~~~~
```

I installed most linux dependencies:

```bash
sudo pacman -S alsa-lib ladspa curl freetype2 fontconfig libx11 libxcomposite libxcursor libxext libxinerama libxrandr libxrender webkit2gtk mesa
```
      

### What is the expected behaviour?

It should build normally and find my installed gtk 2.0, 3.0 or 4.0.

### Operating systems

Linux

### What versions of the operating systems?

Arch Linux up to date

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by sainteckes** [comment]
Is this connected to #1377 as on my arch there is webkit2gtk-4.1 installed and no 4.0?

**Comment by sainteckes** [comment]
I could make it work now by adding this to my cmake file:

```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK3 REQUIRED gtk+-3.0)
pkg_check_modules(WEBKIT2GTK REQUIRED webkit2gtk-4.1)

include_directories(${GTK3_INCLUDE_DIRS} ${WEBKIT2GTK_INCLUDE_DIRS})
```

But can this be fixed in the juce cmake files, so I don't have to add this again to my cmake files?

**Comment by KottV** [comment]
gtk should picked up by cmake automatically:
```
-- Checking for modules 'webkit2gtk-4.1;gtk+-x11-3.0'
--   Found webkit2gtk-4.1, version 2.44.4
--   Found gtk+-x11-3.0, version 3.24.43
```

**Comment by sainteckes** [comment]
This output was there in the cmake configure step, the headers were not found anyways...

**Comment by reuk** [comment]
This behaviour is documented in `docs/CMake API.md`. If you set the `JUCE_WEB_BROWSER=1` preprocessor definition, you must also pass `NEEDS_WEB_BROWSER TRUE` to `juce_add_gui_app` or `juce_add_plugin`.
