### ISSUE TITLE
[Bug]: VST3 plugin load is partially broken since 515c42db4be8e6655bdf48297cf83be7b3148655

### ISSUE THREAD

**Issue by KottV** [juce-framework/JUCE#1441]
### Detailed steps on how to reproduce the bug

Build JUCE 8.0.2  AudioPluginHost

Scan VST3 plugins.
Some of plugins bring the error: "The following files appeared to be plugin files, but failed to load correctly"

Problem plugins are: all VST3 version of
 U-he: https://dl.u-he.com/releases/Zebra_Legacy_293_12092_Linux.zip
 Loomer: https://lmr-dply.s3.eu-west-2.amazonaws.com/String/1.17.3/String_x86_64-1.17.3.tar.gz
 
 The issue seems to be introduced with this commit: 515c42db4be8e6655bdf48297cf83be7b3148655

### What is the expected behaviour?

Plugins should be recognized.

### Operating systems

Linux

### What versions of the operating systems?

openSUSE TW

### Architectures

x86_64

### Plug-in formats (if applicable)

VST3

### Plug-in host applications (DAWs) (if applicable)

APH

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks, I can reproduce the problem and there's a fix on the way.

**Comment by reuk** [comment]
The fix is now on the develop branch: https://github.com/juce-framework/JUCE/commit/ca8b5f7483ef0b882f733ee7f9fc2b38d0b127e7
