### ISSUE TITLE
[Bug]: Does JUCE no longer support compiling with MinGW? I'm unable to successfully compile using CMake with MinGW. Is it possible to add support for MinGW?

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [juce-framework/JUCE#1446]
### Detailed steps on how to reproduce the bug

 compile using CMake with MinGW

### What is the expected behaviour?

successfully compile using CMake with MinGW

### Operating systems

Windows

### What versions of the operating systems?

win11

### Architectures

x86_64, 64-bit

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
This isn't a bug - we removed MinGW support in JUCE 8.0.0 as listed in the breaking changes document.

**Comment by Kreijstal** [comment]
Okay, you don't support mingw, now support any open source toolchain on windows would be nice

**Comment by reuk** [comment]
We do, you can build with Clang on Windows. You'll still need an official Windows SDK, though.
