### ISSUE TITLE
[Bug]: Cant build my plugins. Ordinal 345 Not found at the link

### ISSUE THREAD

**Issue by RichardPortelli** [juce-framework/JUCE#1455]
### Detailed steps on how to reproduce the bug

Building my project on Windows 10 with Juce 8.0.3

### What is the expected behaviour?

I have an error at the link Ordinal 345 Not found.
When testing with Juce 7, I dont have the issue.

### Operating systems

Windows

### What versions of the operating systems?

Windows 10.0.19045.5011

### Architectures

64-bit

### Plug-in formats (if applicable)

VST2, VST3, Standalone

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
I've not heard of this error before, and the description doesn't provide any hints as to what could be causing the problem. At what point is the error displayed? During the build, or when trying to run the plugin, or something else? Please provide as much information as possible.

The biggest difference between JUCE 7 and JUCE 8 on Windows is that the default renderer is now Direct2D. This renderer requires more advanced graphics driver support than the old software renderer. Perhaps it's worth checking that your graphics drivers are up-to-date, and that there are no pending Windows updates.

**Comment by reuk** [comment]
The problem ended up being that no manifest was included in the final binary because the "Generate Manifest" option was disabled in the Projucer. Setting the "Generate Manifest" option to enabled resolves the issue.

**Comment by reuk** [comment]
We've removed the "generate manifest" option from the Projucer to avoid situations like this in the future: https://github.com/juce-framework/JUCE/commit/cba00cc71fe05d9cdac8c8dd47a055b1b13869e7
