### ISSUE TITLE
CMake configure fails on JUCE 7.0.12 on macOS Sequoia

### ISSUE THREAD

**Issue by dingari** [juce-framework/JUCE#1457]
### Detailed steps on how to reproduce the bug

Try to configure the `examples/CMake/GuiApp` example on macOS 15 (AppleClang 16)

### What is the expected behaviour?

The cmake configure phase executes correctly.

After updating to macOS 15 and AppleClang 16, `juceaide` no longer builds and the project is unable to complete the configure phase.

The last bad commit: 49ed0f022dd394587abd321a435714647d5cfdd4
The first good commit: 10cf5a98a2dcaca225d8c15e3aa3798e00160749

### Operating systems

macOS

### What versions of the operating systems?

macOS 15

### Architectures

ARM

### Stacktrace

```shell
Output when running `cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug` 

https://gist.github.com/dingari/6d41ab7c8f9773022a360b741c107fbe
```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
JUCE 7 doesn't support AppleClang 16. You'll need to upgrade to JUCE 8.

See this discussion: https://forum.juce.com/t/sequoia-xcode-16-compatibility/62918

**Comment by dingari** [comment]
Oh, thanks! I didn't see that discussion.
