### ISSUE TITLE
[Bug]: UnitTest assumes that File::userApplicationDataDirectory exists

### ISSUE THREAD

**Issue by umlaeute** [juce-framework/JUCE#1465]
### Detailed steps on how to reproduce the bug

- setup a pristine build machine/container (I'm assuming this is a linux environment)
- ensure that `~/.config` does not exist (since the environment is pristine, there is no reason to assume that somebody created it)
- build the `UnitTestRunner` and run it
- notice that this test fails: https://github.com/juce-framework/JUCE/blob/5179f4e720d8406ebd1b5401c86aea8da6cc83c9/modules/juce_core/files/juce_File.cpp#L1083

### What is the expected behaviour?

the test should test the functionality of JUCE, rather than whether my environment matches the expectations.

### Operating systems

Linux

### What versions of the operating systems?

Debian/sid

### Architectures

Other

### Stacktrace

```shell
$ extras/UnitTestRunner/Builds/LinuxMakefile/build/UnitTestRunner --category=Files        
Random seed: 0x84e8a28df96d5cae
-----------------------------------------------------------------
Starting tests in: Files / Reading...
!!! Test 8 failed

FAILED!!  1 test failed, out of a total of 21

-----------------------------------------------------------------
Starting tests in: Files / Writing...
Completed tests in Files / Writing
-----------------------------------------------------------------
Starting tests in: Files / Memory-mapped files...
Completed tests in Files / Memory-mapped files
-----------------------------------------------------------------
Starting tests in: Files / More writing...
Completed tests in Files / More writing
-----------------------------------------------------------------
Starting tests in: FileSearchPath / removeRedundantPaths...
Completed tests in FileSearchPath / removeRedundantPaths

Test failure summary:

Files / Reading: 1 test failure
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tpoole** [comment]
Thank you for reporting. Fixed here: https://github.com/juce-framework/JUCE/commit/ef28243c6408a0d6edaaa50796620ee80e7b3d3a
