### ISSUE TITLE
[Bug]: SortableCell operator< doesn't do anything different for the columnFirst flag

### ISSUE THREAD

**Issue by Dave-Lowndes** [juce-framework/JUCE#1473]
### Detailed steps on how to reproduce the bug

In juce_Grid.cpp, the code inside the if block L708..714 is identical to the block after it L716...719
Currently the if condition and columnFirst flag appear to be redundant, but was the intent maybe that one of the blocks ought to be checking row/column differently?

### What is the expected behaviour?

unknown

### Operating systems

Windows

### What versions of the operating systems?

n/a

### Architectures

x86_64

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thanks for the report. This was indeed causing a subtle bug, but it took a long time to reverse-engineer a test that would demonstrate the issue!

In any case, this should be fixed on the develop branch:

https://github.com/juce-framework/JUCE/commit/b72e43620ccb63a5b39fa6982a92eca2bc189dcc
