### ISSUE TITLE
[Bug]: IME: The input method prompt window cannot be displayed for Chinese Env

### ISSUE THREAD

**Issue by mzong1208** [juce-framework/JUCE#1482]
### Detailed steps on how to reproduce the bug

The input method prompt window cannot be displayed for Chinese Env
![bug](https://github.com/user-attachments/assets/96e673fd-1395-4a87-b6a9-aa4fd8e97942)
)
![bug](https://github.com/user-attachments/assets/b3b3ed5e-52a4-40f4-9436-05c964cdf625)

### What is the expected behaviour?

Display IME promtpt window as SYSTEM

### Operating systems

Windows, macOS

### What versions of the operating systems?

JUCE 7x and 8.x 

### Architectures

x86_64, Arm64/aarch64, Arm64EC (Windows), x86 (Windows, Android), 32 bit Arm (Linux, Android)

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by reuk** [comment]
Thank you for reporting this issue.

So far, I've been able to reproduce the problem on two Windows 11 machines, but it seems to work correctly on two Windows 10 machines that I've tried.

Which version of Windows are you using, 10 or 11?

**Comment by FangCunWuChang** [comment]
Is this(https://github.com/juce-framework/JUCE/issues/1318) the issue you've encountered?  
I’ve attempted some fixes(https://github.com/juce-framework/JUCE/pull/1487) for these problems.

**Comment by mzong1208** [comment]
> Thank you for reporting this issue.
> 
> So far, I've been able to reproduce the problem on two Windows 11 machines, but it seems to work correctly on two Windows 10 machines that I've tried.
> 
> Which version of Windows are you using, 10 or 11?

I use windows 11

**Comment by reuk** [comment]
Thanks for the information. We've now merged a fix here: https://github.com/juce-framework/JUCE/commit/038b0d6c9ee652437cae3cbc0aa08f295ca30b1b

I also observed an issue where the IME window could sometimes appear in the wrong location on scaled/hi-dpi displays. That issue should be fixed here: https://github.com/juce-framework/JUCE/commit/cfee7cfc9388c69b881c96f1f01abf13dc35ec72
