### ISSUE TITLE
 Windows 10 - UWP support

### ISSUE THREAD

**Issue by sseyod** [juce-framework/JUCE#218]
We need support for in JUCE for Windows 10 / UWP.

The business case is pretty simple: we need to be able to deploy our JUCE-based apps through the Windows 10 store.

**Comment by jrlanglois** [comment]
This is pretty complicated I hope you realise?

All of the native Win32 APIs are disallowed on that platform.

**Comment by sseyod** [comment]
I'm sure you're right. That, of course, gives an added benefit to using JUCE for application delivery on Windows 10. So, all the more reason for ROLI to deliver it! It is relatively easy to bind from C++ to UWP APIs in C++/CLI - I've done it myself in a separate project.

**Comment by jrlanglois** [comment]
> It is relatively easy to bind from C++ to UWP APIs in C++/CLI - I've done it myself in a separate project.

Sure, binding is not in question at all!

The complexity is really porting every single native feature and all of the value-added JUCE features (eg: audio plugin hosting, audio plugin development - both of which _may_ not be possible).

For future reference, especially for the Roli devs, here is a list of classic Win32 APIs that are apparently supported: [Win32 and COM APIs for UWP apps](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps).

**Comment by mathieu-b** [comment]
Just an idea (note: I'm *not* a Windows UWP software development expert)

A shortcut (at least for the graphics part) might be to rely on the OpenGL ES renderer, and using angle: https://github.com/Microsoft/angle

Not been there, not done that, just a pointer.

Regards.

**Comment by sseyod** [comment]
Thanks Mathieu. The problem is getting it past Microsoft's review process!

For my own particular purposes, I don't require audio plug-in hosting etc. - I just need an app GUI based on Juce to "pass" the UWP verification - the app happens to generate audio, but I use Juce purely for the cross-platform UI capability; so I'd be perfectly happy with a "GUI only" subset of Juce for builds that target UWP. 

Of course, I understand that other prospective customers have different requirements!

**Comment by sseyod** [comment]
I thought I should provide some more info on this; shame there hasn't been any further update from ROLI!

1) You should first associate your C++ project with the Windows 10 store application id (you first need to have configured a Microsoft Store account to do this, and allocated the appropriate app name etc. on the Microsoft portal)
2) This explains how to add a "Windows Application Packaging Project" to a C++ project - including an app built with Juce - in a solution:
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net
The info here seems to have appeared last August.
Call your "packaging project" (say) "MyAppUWP"
3) You *must* have installed the .net development option from your Visual Studio installer (just the C++ option is not enough... otherwise, you get weird build errors)
4) You *must not* build from a network drive (or you see yet more weird build errors)
5) I've found that native windows message boxes cause the app to hang; use the Juce ones instead

I'm now investigating if Microsoft will approve my projects for the Windows 10 store (or not!)

Pete

**Comment by sseyod** [comment]
And here is the feedback from Microsoft. Looking promising.

===
We tested the app on Windows 10 and Windows 10 S simulation VMs.
It even passed WACK test but wanted to inform you that it failed the Package sanity test for blocked executables. Launching executable files is restricted on Windows 10 S systems. Apps that rely on this capability might not run correctly on Windows 10 S systems. You can identify which of the flagged entries represent a call to launch an executable file that is not part of your app and remove those calls. 

NOTE: If the flagged files are part of your application, you may ignore the following warnings:

FAILED
Blocked executables
Error Found: The blocked executables test has detected the following errors:
File YOURAPP\YOURAPP.exe contains a reference to a "Launch Process" related API shell32.dll!ShellExecuteA
File YOURAPP\YOURAPP.exe contains a reference to a "Launch Process" related API shell32.dll!ShellExecuteW
File YOURAPP.exe contains a blocked executable reference to "csI".
File YOURAPP.exe contains a blocked executable reference to "Cmd".
File YOURAPP.exe contains a blocked executable reference to "ReG".
File YOURAPP.exe contains a blocked executable reference to "CdB".
File YOURAPP.exe contains a blocked executable reference to "dNX".
File YOURAPP.exe contains a blocked executable reference to "\Cmd".
File YOURAPP.exe contains a blocked executable reference to "v\csi".
File YOURAPP.exe contains a blocked executable reference to "bash".
File YOURAPP.exe contains a blocked executable reference to "NTSd".
File YOURAPP.exe contains a blocked executable reference to "\CdB".

As next steps, we will proceed with Runfulltrust permission for this app and keep you updated as the waiver gets applied.
===

**Comment by sseyod** [comment]
And... we've now had two apps approved for the Windows 10 store, using the process outlined above, both written with Juce.

They should be live in a few days!

**Comment by rosesby** [comment]
> This is pretty complicated I hope you realise?
> 
> All of the native Win32 C APIs are disallowed on that platform; you have to migrate everything to C++/Cx (WinRT). This includes everything from file I/O, to input, threads, to even how your update loop works.
> 
> Also, I'm pretty sure dynamic library usage is disallowed, too.

In 2019 With C++/WinRT you don't need to port to C++/CX, because it's implemented as ISO C++17
https://docs.microsoft.com/es-mx/windows/uwp/cpp-and-winrt-apis/

**Comment by sseyod** [comment]
Wow - thanks for the information - I'd not heard of C++/WinRT before, that is tremendous!
