### ISSUE TITLE
Projucer cmdline cannot be run without X11

### ISSUE THREAD

**Issue by umlaeute** [juce-framework/JUCE#422]
Trying to run Projucer (in cmdline mode) on a headless machine (without any display-server) fails.

On Linux/amd64 (distro: Debian/buster) with Projucer from today's `develop` branch (dbb1345583adb5ed01c1344f4e34380d481e0a26) i get:

~~~sh
$ cd JUCE/extras/Projucer/Builds/LinuxMakefile/build
$ ./Projucer -resave ../../../../UnitTestRunner/UnitTestRunner.jucer 
JUCE v5.3.2
No protocol specified
No protocol specified
Failed to connect to the X Server.
$
~~~

Our use-case is continuous-integration, where we build JUCE-projects on every push to our git-repository.
Our git repository follows best-practice, and does not include any generated code, so the only build-files are the `.jucer` projects (no Makefiles, XCode, VS-Projects in the repository), and the actual build-system needs to be generated on-the-fly using Projucer`s `-resave` command.

Now I understand that `Projucer` is mainly an IDE to be used with it's fancy GUI.
However, when doing CI-builds, we must automate everything, and don't have a GUI available.

Since running `Projucer -resave` doesn't actually open up any window, I would have expected that it does not require a full display server.

The simplest way I found for reproducing this (assuming you are working in a running X11-session) is to ssh into the same machine with a *different* account (and of course have X-forwarding disabled):

~~~
$ ssh root@localhost
# ./Projucer -resave ../../../../UnitTestRunner/UnitTestRunner.jucer 
~~~

**Comment by peterrudenko** [comment]
I've faced the same problem when setting up CI, and one possible workaround is to use virtual framebuffer:
`xvfb-run -a bash -c 'command-line-of-yours'`

**Comment by laserbat** [comment]
This is a serious issue and it's really sad to see it being unnoticed by developers. I'm trying to package a JUCE based app for void linux and it's very ugly because of this bug :(

**Comment by McMartin** [comment]
@laserbat If you have a `.jucer` project file, you can use `Jucer2Reprojucer` from [FRUT](https://github.com/McMartin/FRUT) (I'm the author) to convert it to a `CMakeLists.txt` file and then use CMake to build.

**Comment by chevdor** [comment]
I ran into this issue on a recent Ubuntu with X11 / Gnome installed and fully functional.
This is fortunately easy to fix (maybe the info can be added to the doc).

Here is a one-liner:
`echo "export GDK_BACKEND=x11" >> ~/.bashrc && source ~/.bashrc`

Note, this will fix only your current shell. If you have other open shells, you probably want to close and re-open them. After rebooting your system, all shells will be fine however.

After doing that, you will be able to start Projucer from the JUCE folder with `./Projucer` and it should work all fine.

**Comment by kunitoki** [comment]
i have the same issue, the application can't run from bash if it's not under x11, any news if this could be addressed ?

**Comment by kunitoki** [comment]
I tried this and it's working nicely.

```
diff --git a/juce/modules/juce_gui_basics/native/juce_linux_X11.cpp b/juce/modules/juce_gui_basics/native/juce_linux_X11.cpp
index a2ceb67074d2b2b9c8988b2dbdb1f7737d8d8336..82907489ce4fd5222aa6c5219d6c4fc58b070d2f 100644
--- a/juce/modules/juce_gui_basics/native/juce_linux_X11.cpp
+++ b/juce/modules/juce_gui_basics/native/juce_linux_X11.cpp
@@ -149,14 +149,16 @@ XWindowSystem::~XWindowSystem() noexcept
 
 ::Display* XWindowSystem::displayUnref() noexcept
 {
-    jassert (display != nullptr);
-    jassert (displayCount.get() > 0);
-
-    if (--displayCount == 0)
+    if (display)
     {
-        destroyXDisplay();
-        XCloseDisplay (display);
-        display = nullptr;
+        jassert (displayCount.get() > 0);
+
+        if (--displayCount == 0)
+        {
+            destroyXDisplay();
+            XCloseDisplay (display);
+            display = nullptr;
+        }
     }
 
     return display;
@@ -168,7 +170,7 @@ void XWindowSystem::initialiseXDisplay() noexcept
     if (display == nullptr)
     {
         Logger::outputDebugString ("Failed to connect to the X Server.");
-        Process::terminate();
+        return;
     }
 
     // Create a context to store user data associated with Windows we create
@@ -223,11 +225,14 @@ void XWindowSystem::initialiseXDisplay() noexcept
 
 void XWindowSystem::destroyXDisplay() noexcept
 {
-    ScopedXLock xlock (display);
-    XDestroyWindow (display, juce_messageWindowHandle);
-    juce_messageWindowHandle = 0;
-    XSync (display, True);
-    LinuxEventLoop::unregisterFdCallback (XConnectionNumber (display));
+    if (display)
+    {
+        ScopedXLock xlock (display);
+        XDestroyWindow (display, juce_messageWindowHandle);
+        juce_messageWindowHandle = 0;
+        XSync (display, True);
+        LinuxEventLoop::unregisterFdCallback (XConnectionNumber (display));
+    }
 }
 
 JUCE_IMPLEMENT_SINGLETON (XWindowSystem)

```

**Comment by tpoole** [comment]
As of recent versions of JUCE the Projucer should not need an X server to run the command line, although it will need the various X development packages to build.
