### ISSUE TITLE
Cumbersome to checkout a specific version of Oboe

### ISSUE THREAD

**Issue by dturner** [juce-framework/JUCE#437]
JUCE (5.4.1) requires a specific commit of the Oboe library. The SHA of this commit is given in the info box under the Android project settings: 

![image](https://user-images.githubusercontent.com/873212/48431081-bc813700-e768-11e8-8f12-145f20023ccd.png)

Unfortunately there's no way to copy/paste this SHA so that means hunting through the Projucer source code to get this SHA (I couldn't find it in the docs anywhere). For anyone else looking at this it's here: 

    c5c3cc17f78974bf005bf33a2de1a093ac55cc07

Since I'm one of the authors of the Oboe library, is there anything we can do to make this process less arduous for developers. For example: 

- by providing Oboe library binaries
- using a tag for a given version and then having the Projucer show the full git command to clone/checkout that version of Oboe

**Comment by talaviram** [comment]
Why not include Oboe with JUCE? If license permits it this would be like audiounit / vst3 included already with option to set custom path...

Internally in our private tools we use sub-modules which is also simple way to keep Oboe separated. 

If it should be only on Oboe side without commits to JUCE then the following can simplify:
- add a tag to the specific JUCE relavant state.
- update the library README.md to have some tips (including SHA) from Google's side...

**Comment by dturner** [comment]
Oboe is licensed under Apache 2.0. Maybe binaries distributed with JUCE are the way to go - keeps things simple rather than having to use sub-modules or rely on the developer having to check out code.

**Comment by ed95** [comment]
The Oboe source is now included in the JUCE repo on the `juce6` preview branch in commit [719a491](https://github.com/juce-framework/JUCE/commit/719a4917404307073f6de427383886cad0612b14).
