### ISSUE TITLE
[Android/Oboe] oboe::StabilizedCallback should be implemented to avoid glitches by sleeping audio callback

### ISSUE THREAD

**Issue by audiooffler** [juce-framework/JUCE#494]
Running an Android application with an AudioProcessorPlayer produces glitches, even if and especially if AudioDeviceManager::getCpuUsage() shows a low percentage. When switching off the display the amount of glitches increases. As watching /system/bin/audioserver in systrace.py the Thread "AudioOut_D" goes to sleep from time to time.

When using oboe in current JUCE (5.4.3), the oboe::StabalizedCallback is not implemented, as meantioned here: [Android (JUCE) performance issues when NOT touching screen](https://stackoverflow.com/questions/53860502/android-juce-performance-issues-when-not-touching-screen) and here: [Android oboe::StabilizedCallback](https://forum.juce.com/t/android-oboe-stabilizedcallback/31964). The problem was already discussed here: [Audio glitches with simple sine wave android Lenovo p2 but not on sim](https://forum.juce.com/t/audio-glitches-with-simple-sine-wave-android-lenovo-p2-but-not-on-sim/28158/6)
I assume this could be very of help, it should be implemented in juce_audio_devices/native/juce_android_Oboe.cpp

Tested on 2 different armeabi-v7a Android 7 devices (Fairphone 2 and Tablet HuaweiMediaPad M3 Lite10)

**Comment by deltavaudio** [comment]
I think I may have succeeded in getting this to work in JUCE, see thread:

https://forum.juce.com/t/android-oboe-stabilizedcallback/31964/5

**Comment by ed95** [comment]
This has been added to the `juce6` preview branch in commit [6a48f66](https://github.com/juce-framework/JUCE/commit/6a48f66cd4d82d26505697f208d1f60b9501ec9c).
