### ISSUE TITLE
Camera name is hardcoded "default"

### ISSUE THREAD

**Issue by Nizarazo** [juce-framework/JUCE#587]
Hi

I am using macos I see in recently versions of JUCE that Quick Time is deprecated so the implementation of function getAvailableDevices in juce_mac_CameraDevice.mm (which retrieves the camera name) has changed from:

     static StringArray getAvailableDevices()
    {
        StringArray results;
        NSArray* devs = [QTCaptureDevice inputDevicesWithMediaType: QTMediaTypeVideo];

        for (int i = 0; i < (int) [devs count]; ++i)
        {
            QTCaptureDevice* dev = (QTCaptureDevice*) [devs objectAtIndex: i];
            results.add (nsStringToJuce ([dev localizedDisplayName]));
        }

        return results;
    }

to:
   static StringArray getAvailableDevices()
    {
        StringArray results;
        results.add ("default");
        return results;
    }

meaning the camera name is set hard coded as "default"

Are you going to support retrieving real camera name in versions 5.x?
What is the alternative?

Any help is appreciated.
Thanks

**Comment by ed95** [comment]
This has been added to the `juce6` preview branch in commit [94cc9c4](https://github.com/juce-framework/JUCE/commit/94cc9c48a4d6f8f92ed2425f64caf815f824a0db).
