### ISSUE TITLE
Waves VST2 plugins (Codex, Elements, ...) crash the AudioPluginHost while loading

### ISSUE THREAD

**Issue by seb-nektar** [juce-framework/JUCE#612]
Loading a Waves VST2 (e.g. Codex or Elements) plugin crashes JUCE-based plugin hosts. This was already reported in the [JUCE forum](https://forum.juce.com/t/vst-gets-created-twice-in-host-breaks-vst) and a potential fix is described there.

We further debugged the issue and can confirm that opening the plugin two times by `dispatch (Vst2::effOpen, ...` is the problem here.

1.  Looking into the history of juce_VSTPluginFormat.cpp with git blame shows that another "open" of the plugin has been added in [VSTPluginInstance::create()](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L1176) with commit 4fa0516f4068 `Revised multibus API and added support for multibus hosting`.

2. The other call to "open" the plugin in `VSTPluginInstance::initialise()` has been there since the beginning of the git history.

The second call to "open" in `initialise()` is probably not necessary anymore as the `vsteffect` object is now always passed in an "open" state into the constructor in `VSTPluginInstance::create()`.

**Comment by JoshMarler** [comment]
+1, would be great to get an update on this.

**Comment by seb-nektar** [comment]
We have the proposed fix in our internal JUCE branch for some time now and did not discover any regressions. Any reason why that fix cannot be applied to upstream JUCE? From my understanding the second call to `dispatch (Vst2::effOpen, ...` looks like a leftover which was forgotten to be removed when working on commit 4fa0516.

**Comment by reuk** [comment]
I've investigated this a bit, and on Catalina and Big Sur with the latest release of Waves Codex, the very first dispatch of effOpen in `create` causes the plugin to segfault. Commenting out the call in initialise has no effect.

On Windows, I’m able to open Codex with no changes to JUCE.

At the moment, I’m inclined to say that this is a bug in the Mac version of Codex 12. I’d be reluctant to modify JUCE code to accommodate Codex, given that this may in turn break other plugins.

**Comment by seb-nektar** [comment]
Indeed, the problem seems to disappear with Wave plugin versions 11 and above. At the time I wrote the bug report back in 2019  Waves plugins version 10 was used for testing. 

Still I think the double call to effOpen is not necessary and you could consider removing it. Looks like a remainder from merging 4fa0516? Otherwise feel free to close the item.

**Comment by reuk** [comment]
Given that the duplication doesn't seem to be actively harmful, and we know that compatibility with most plugins is very good, I think I'll leave things as they are for now. If I were to remove one of the calls, I would want to test this thoroughly with a variety of plugins and platforms, and I think that time would be better spent fixing other issues.

Thanks for reporting this issue, and for your patience.
