### ISSUE TITLE
transform matrix is applied irregularly in JUCE on some SVG elements 

### ISSUE THREAD

**Issue by ramagottfried** [juce-framework/JUCE#688]
JUCE's handing of SVG transform appears to be irregular for different graphic types.

Testing on MacOS with JUCE develop branch commit 18df1b09379f1fb9ba997926b860f92b9515fc64 using the DemoRunner GraphicsDemo example (with a minor edit, pasted below).

Viewing the basic example below, please notice:
* the SVG `<text>` and `<rect>` should have exactly the same transform applied. Viewing in a browser, the text appears perfectly lined up inside the rotated rectangle, in the JUCE DemoRunner both objects appear, but the text is located far above the rectangle (note: you may need to expand the DemoRunner window quite a bit to see the text element).

Test SVG file:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="600px" height="200px" viewBox="0 0 600 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">

<text x="68" y="56" font-size="18" 
     transform="matrix(0.000796,0.999784,-0.999784,0.000796,140.417121,-41.539713)">TEST</text>

<rect x="67" y="42" width="48" height="15" 
     transform="matrix(0.000796,0.999784,-0.999784,0.000796,140.417121,-41.539713)" stroke="black" stroke-width="1" fill="none" />

</svg>
```
Minor edit to the `createSVGDrawable` function in the GraphicsDemo.h to test:

```
void createSVGDrawable()
    {
        lastSVGLoadTime = Time::getCurrentTime();

        File testFile( ... insert path to the above SVG file here... );
        svgDrawable = Drawable::createFromImageFile(testFile);
        if (svgDrawable != nullptr)
        {
            if (auto comp = dynamic_cast<DrawableComposite*> (svgDrawable.get()))
                comp->setBoundingBox ({ -100.0f, -100.0f, 200.0f, 200.0f });
        }
    }
```

**Comment by abj12798** [comment]
Please assign this to me

**Comment by szarvas** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/a99422efeef09ec07c4f7a67d07da8c078d55cd6

Thank you for reporting.
