### ISSUE TITLE
BinaryData::getNamedResourceOriginalFilename compares pointers not strings

### ISSUE THREAD

**Issue by kunitoki** [juce-framework/JUCE#691]
The generated function `BinaryData::getNamedResourceOriginalFilename` is not working correctly as it compares the `const char*` pointers instead of doing a string comparison. If you are not passing in a string literal but you pass in a runtime computed string it's failing badly.

**Comment by tpoole** [comment]
This has been fixed on the `develop` branch: https://github.com/juce-framework/JUCE/commit/d5311698e907f637ea3b2bc8a60aa427f2fe4279

Thank you for reporting.
