### ISSUE TITLE
Minor - juce6 cmake with Linux and NEEDS_(CURL|WEB_BROWSER)

### ISSUE THREAD

**Issue by baconpaul** [juce-framework/JUCE#704]
Hi

Juce6 is amazing. Thank you. And sorry to open this as an issue. For some reason my roli id doesn't let the forum see me as logged in so I can't post this on the forum.

I have a teensy juce6 app I am using and I noticed an inconsistency with linux builds and cmake. I'm using juce6 branch as of c419bc516d7 on a newly installed ubuntu 20.04 LTS

If I set

```
    NEEDS_CURL                      FALSE
    NEEDS_WEB_BROWSER               FALSE
```

in my `juce_add_gui_app` then do `cmake --build build --config Release` I get an error

```
[ 57%] Building CXX object CMakeFiles/HarmonyTrainer.dir/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp.o
/home/paul/dev/harmony-trainer/JUCE/modules/juce_gui_extra/juce_gui_extra.cpp:107:11: fatal error: gtk/gtk.h: No such file or directory
  107 |  #include <gtk/gtk.h>
      |           ^~~~~~~~~~~
compilation terminated.
```

if I set `NEEDS_WEB_BROWSER` to `TRUE` and do the same, I get that juce_gui_extra builds but I fail to link because of a lack of CURL

When I set them both to TRUE everything works.  Which is great! Because (and have I mentioned this?) juce6 is amazing.

I think this is because at line 87 of JUCEUtils.cmake you add gtk+-x11-3.0 to JUCE_BROWSER_LINUX_DEPS so it is only there if browser is on.

But in `JUCE/modules/juce_gui_extra/juice_gui_extra.h` you define JUCE_WEB_BROWSER to 1 if it is not otherwise defined at line 57. 

So if I put `JUCE_WEB_BROWSER=0` into my target_compile_defines then I build with FALSE for NEEDS_WEB_BROWSER, although don't link because of curl. And if I also add JUCE_USE_CURL=0 then I can build and link. But I think your cmake files could do that automatically.

You set this up in JUCEUtils.cmake so adding an else there fixes the problem. Here's a diff that allowed me to build with the NEEDS_ variables on and no additional modification

```
diff --git a/extras/Build/CMake/JUCEUtils.cmake b/extras/Build/CMake/JUCEUtils.cmake
index f7de9ca15..c3b3988dc 100644
--- a/extras/Build/CMake/JUCEUtils.cmake
+++ b/extras/Build/CMake/JUCEUtils.cmake
@@ -555,12 +555,16 @@ function(_juce_link_optional_libraries target)
 
         if(needs_curl)
             target_link_libraries(${target} PRIVATE PkgConfig::JUCE_CURL_LINUX_DEPS)
+        else()
+            target_compile_definitions(${target} PRIVATE JUCE_USE_CURL=0)
         endif()
 
         get_target_property(needs_browser ${target} JUCE_NEEDS_WEB_BROWSER)
 
         if(needs_browser)
             target_link_libraries(${target} PRIVATE PkgConfig::JUCE_BROWSER_LINUX_DEPS)
+        else()
+            target_compile_definitions(${target} PRIVATE JUCE_WEB_BROWSER=0)
         endif()
     elseif(APPLE)
         get_target_property(needs_storekit ${target} JUCE_NEEDS_STORE_KIT)
```

Hope that helps!

**Comment by baconpaul** [comment]
Oh and I understand that you generally don't work through pull requests from newcomers to the platform which is why I pasted a diff; but if you would rather I submit this as a PR that's fine with me. Of course this could be totally the wrong fix too! But thanks for your time in any case.

**Comment by tobanteAudio** [comment]
You need to set:

```sh
target_compile_definitions(YourTraget
        JUCE_WEB_BROWSER=0
        JUCE_USE_CURL=0
)
```

**Comment by baconpaul** [comment]
Yeah I did that and it compiled - and my diff would do it automatically. My point was that you could set it automatically if the NEEDS is false but over on the forum https://forum.juce.com/t/linux-juce6-cmake-with-needs-web-browser/38990/6 Someone shared an example why that’s wrong so let me close this!
