### ISSUE TITLE
JUCE Forum Login Broken

### ISSUE THREAD

**Issue by jakemumu** [juce-framework/JUCE#705]
Hey posting this here since I can't get into the forum. 

I sign in via the Roli website, but then go to JUCE forum and it still shows login, click login, and it shows me as logged in. 

I'm using newest safari on Catalina. Apologies as I know this isn't the best place to report this, feel free to close immediately. 

Best,

J

**Comment by McMartin** [comment]
If you are using Safari, there is a known issue: https://forum.juce.com/t/forum-and-safari-on-mojave-login/37715

Please try using another web browser.

**Comment by jakemumu** [comment]
ahh okay, thanks @McMartin -- just got a fresh computer I'll grab chrome

**Comment by ed95** [comment]
This should be fixed now with the new JUCE account changes.
