### ISSUE TITLE
How do I develop an audio plug-in on Linux?

### ISSUE THREAD

**Issue by quinor** [juce-framework/JUCE#712]
I'm trying to use JUCE to develop an audio plugin on Linux. I had encountered a few issues:
- The linux makefile doesn't seem to build the VST3/AU plugins even though I had checked the right box in the projucer. Am I doing anything wrong or it's just not supported yet?
- The AudioPluginHost does not seem to be able to load VST3/AU plugins at all - does that mean that I have to use a different plugin type to work with the AudioPluginHost? How do I make Projucer export the right one? I've seen "internal" type plugins being supported, but I wasn't able to export one.
- In general, how do I set up my Linux workflow in order to be able to use Projucer/AudioPluginHost for plugin development on Linux?

A few technical details:
- I had pulled the up-to-date JUCE from the develop branch and compiled it by hand enabling the GPL mode
- I'm working on Arch Linux (x86_64)

**Comment by jokla** [comment]
Hi @quinor .
I have the same problem. I just found out that JUCE6 supports now VST3 plugin ([see here](https://forum.juce.com/t/vst3-support-on-linux/31872/12)). I will try to build Juice6 from this branch  https://github.com/juce-framework/JUCE/tree/juce6

**Comment by quinor** [comment]
I managed to build JUCE6 on Linux. It worked, but in AudioPluginHost there is no builtin plugin that would simply loop over a sound file (so that I can then run it through my own plugin for testing).

**Comment by ed95** [comment]
JUCE 6 supports building and hosting VST3 plug-ins on Linux.
