### ISSUE TITLE
Warning: Token pasting of ',' and __VA_ARGS__ is a GNU extension

### ISSUE THREAD

**Issue by stijnfrishert** [juce-framework/JUCE#714]
Hi all,

Compiling the **Juce 6** GUI Example throws the above warning with Xcode 11.4.1 (AppleClang) and **-Wpedantic**. I'd like to run my projects with warnings as errors, but can't now.

Running macOS Catalina (10.15.4)

**Comment by reuk** [comment]
Thanks for the report, this should now be fixed on the juce6 branch.
