### ISSUE TITLE
[Juce 6, Windows] JUCE_USE_WINRT_WEBVIEW does not respond to right clicks

### ISSUE THREAD

**Issue by ghost** [juce-framework/JUCE#721]
Hi,

First of all, thanks for all the great work on JUCE.

I observe a problem with right clicking on new WinRT based WebBrowser component in JUCE 6. Whenever I right click on the component, the webview does not respond. I would expect the corresponding menu of (eg. depending on the position on the webpage, copy-paste options) to appear. Instead, the only response to right clicking comes if the application window is maximized. If and only if the application window is maximized and you right click, the window context menu appears on the upper left corner of the screen.

Example:
![right click](https://user-images.githubusercontent.com/63107755/81920976-9bf69f00-95e2-11ea-83ca-9ddb2517d89b.png)

Steps to reproduce: 
1) Open the WebBrowserDemo example application in projucer and enable the JUCE_USE_WINRT_WEBVIEW in the juce_gui_extra module. 
2) Build and run the application
3) Navigate to a web page eg. https://www.google.com
4) Un-maximize the window
5) Right click anywhere on the page. Result: nothing happens. Expected result: A pop-up menu from the web page at the location of the mouse pointer.
6) Maximize the window
7) Right click anywhere on the page. Result: The window manipulation pop-up menu appears on the upper left of the screen. Expected result: A pop-up menu from the web page at the location of the mouse pointer.
 
OS: Windows 10 19.09 64bit
Visual Studio 2019.
JUCE version: juce 6 technical preview (29c8b2358d344b4cc56aec5d10a30bd202408a96)

**Comment by ed95** [comment]
The WinRT WebView has been replaced with the more recent, chromium based `WebView2` in the JUCE 6 release. Right-clicks should work as expected.
