### ISSUE TITLE
demo runner can't show demo list

### ISSUE THREAD

**Issue by yinkaisheng** [juce-framework/JUCE#725]
Windows 7 sp1, x64, screen size 1366x768
I built the vs2017 solution with latest code(5.4.7 2020-05-20) in a Windows 10 and copied the ouput exe to a Windows 7 PC.
It runs but demo list is empty in Windows 7 .
There is no probilem in Windows 10.

![image](https://user-images.githubusercontent.com/5846696/82408712-c4791000-9a9e-11ea-9019-f17ff6626507.png)

![juce](https://user-images.githubusercontent.com/5846696/82408668-a90e0500-9a9e-11ea-9395-91e70b73339e.gif)

**Comment by ed95** [comment]
The DemoRunner needs to be inside the `JUCE/examples` directory to find the demos and resources.

**Comment by yinkaisheng** [comment]
OK, thanks.
