### ISSUE TITLE
Misspelling: ResizableBorderComponent misspelled at juce_ResizableEdgeComponent.h:L41

### ISSUE THREAD

**Issue by beer-mike** [juce-framework/JUCE#726]
https://github.com/juce-framework/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_gui_basics/layout/juce_ResizableEdgeComponent.h#L41

ResizableBorderComponent is misspelled at juce_ResizableEdgeComponent.h:L41. The '**a**' in "**Resizable**" is missing. This misspelling breaks the link in the HTML docs. Cheers.

**Comment by ed95** [comment]
Thanks, we've added this in [685dc4f](https://github.com/juce-framework/JUCE/commit/685dc4fd7876200a85fe710e98e3bde1224311af).
