### ISSUE TITLE
Typo: Rectangle::removeFromBottom Documentation Reports Wrong Result

### ISSUE THREAD

**Issue by beer-mike** [juce-framework/JUCE#729]
https://github.com/juce-framework/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_graphics/geometry/juce_Rectangle.h#L527

The documentation for <i>Rectangle::removeFromBottom</i> reports a returned result of (100, <b>250</b>, 300, 50) for the returned rect but my test shows the actual returned result is (100, <b>350</b>, 300, 50). The <b>pos.y</b> value of the returned rect is incorrect. I recommend doublechecking these results as I'm fairly tired at the moment. Cheers.

**Comment by ed95** [comment]
Good spot! We've corrected this [here](https://github.com/juce-framework/JUCE/commit/b77b14c6c3ab8a736ff852966689f1b5b48ed72f).
