### ISSUE TITLE
Typo: Rectangle::removeFromRight Documentation Reports Wrong Result

### ISSUE THREAD

**Issue by beer-mike** [juce-framework/JUCE#730]
https://github.com/juce-framework/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_graphics/geometry/juce_Rectangle.h#L510

The documentation for <i>Rectangle::removeFromRight</i> reports a returned result of (<b>250</b>, 100, 50, 300) for the returned rect but my test shows the actual returned result is (<b>350</b>, 100, 50, 300). The <b>pos.x</b> value of the returned rect is incorrect. I recommend doublechecking these results as I'm fairly tired at the moment. Cheers.

**Comment by ed95** [comment]
https://github.com/juce-framework/JUCE/issues/729#issuecomment-632627767
