### ISSUE TITLE
BubbleComponent::updatePosition() Does Not Appear to Exist

### ISSUE THREAD

**Issue by beer-mike** [juce-framework/JUCE#731]
https://github.com/juce-framework/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_gui_extra/misc/juce_BubbleMessageComponent.h#L68

https://github.com/juce-framework/JUCE/blob/02bbe31c0d2fb59ed32fb725b56ad25536c7ed75/modules/juce_gui_extra/misc/juce_BubbleMessageComponent.h#L91

The documentation for <code>BubbleMessageComponent::showAt</code> mentions a function, <code><b>BubbleComponent::updatePosition()</b></code>, that does not appear to exist.

**Comment by ed95** [comment]
Thanks for reporting, we've fixed this in https://github.com/juce-framework/JUCE/commit/9de335a575178c5a07eb8863598602b992e62252
