### ISSUE TITLE
 jpegint.h: No such file or directory

### ISSUE THREAD

**Issue by magnetophon** [juce-framework/JUCE#733]
I'm packaging Juce for NixOS, but I get:
``
/nix/store/796fpc57zsb4x57krgcdspxk0vp2rykq-glibc-2.30-dev/include/features.h:382:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
In file included from ../../../../modules/juce_graphics/image_formats/juce_JPEGLoader.cpp:148,
                 from ../../../../modules/juce_graphics/juce_graphics.cpp:130,
                 from ../../JuceLibraryCode/include_juce_graphics.cpp:9:
/nix/store/78zkj5rkgm140n3rvmxall7qn613jhh5-libjpeg-turbo-2.0.4-dev/include/jpeglib.h:1122:10: fatal error: jpegint.h: No such file or directory
 1122 | #include "jpegint.h"            /* fetch private declarations */
      |          ^~~~~~~~~~~
compilation terminated.
``

NixOS unstable 64-bit: 20.09pre225264.683c68232e9
Juce version 5.4.7

**Comment by McMartin** [comment]
JUCE comes with its own copy of jpglib (in https://github.com/juce-framework/JUCE/tree/5.4.7/modules/juce_graphics/image_formats/jpglib), so it should not include `jpeglib.h` from another location.

**Comment by magnetophon** [comment]
@McMartin Thanks!
I noticed that too.
Any idea how come it's not being found?

**Comment by McMartin** [comment]
`juce_JPEGLoader.cpp` contains:

https://github.com/juce-framework/JUCE/blob/1e71c07a492f01022f9064560c95c2bcd938847c/modules/juce_graphics/image_formats/juce_JPEGLoader.cpp#L35-L40

https://github.com/juce-framework/JUCE/blob/1e71c07a492f01022f9064560c95c2bcd938847c/modules/juce_graphics/image_formats/juce_JPEGLoader.cpp#L142-L149

so I guess `JUCE_INCLUDE_JPEGLIB_CODE` is defined to `0`.

**Comment by sehe** [comment]
@magnetophon did you end up getting it working? It seems the current nixpkgs.juce still doesn't have it, and none of the libjpeg package alternatives fits the bill

**Comment by magnetophon** [comment]
@sehe No, I lost interest soon after.
I've been developing using https://github.com/robbert-vdh/nih-plug instead.
