### ISSUE TITLE
[Juce 6, macOS] Reading a WebInputStream using an AudioFormatReader doesn't work

### ISSUE THREAD

**Issue by joelrobichaud** [juce-framework/JUCE#741]
Hi there!

I would like to use a `WebInputStream` (created using `URL::createInputStream`) as an `InputStream` for an `AudioFormatReader` (so that I can download and parse audio files in memory, keeping the audio content into an `AudioBuffer`).

Unfortunately, this does not seem to work. The file doesn't seem to be downloaded and the samples are all set to 0 by the reader. I would expect the `WebInputStream` to work just like any other stream when given to the reader.

Here's the code I'm using:
```
const juce::URL url("https://file-examples.com/wp-content/uploads/2017/11/file_example_WAV_1MG.wav");

juce::AudioFormatManager audioFormatManager;
audioFormatManager.registerBasicFormats();
std::unique_ptr<juce::AudioFormatReader> reader(audioFormatManager.createReaderFor(url.createInputStream(false)));

if (reader.get() != nullptr) {
    AudioSampleBuffer buffer;
    buffer.setSize(reader->numChannels, (int)reader->lengthInSamples);
    reader->read(&buffer, 0, (int)reader->lengthInSamples, 0, true, true);

    // All of the samples in the buffer are set to 0 after the call to read!
}
```

From what I can see, the first call to `read` in `juce_mac_Network.mm` returns 0 because there is no data for it to consume.

**Comment by jwietelmann** [comment]
This looks very similar to a problem I'm having today. The server never receives the request, and this returns an empty string:

```
url.readEntireTextStream()
```

But it actually works fine for my VST3 build. It only fails for my Audio Unit. @joelrobichaud is that the case for you, too?

**Comment by ultraaudio** [comment]
I am having the same issue decoding ogg files from Amazon S3. Did you ever solve it?

**Comment by chromadevlabs** [comment]
When testing with the provided URL, it resolves to a page instead of the actual wav file on my machine with your test code.

**Comment by chromadevlabs** [comment]
Looked into this today.

This is a side effect of the WebInputStream and how AudioFormats are read. Some formats require seeking back and forth to correctly decode and thats not possible with a WebInputStream on its own.

You can use a BufferedInputStream If you know the size of the audio file before hand.

This should work for you (URL issues aside)


```
juce::AudioFormatManager audioFormatManager;
audioFormatManager.registerBasicFormats();

const auto fileSize = 1 * 1024 * 1024;
const juce::URL url("https://file-examples.com/wp-content/uploads/2017/11/file_example_WAV_1MG.wav");
const auto options = URL::InputStreamOptions(URL::ParameterHandling::inAddress).withConnectionTimeoutMs(1000);
auto stream = std::make_unique<BufferedInputStream>(url.createInputStream(options).release(), fileSize, true);

if (auto reader = audioFormatManager.createReaderFor(std::move(stream)))
{
  AudioSampleBuffer buffer;
  
  buffer.setSize(reader->numChannels, (int)reader->lengthInSamples);
  reader->read(&buffer, 0, (int)reader->lengthInSamples, 0, true, true);
}
```
