### ISSUE TITLE
VST3 only - setLatencySamples crashing Ableton Live 10

### ISSUE THREAD

**Issue by audiority** [juce-framework/JUCE#742]
Since JUCE 5.4.6, VST3 plugins setting latency in process are crashing Ableton Live 10.

OS tested: OSX 10.14.3, OSX 10.14.6, Windows 10
Ableton Live 10.1.13, 10.1.15

To replicate: 

- use setLatencySamples(2) (or any other value) in processBlock.
- open a new Ableton Live 10 project and add the plugin (be sure it's reporting latency)
- save the project
- close Ableton, open it again and load the saved project

**Comment by audiority** [comment]
Looks like the issue has been introduced with this commit: https://github.com/juce-framework/JUCE/commit/d00d23139c659d3fc823e368502f0c47d14f0c04

In void audioProcessorChanged (AudioProcessor*) override

The line: 
componentHandler->restartComponent (Vst::kLatencyChanged | Vst::kParamValuesChanged | Vst::kParamTitlesChanged);

By removing the flag Vst::kParamTitlesChanged, the plugin won't crash Ableton Live 10.

**Comment by ed95** [comment]
Thanks for reporting. This has been fixed in https://github.com/juce-framework/JUCE/commit/51fe471461f75fcfd72f7d0749382cbc149eef37.
