### ISSUE TITLE
juce_VST3PluginFormat.cpp: disconnecting then reconnecting an audiograph loses MIDI input

### ISSUE THREAD

**Issue by swarsys** [juce-framework/JUCE#744]
I found out that if I temporarily disconnect my Audiograph by using DeviceManager::removeAudioCallback, then reconnect it with DeviceManager::addAudioCallback, no MIDI input is received any longer. This happens only for VST3 format.

I was able to track it to this:

When the VST3 is loaded:

initialise -> setupIO -> setStateForAllInputBusEnabled(true)

Then when disconnecting:

removeAudioCallback -> releaseResources ->setStateForAllInputBusEnabled(false)

But then when reconnecting, addAudioCallback does not call for setStateForAllInputBusEnabled(true) in any way.

The whole VST3 implementation is very complex, so maybe this is the way it’s supposed to work, but could you please have a look at it and possibly fix that issue?

Thanks a lot.

**Comment by ed95** [comment]
Thanks for reporting. This has been fixed on the `develop` branch in https://github.com/juce-framework/JUCE/commit/b0790feab6df8b57ab9867aa3e2355a92ccb477b and https://github.com/juce-framework/JUCE/commit/a2d1fc412a288287c3a841046e0501bfc30f7bf7.

**Comment by swarsys** [comment]
Doesn't seem to be solved. When setStateForAllInputBusEnabled(false) is called, it seems to remove any MIDI buses in the component, so when we call setStateForAllInputBusEnabled(true) in preparePlayback, it has no effect, as no bus is found to be activated.
