### ISSUE TITLE
[Feature request] Add Oboe binary dependencies to JUCE

### ISSUE THREAD

**Issue by dturner** [juce-framework/JUCE#745]
In order to use Oboe (the recommended API for Android apps) in a JUCE project, you currently (as at projucer 5.4.7) need to: 

- Clone the Oboe source code at a specific commit SHA (which is not copy/pastable from the projucer)

![image](https://user-images.githubusercontent.com/873212/85393105-595ea580-b544-11ea-8f86-aabe0ec1aefc.png)

- Update Projucer with the Oboe source path

This is a lot of extra friction for anyone setting up an Android project and wanting to use Oboe (which they should because it'll give lower latency and better overall performance than OpenSL ES).

I'd like to propose a better method: 

Oboe is now [distributed as a binary package](https://github.com/google/oboe/blob/master/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers) so it should be as simple as updating the Android JUCE project template to include a dependency on the latest stable version of Oboe (currently 1.4.2).

**Comment by ed95** [comment]
Hi @dturner. As of https://github.com/juce-framework/JUCE/commit/719a4917 the Oboe source is included directly in JUCE and is the default audio path on Android. This is currently available on the `juce6` technical preview branch and will make its way onto the `develop` and `master` branches with the upcoming release (hopefully in the next week or so).

**Comment by dturner** [comment]
I mean, that's great news, however, it might be better to depend on the stable binaries in future because: 

- building Oboe from source will slow down your build (at least initially) and is more error prone
- updating to a new version of Oboe means cloning the source into JUCE each time

With the binary distribution you can just bump the version inside the `app/build.gradle` template and it'll be automatically downloaded - less maintenance and less things to go wrong.

**Comment by ed95** [comment]
The reasoning for including the Oboe source directly in the JUCE tree was that it's a more transparent process for users - they can see the source files directly and step into the code when debugging. We had some issues with the Oboe CMake package not compiling with the default JUCE compiler warnings, so including the source gives us full control over that too. It also looks like prefab support is only available in the latest Android Studio version, so we'd be forcing users to upgrade if they wanted to use Oboe which some may not want to do. 

It's something we'll look into but for now the in-source approach seems to be working well and is much easier than before, as well as meaning that we can use Oboe as the default audio device on Android in JUCE 6.

**Comment by dturner** [comment]
Fair enough. Thanks for the explanation.
