### ISSUE TITLE
Latest release of Android Oboe 1.4.2 or later should be included

### ISSUE THREAD

**Issue by philburk** [juce-framework/JUCE#748]
JUCE includes the source code for Oboe 1.2.4.
But the more recent version, 1.4.2, has a workaround for a serious crashing bug
in AudioFlinger that can occur when a headset is plugged in.

https://github.com/google/oboe/releases/tag/1.4.2

**Comment by ed95** [comment]
Hi Phil. Thanks for the heads up, I've updated the Oboe sources to 1.4.2 on the `develop` branch in https://github.com/juce-framework/JUCE/commit/5fe53862ae274131d8d3bdb698d78caf62324327.
