### ISSUE TITLE
[JUCE 6, Linux, 32-bit Raspian (buster)] Failed to Build juceaide

### ISSUE THREAD

**Issue by RitchRock** [juce-framework/JUCE#749]
I've cloned the GIT repository on my Raspberry Pi 4 running Raspbian GNU/Linux 10 (buster), but running the first command in the readme.md:

> cmake . -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON

Is throwing up some errors:

> -- Configuring juceaide
> -- Building juceaide
> CMake Error at extras/Build/juceaide/CMakeLists.txt:86 (message):
>   Failed to build juceaide
> 
>   [ 12%] Linking CXX executable juceaide_artefacts/Debug/juceaide
> 
>   /usr/bin/ld:
>   CMakeFiles/juceaide.dir/__/__/__/modules/juce_core/juce_core.cpp.o: in
>   function `std::__atomic_base<long long>::operator long long() const':
> 
>   /usr/include/c++/8/bits/atomic_base.h:396: undefined reference to
>   `__atomic_load_8'
> 
>   /usr/bin/ld:
>   CMakeFiles/juceaide.dir/__/__/__/modules/juce_core/juce_core.cpp.o: in
>   function `std::__atomic_base<long long>::operator^=(long long)':
> 
>   /usr/include/c++/8/bits/atomic_base.h:344: undefined reference to
>   `__atomic_fetch_xor_8'
> 
>   collect2: error: ld returned 1 exit status
> 
>   make[2]: *** [extras/Build/juceaide/CMakeFiles/juceaide.dir/build.make:195:
>   extras/Build/juceaide/juceaide_artefacts/Debug/juceaide] Error 1
> 
>   make[1]: *** [CMakeFiles/Makefile2:153:
>   extras/Build/juceaide/CMakeFiles/juceaide.dir/all] Error 2
> 
>   make: *** [Makefile:150: all] Error 2
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/Documents/JUCE/cmake-build/CMakeFiles/CMakeOutput.log".

Unfortunately the output log does not tell me much.

**Comment by lkotsonis** [comment]
I found a similar issue here: https://github.com/alexa/avs-device-sdk/issues/1404

Did you fix the issue? If not, could you try what is suggested in the above link?

**Comment by RitchRock** [comment]
> I found a similar issue here: [alexa/avs-device-sdk#1404](https://github.com/alexa/avs-device-sdk/issues/1404)
> 
> Did you fix the issue? If not, could you try what is suggested in the above link?

Following this did get rid of that error. I added:

`set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`

To /JUCE/CMakeLists.txt
