### ISSUE TITLE
Improve discoverability in GitHub search

### ISSUE THREAD

**Issue by kmturley** [juce-framework/JUCE#750]
Currently in GitHub search results Juce shows as:

![Screen Shot 2020-07-03 at 11 19 42 PM](https://user-images.githubusercontent.com/1710493/86506384-d16a6e00-bd83-11ea-8ba8-041858c4fbd6.png)

And on your organization page:

![Screen Shot 2020-07-03 at 11 21 18 PM](https://user-images.githubusercontent.com/1710493/86506401-f3fc8700-bd83-11ea-923c-294346f040f4.png)

It doesn't explain what the framework does, until you click through to the repository itself:

![Screen Shot 2020-07-03 at 11 22 35 PM](https://user-images.githubusercontent.com/1710493/86506418-19899080-bd84-11ea-858c-f4ec905533d2.png)

When searching GitHub for audio plugins, VSTs or plugin toolkits Juce does not appear, because those keywords do not appear anywhere.

Suggestion is to add a description and tags which explain what Juce does:

> JUCE is an open-source cross-platform C++ application framework used for rapidly developing high quality desktop and mobile applications, including VST, AU (and AUv3), RTAS and AAX audio plug-ins.

With tags such as:
- C++
- framework
- applications
- audio
- plugin
- VST

I only found out about your framework by a YouTube video! Think of how many potential users are missing your framework because they simply didn't find it in search! :)

**Comment by tpoole** [comment]
Thank you for the suggestion. I've put a few more words into the description.
