### ISSUE TITLE
[JUCE 6, Linux] JUCE 6 doesn't detect X11 on Raspberry Pi running VNC

### ISSUE THREAD

**Issue by tommag** [juce-framework/JUCE#751]
Hello, 

I'm running [Chataigne](https://github.com/benkuper/Chataigne) on a Raspberry Pi 3B+ with stock Raspberry Pi OS (Debian Buster 32 bit), with no monitor attached (via VNC).

Since the recent update to JUCE 6.0.0, no windows are created and a lot of assertions fail when launching the program : 

    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1300
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1416
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1483
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1471
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1483
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
    JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1380

I managed to launch a debug session (I'm on an "old" Pi 3B+ with only 1GB of RAM) and I saw that on this line : 
https://github.com/juce-framework/JUCE/blob/master/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp#L1237 the variable `xIsAvailable` is `false`. 

It seems that the recent commit https://github.com/juce-framework/JUCE/commit/0f6cdd845792b3faba6cf94455f2921a617f33ef broke the X detection on some systems, is it possible that there is a timing issue somewhere or that only the first call to `loadAllSymbols()` return true ?

It turns out that after installing `libx11-dev` the windows load just fine (same behavior with the Projucer, it starts correctly with `libx11-dev` but returns the following output if I uninstall this package. 

```
pi@raspberrypi:~/JUCE/extras/Projucer/Builds/LinuxMakefile/build $ ./Projucer 
JUCE v6.0.0

**********************************************************
Projucer 6.0.0  ---  Build date: Jul  5 2020
Log started: 5 Jul 2020 7:07:43pm

Linux
CPU: 0MHz  Cores: 4  926MB
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1300
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1416
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1483
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1559
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1471
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1483
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1559
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1471
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1725
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1664
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:2664
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1725
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1698
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1471
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1725
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1698
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:750
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1645
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1804
JUCE Assertion failure in juce_linux_XWindowSystem.cpp:1804

```

This package was not needed with the same code compiled with a snapshot of the develop branch from the 8th of June.

**Comment by ed95** [comment]
libX11 is required for anything GUI-related on Linux using JUCE. The recent changes have been to load the X11 symbols dynamically at runtime, so instead of JUCE programs linking directly to the X libraries instead they attempt to load all of the required symbols from `libX11.so`, `libXext.so` etc. at program startup. This means that if the libraries aren't present, we can fall back to some sensible default behaviour instead of throwing a linker error and exiting the program immediately. The assertions that you're seeing are due to invalid window handles as the program is trying to open and interact with a window on a system which doesn't have the libs installed. Are you saying that the program used to work correctly before these changes on a system without any of the X11 libraries installed?

**Comment by tommag** [comment]
Requiring `libX11` for a program running on X sounds totally reasonable :) 

However, the issue is that it now also requires `libX11-dev` i.e. the header files that should normally only be necessary to compile the program from source, not to run it. 

Before the commit that I referenced, AFAIK the dev package was not required. We noticed this issue because some users reported that the newest releases of the program stopped working on the Raspberry Pi (when updating the develop branch from  https://github.com/juce-framework/JUCE/commit/ae35ebd5bcfd741a7c6a355b07290e9891b435c7 to 6.0.0).

Cheers,

**Comment by tommag** [comment]
I have just tested on a "regular" Linux system (x86-64 laptop running Debian buster) and `libX11-dev` is indeed necessary (and probably `libxcursor-dev libxinerama-dev libxrandr-dev` as well, without those installed I had strange display issues). 

It was not the case before, the same software used to launch on this machine but to use the latest release I had to install the `dev` packages.

Cheers,

**Comment by ed95** [comment]
Thanks! I can see what the problem is now - we're using the unversioned, symlinked `.so`s for the X libs which are only present if the user has installed the *-dev packages. In https://github.com/juce-framework/JUCE/commit/c64ddc449042d8e359b69585ef6ce8582b255e66 we're now using the versioned libs so this should work correctly with both dev and non-dev libs.

**Comment by tommag** [comment]
Awesome! Many thanks for the quick fix!
