### ISSUE TITLE
JUCE6 Critical break ! Point<float> * integer  is rounded (same for Point<float>/ integer)

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#755]
Hello,
after updating to JUCE 6, a LOT of app started to act weird because now when doing operation between Point<float> and integers, the result is rounded, whereas in JUCE5, the result was properly handled (like doing float * int).

This breaks a lot of things !!! 

I saw some changes in the file 10 days ago but not sure about how to check that this commit is the one causing troubles : https://github.com/juce-framework/JUCE/commit/394c4fd475c58804d3766f7b8f1000e2bbbcc46d#diff-92687d8e23efda4e218b0eeb752e78ce

Is it reproducible for you ? now I have to cast ALL Point<float>*integer and Point<float>/integer operations, which doesn't seem the good thing to do...

**Comment by tpoole** [comment]
Thank you for reporting.

We've fixed things, https://github.com/juce-framework/JUCE/commit/754ec66b42da46e5ff15021774eaad9710e1508e, and will get this onto the master branch shortly.
