### ISSUE TITLE
Shouldn't the device first be stopped via AudioDeviceManager::stopDevice() before it is deleted?

### ISSUE THREAD

**Issue by ianacaburian** [juce-framework/JUCE#758]
https://github.com/juce-framework/JUCE/blob/98c19f752fcdf9c2dc80ba2deb227f4ce26a5c70/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp#L550

For example, when a user switches between different output devices, the AudioProcessor::releaseResources() callbacks (which could contain important memory management logic) are correctly called UNLESS the user switches from some audio output device to no output. While this state is certainly not normal, the audio callback has been ceased without being "released" via releaseResources() which could lead to unexpected state, particularly if some lock-free queue logic has been built around releaseResources() triggering some logic to prevent queues from being overwritten or overloaded, etc.

**Comment by ed95** [comment]
Yes that sounds sensible, thanks! We've added this in https://github.com/juce-framework/JUCE/commit/21e452289180b1e348d5fffcb7fa4eea92f24f83.
