### ISSUE TITLE
File Manager doesn't open when trying to create a new class

### ISSUE THREAD

**Issue by felipebalbi** [juce-framework/JUCE#765]
When using `Projucer` with `xmonad` (a tiling window manager) on Linux, I can't get file manager to open when trying to create a new class.

I use Thunar as my File Manager but it won't open. What's the requirement for `Projucer` to be able to open the File Manager? Is it sending a message on `dbus` or how does it open the File Manager?

1) Steps to reproduce

     - Open Projucer on `xmonad`
     - Create new project
     - Click the + button
     - Click on "Add New CPP & Header File"

2) Expected Behavior

    - File Manager opens and let's us choose where to save new class and Header

3) Operating System

    - Arch Linux running Linux version 5.7.9-arch1

4) Architecture

    - x86 64-bit

**Comment by felipebalbi** [comment]
A gentle remind here, are there any hints?

Thank you

**Comment by ed95** [comment]
`kdialog` or `zenity` are required for the native file browser on Linux.

**Comment by felipebalbi** [comment]
@ed95 tested with `zenity` and it works fine. Thank you
