### ISSUE TITLE
Fitted text does not fill the specified width.

### ISSUE THREAD

**Issue by joshua-maros** [juce-framework/JUCE#768]
Steps to reproduce:
1. Create or open an audio plugin project.
2. Replace the body of `PluginEditor::paint(Graphics)` with:
```cpp
auto str = "Audiobench is free and open source software. You are free to do anything you want with it, including selling any audio, patches, or modules you make with or for this software.";
int x = 16;
int y = 200;
int w = 600;
int h = 200;
auto justification = Justification::topLeft;
int maxLines = 5;
float minScale = 1.0f;
g.setColour(Colours::black);
g.fillRect(x, y, w, h);
g.setColour(Colours::white);
g.drawFittedText(str, x, y, w, h, justification, maxLines, minScale);
```

Problem:
Despite the width parameter being `600` in both cases, the text is wrapped a good deal before the end of the rectangle.

Expected behavior:
'it, including' should be on the first line as there is still enough space to fit it without wrapping.

![Screenshot_20200729_223548](https://user-images.githubusercontent.com/60271685/88884627-dd631780-d1eb-11ea-86f9-7c12cf4f6792.png)

**Comment by tpoole** [comment]
drawFittedText is designed as a quick solution to things like labels and buttons, where some degree of clumpiness with lines having similar lengths is desired.

For longer pieces of text you should use AttributedString, which will also benefit from being rendered more quickly on some platforms.

```cpp
Rectangle<float> bounds { 16.0f, 200.0f, 600.0f, 200.0f };
g.setColour (Colours::black);
g.fillRect (bounds);
AttributedString str ("Audiobench is free and open source software. You are free to do anything you want with it, including selling any audio, patches, or modules you make with or for this software.");
str.setJustification (Justification::topLeft);
str.setColour (Colours::white);
str.draw (g, bounds);
```

**Comment by joshua-maros** [comment]
Ah, ok. Thanks for the clarification.
