### ISSUE TITLE
Assertion Errors after updating from JUCE 5.4.4 to 6.0.1

### ISSUE THREAD

**Issue by Patrick-M90** [juce-framework/JUCE#771]
Hello,
since updating from JUCE 5.4.4 to 6.0.1 I'm getting some Assertion Errors (e.g. InputStream:46) when creating AudioFormatReaders for a lot of audiofiles in my iOS app. On 5.4.4 everything works good.

FYI in my app I load project files, which may contain URLs to many different audio files, which have to be read an playback simultaneously.

Is this a bug in JUCE 6.0.1 or is it my fault?

**Comment by tpoole** [comment]
We'll need a little more context before we can help. Can you provide some source code to show us what you're doing?

The [JUCE forum](https://forum.juce.com) is the best place to get assistance.

**Comment by Patrick-M90** [comment]
Hello,
Thanks for your fast reply.

I'm doing this (in addition of a lot of other things) in a loop for many hundred files (in a huge project) when loading a self-created project xml:
                    if (reader == nullptr){
                        std::unique_ptr<InputStream> is = fullURL.createInputStream (false);

                        if (is != nullptr){
                            reader = formatManager->createReaderFor (fullURL.createInputStream (false));
                        } else {
                            DBG("Failed createInputStream");
                        }
                        
                    }

After 293 executions I'm getting assertion errors:
JUCE Assertion failure in juce_FileInputStream.cpp:46
JUCE Assertion failure in juce_FileInputStream.cpp:71
JUCE Assertion failure in juce_FileInputStream.cpp:46
JUCE Assertion failure in juce_FileInputStream.cpp:71
JUCE Assertion failure in juce_FileInputStream.cpp:38
JUCE Assertion failure in juce_FileInputStream.cpp:46
JUCE Assertion failure in juce_FileInputStream.cpp:38
JUCE Assertion failure in juce_FileInputStream.cpp:38

Skipping the file at position 294 and continuing with the next file does not help, so I think the file itself is not the problem.

Switching back to JUCE 5.4.4 and changing the code to:

                  if (reader == nullptr){
                        **InputStream*** is = fullURL.createInputStream (false);
                        if (is != nullptr){
                            reader = formatManager->createReaderFor (**is**);
                        } else {
                            DBG("Failed createInputStream");
                        }
                    }
helps for me.

Thanks in advance :)

**Comment by tpoole** [comment]
The two bits of code are not functionally equivalent.

The old code checks if the input stream has been created (not equal to nullptr), then uses that stream.

The new code checks if a stream has been created, then creates a *different* concurrent stream (without checking) and uses that. Try:

    formatManager->createReaderFor (std::move (is));

**Comment by Patrick-M90** [comment]
Thanks, I was a bit inexperienced with the new return type.

**Sadly, the updated code leads to the same result. :(**

**Comment by Patrick-M90** [comment]
Could it be that the errors are being thrown because I am handling the loading process in a separate thread?

**Comment by tpoole** [comment]
There have been no threading changes explicitly related to reading files in JUCE 6, and I can't spot anything else amis with your code sample.

Please post a more detailed report, ideally using something that recreates the problem in a much simpler app, on the JUCE forum: https://forum.juce.com The forum gets many more views that GitHub issues and it possible that someone else might recognise what's happening.

**Comment by Patrick-M90** [comment]
Hello,
I found out that the according FileInputStream hast an errorMessage with the text value "Too many open files".
Why is this only happening in Juce 6 and what can I do to avoid this?

**Comment by tpoole** [comment]
That would suggest that you should close files immediately after you have read their contents. This is likely be triggered by different lifetimes of various objects as a result of handling memory via unique_ptrs.

The code sample you have provided doesn't contain enough information for us to be able to help you. To get assistance please post a more complete example on the JUCE forum: https://forum.juce.com.
