### ISSUE TITLE
[JUCE6][Linux] U-he, xhip (and maybe other VST2) plugins are broken.

### ISSUE THREAD

**Issue by KottV** [juce-framework/JUCE#777]
Please include:

  1) Run JUCE6 host, for example Tracktion Waveform 11.1.1x beta or AudioPluginHost on Linux
Add any U-he (VST2) plugin or xhip http://xhip.net/alpha/
Open plugin
  2) Plugin's UI has to be displayed but it draws garbage or frozen bitmap of underlay window.
  3) Linux openSUSE Thumbleweed 
  4) x86_64
  5) no crash or error in stdout
  6) VST2
  7) Tracktion Waveform 11.1.1x beta or AudioPluginHost (from develop branch)

**Comment by KottV** [comment]
I've checked this on plain new Ubuntu 20.04 and got same result with AudioPluginHost and xhip

**Comment by mikobuntu** [comment]
I can confirm that vst2 of all LSP plugins exhibit the same behaviour running Waveform 11.1.2x as explained by Kott.

**Comment by ed95** [comment]
This has been fixed in https://github.com/juce-framework/JUCE/commit/3f78998b967979da8523030ba76e807d4431efcd
