### ISSUE TITLE
cmake project on ubuntu bionic - gtk headers not found

### ISSUE THREAD

**Issue by ulph** [juce-framework/JUCE#786]
(this works fine on osx including ios targets)

here is a snippet that oulines the the target (static lib,)

---

add_subdirectory(JUCE) # as opposed to find_package

target_link_libraries(mylib PRIVATE
    juce::juce_audio_basics
    juce::juce_audio_devices
    juce::juce_audio_formats
    juce::juce_audio_processors
    juce::juce_core
    juce::juce_cryptography
    juce::juce_data_structures
    juce::juce_dsp
    juce::juce_events
)

---

... / JUCE/modules/juce_gui_extra/juce_gui_extra.cpp:121:11: fatal error: gtk/gtk.h: No such file or directory
  #include <gtk/gtk.h>

---

As far as I understand, PkgConfig should take care of this?

There are of course workarounds...

**Comment by ulph** [comment]
find /usr/include/ -name gtk.h
>
/usr/include/gtk-3.0/gtk/gtk.h
/usr/include/gtk-2.0/gtk/gtk.h

...

pkg-config gtk+-2.0 --cflags
> ...
-I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include
...

so system is ok

**Comment by McMartin** [comment]
Unless you really need the Web browser, you can add 
```cmake
target_compile_definitions(mylib PUBLIC JUCE_WEB_BROWSER=0)
```
to remove it from the build.

**Comment by ulph** [comment]
ok, so adding that define I no longer end up building juce_gui_extra module, which is where all my issues were. a passable workaround in my case as I actually don't want that module.

issue remains though in that link and include paths are not set up correctly

case in point, I now run into a linking issue with curl (but also here, curl / curl-dev is installed!)

it turns out I need to 
target_compile_definitions(tart PUBLIC JUCE_USE_CURL=0)
to bypass that problem

**Comment by McMartin** [comment]
If you want to enable using curl, then you need to pass `NEEDS_CURL TRUE` to the `juce_add_{gui_app,console_app,plugin}` function.
See the documentation for `NEEDS_CURL` in https://github.com/juce-framework/JUCE/blob/6.0.3/docs/CMake%20API.md#juce_add_target.
