### ISSUE TITLE
Build errors in project generated with CLion (beta) exporter

### ISSUE THREAD

**Issue by rn1d** [juce-framework/JUCE#790]
I'm seeing a build errors and warnings when using the CLion (beta) exporter after upgrading to Juce 6.0.3 from 6.0.1. 

I can reproduce this with the tutorial project generated from the PIP file: https://docs.juce.com/master/tutorial_audio_device_manager.html

After opening the project in CLion (and fixing CMake root), I get errors related to `set_target_properties`:

```
CMake Error at CMakeLists.txt:2887 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

When comparing the  CMakeLists.txt generated by 6.0.3 to 6.0.1, I see that this is new and appears to cause it:

```
    XCODE_ATTRIBUTE_MTL_HEADER_SEARCH_PATHS (
					"../../JuceLibraryCode",
					"$(HOME)/JUCE/modules",
				)
```

The error goes away if I remove the trailing comma after the last element in the list, and the warnings go away if the value is all on one line, like so:

```
    XCODE_ATTRIBUTE_MTL_HEADER_SEARCH_PATHS ("../../JuceLibraryCode", "$(HOME)/JUCE/modules")
```

I can't seem to get rid of all the warnings, but at least I can work around the error and keep using CLion. This workaround works for me, but obviously, the CMake project is regenerated every time CLion is opened from Projucer. 

I'm using macOS Big Sur (latest public beta), Juce 6.0.3, CLion 2020.2.4.

**Comment by McMartin** [comment]
According to https://forum.juce.com/t/clion-exporter-broken-on-mac/42001/12, this has been fixed on the `develop` branch.
