### ISSUE TITLE
juce_FFT calls deprecated IPP function

### ISSUE THREAD

**Issue by PeterEmanuel** [juce-framework/JUCE#799]
Building a plugin with Visual Studio 2019 on Windows 10 shows a deprecation message from Intel IPP (version 8).

This function is called:

(line 4451 in ipps.h)

```
IPP_DEPRECATED("is deprecated. Integer APIs for linear transforms are obsolete and will be removed in one of the future IPP releases. All linear-transform functions are FP internally - use FP variant of this function. Use the following link for details: https://software.intel.com/sites/products/ipp-deprecated-features-feedback/")\

IPPAPI (IppStatus, ippsFFTFwd_RToCCS_32f_I, ( Ipp32f* pSrcDst, const IppsFFTSpec_R_32f* pFFTSpec, Ipp8u* pBuffer ))
```

Called by:

    void performRealOnlyForwardTransform (float* inoutData, bool ignoreNegativeFreqs) const noexcept override
    {
        ippsFFTFwd_RToCCS_32f_I (inoutData, real.specPtr, real.workBuf.get());
        // etc

Line 846 in juce_FFT

Is it possible to fix this call with a proper one?

Cheers,
Peter Emanuel Roos

**Comment by szarvas** [comment]
Taking a look at the current version 2021.6.0 of IPP I believe this issue no longer persists. I can see no deprecation message when compiling, and also all deprecation messages seem to have been removed from `ipps.h`.

I'm closing the issue, but we can reopen it in case there is still a problem.
