### ISSUE TITLE
Can `getApproximateScaleFactorForComponent()` take a `const Component*`?

### ISSUE THREAD

**Issue by tomfclarke** [juce-framework/JUCE#801]
https://github.com/juce-framework/JUCE/blob/78f9985e59bca8194942d63ee8beabc35241c36e/modules/juce_gui_basics/components/juce_Component.h#L617

**Comment by tpoole** [comment]
This has been fixed on the `develop` branch: https://github.com/juce-framework/JUCE/commit/9ccfea900149aa3b68c5edc7c88d9d5b43291b8a

Thank you for reporting.
