### ISSUE TITLE
Xcode 12.2 projects crash on older macOS (tested 10.8, 10.9)

### ISSUE THREAD

**Issue by talaviram** [juce-framework/JUCE#805]
Prior to Xcode 12.2, same projects with JUCE6 compiles and runs just fine.
Since Xcode 12.2, seems like Apple removed/changed their inclusion.

Here is our discussion on JUCE forum:
https://forum.juce.com/t/macos-10-9-5-symbol-not-found-objc-class-nsmutableurlrequest

We can 'resolve' this by adding Foundation ourselves:
![image](https://user-images.githubusercontent.com/6911158/100540062-9477aa00-3243-11eb-9cf7-0d4c9872f359.png)
(as was suggested by many stackoverflow answers - https://stackoverflow.com/questions/24043532/dyld-symbol-not-found-nsurlauthenticationmethodclientcertificate-when-trying?rq=1)

But I guess it'll be less breaking change if JUCE Projucer generator would add Foundation by itself.
(I didn't test CMake so it might need similar support over there too).

**Comment by McMartin** [comment]
I guess the patch to apply is:
```diff
--- a/modules/juce_core/juce_core.h
+++ b/modules/juce_core/juce_core.h
@@ -39,7 +39,7 @@
   license:            ISC

   dependencies:
-  OSXFrameworks:      Cocoa IOKit
+  OSXFrameworks:      Cocoa Foundation IOKit
   iOSFrameworks:      Foundation
   linuxLibs:          rt dl pthread
   mingwLibs:          uuid wsock32 wininet version ole32 ws2_32 oleaut32 imm32 comdlg32 shlwapi rpcrt4 winmm
```

**Comment by ed95** [comment]
Thanks, added in https://github.com/juce-framework/JUCE/commit/45a2e57bf9a371a3a77d10cf746d965191854a9a.
