### ISSUE TITLE
cmake --build using --target does not generate VST/AU files

### ISSUE THREAD

**Issue by kmturley** [juce-framework/JUCE#806]
**Describe the issue:**

When building [AudioPluginExample](https://github.com/juce-framework/JUCE/tree/master/examples/CMake/AudioPlugin) it generates different files if --target is used vs not. It's my understanding that --target parameter limits the build to a single project, and should not affect whether VST/AU files are generated or not.

It works when omitting the --target parameter, but that requires you to generate every project. We need to be able to generate VST/AU files, without having to build every project in the child directories.

**Steps to reproduce:**

1) Clone the repo:
```
git clone https://github.com/juce-framework/JUCE
```

2) Install cmake:
```
brew install cmake
```

3) Install Xcode:
```
xcode-select --install
```

4) Run cmake generator command:
```
cmake \
  -G "Xcode" \
  -DJUCE_BUILD_EXAMPLES=ON \
  -DJUCE_BUILD_EXTRAS=OFF \
  -S . \
  -B ./build
```

5) Run cmake build command with target included:
```
cmake --build ./build --config Debug --target AudioPluginExample
```

6) Notice the VST/AU files are is not generated in the folder:
```
./build/examples/CMake/AudioPlugin/AudioPluginExample_artefacts
```

![Screen Shot 2020-11-29 at 9 39 30 AM](https://user-images.githubusercontent.com/1710493/100549294-f1b13280-3226-11eb-83e1-ff6b3840323a.png)

7) Now run cmake build command without target included (and wait a long time):
```
cmake --build ./build --config Debug
```

8) Notice the VST/AU files are now generated in the folder:
```
./build/examples/CMake/AudioPlugin/AudioPluginExample_artefacts
```

![Screen Shot 2020-11-29 at 9 40 30 AM](https://user-images.githubusercontent.com/1710493/100549298-f8d84080-3226-11eb-9cf2-ec5535b79dff.png)

**Expected behaviour**

Builds using the target command should also generate VST/AU files

**System details**

- Machine: MacBook Pro (15-inch, 2017)
- OS: MacOS Catalina 10.15.7
- IDE: Visual Studio Code 1.51.1
- Cmake: 3.19.1
- Xcode: 12.2

**Comment by McMartin** [comment]
An Audio Plug-In project in made of several targets:
- the static library where all shared code is built (here AudioPluginExample)
- one target per plugin format (here AudioPluginExample_AU, AudioPluginExample_Standalone, and AudioPluginExample_VST3), which depends on the static library 
- a meta-target that depends on all previously mentioned targets (here AudioPluginExample_All)

I guess running `cmake --build . --target AudioPluginExample_All` would give you the expected behavior.

I hope this helps!

**Comment by kmturley** [comment]
Amazing, thanks for the quick response. I tried and it works as expected, thank-you!

Is this functionality documented somewhere? I think it would be useful for first-time users. README.md documents a simple case:
```
cd /path/to/JUCE
cmake . -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON
cmake --build cmake-build --target DemoRunner
```
https://github.com/juce-framework/JUCE/blob/master/README.md

Wondering if this could be expanded?

**Comment by kmturley** [comment]
Looks like there is another variation when using different generators `Xcode` vs `Unix Makefiles` the folder structure is slightly different which is a pain when trying to generate all platforms:
```
cmake \
  -G "Xcode" \
  -DJUCE_BUILD_EXAMPLES=ON \
  -DJUCE_BUILD_EXTRAS=OFF \
  -S ./jucesdk \
  -B ./build
cmake --build ./build --config Debug --target AudioPluginExample_All
```

Notice there is a Debug folder:
![100549298-f8d84080-3226-11eb-9cf2-ec5535b79dff](https://user-images.githubusercontent.com/1710493/100554439-8036ab80-3249-11eb-8380-cb70df4cb913.png)


```
cmake \
  -G "Unix Makefiles" \
  -DJUCE_BUILD_EXAMPLES=ON \
  -DJUCE_BUILD_EXTRAS=OFF \
  -S ./jucesdk \
  -B ./build
cmake --build ./build --config Debug --target AudioPluginExample_All
```

Notice there is not a Debug folder:

![Screen Shot 2020-11-29 at 1 47 19 PM](https://user-images.githubusercontent.com/1710493/100554461-a4928800-3249-11eb-8b7a-4607d20a0d78.png)

**Comment by McMartin** [comment]
"Unix Makefiles" is a single-config generator, while "Xcode" is a multi-config generator.

When using a single-config generator, the build type is specified when generating the build system by defining [`CMAKE_BUILD_TYPE`](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.HTML). For instance:
```
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
cmake --build . 
```

When using a [multi-config generator](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html), the build type is selected when building. For instance:
```
cmake .. -G "Xcode"
cmake --build . --config Debug
```

**Comment by kmturley** [comment]
Ah that makes sense. I had `-DCMAKE_BUILD_TYPE=Debug` on my Steinberg VST SDK plugin template, but had removed it for the JUCE plugin template.

I'm working on an ecosystem of open-source tools to automatically build and distribute audio plugins:
https://github.com/studiorack

The plugin templates use GitHub actions CI to automatically build plugins for Mac, Windows and Linux and publish a versioned release on Github:
https://github.com/studiorack/studiorack-plugin-juce

Then you can use the StudioRack website, app or command line tool to install the plugins.
