### ISSUE TITLE
VST2: Why is "Vst2::effOpen" called in VSTPluginFormat::findAllTypesForFile?

### ISSUE THREAD

**Issue by kmatheussen** [juce-framework/JUCE#811]
https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L3496

Seems like this can slow down scanning. Also, it's not done for shell plugins.

**Comment by kmatheussen** [comment]
I tried commenting out this line, and it didn't really make the scanning go much faster, although I guess it could make a difference for some plugins. However, the function still worked just fine.

I'm speculating that perhaps the line was added to trigger an early crash, instead of a late crash, for buggy plugins?

**Comment by kmatheussen** [comment]
Why did you close it? The unnecessary call to Vst2::effOpen is still there.
There's even some people who experience crashes because of it (triggering
bugs in plugins):
https://forum.juce.com/t/vst-gets-created-twice-in-host-breaks-vst/22385

**Comment by tpoole** [comment]
As stated in this issue removing the call didn't make scanning go any faster. We're tracking the corresponding topic on the forum, and want to avoid duplicated bug reports across both GitHub and the forum.
