### ISSUE TITLE
Standalone mode broken for all MIDI-only plugins

### ISSUE THREAD

**Issue by jjYBdx4IL** [juce-framework/JUCE#812]
This assertion is doomed to fail when there is no audio bus:

https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.cpp#L54

Example: breaks the MIDILogger *standalone* example on PC (Visual Studio 19) in Debug mode.

**Comment by jjYBdx4IL** [comment]
Also, in release builds, the standalone app does not receive any MIDI events when there is no audio bus.

**Comment by ed95** [comment]
This should now be fixed on the `develop` branch with commits https://github.com/juce-framework/JUCE/commit/107a2cfe27f8e5f28bb4aab270cd07d9c1a2bcbb and https://github.com/juce-framework/JUCE/commit/04fdc4c20983c54d3bdaf6355814d29ad827c761.
