### ISSUE TITLE
Incompatibility with MacOS Big Sur version 11.1

### ISSUE THREAD

**Issue by zacharyabolton** [juce-framework/JUCE#817]
Hey folks,

This line throws an error (JUCE Message Thread (1): EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0) when I try to start a fresh project on MacOS Big Sur version 11.1. No issues on MacOS Big Sur version 11.0.

I "fixed" it locally with changing the line to 

`jassert (major == 11 && minor >= 0);`

But of course I have no idea what kinda unseen problems this might cause elsewhere. Just thought I'd let you know. First time using github for something like this. Pardon any lack of clarity.

https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/modules/juce_core/native/juce_mac_SystemStats.mm#L160

Love what y'all do BTW! Keep it up!

EDIT: I'm using XCode Version 12.3 (12C33)

**Comment by tpoole** [comment]
Hi Zac,

We've already fixed this on the `develop` branch. See here for more info: https://forum.juce.com/t/systemstats-getoperatingsystemtype-assertion-fails-on-macos-11-1/43251
