### ISSUE TITLE
CMake cannot find JUCE after apt install juce-tools

### ISSUE THREAD

**Issue by gvcallen** [juce-framework/JUCE#818]
I'm not sure if I'm doing something wrong (as I am new to the Linux community in general) but after running _sudo apt install juce-tools_, on Ubuntu, CMake is unable to find JUCE using find_package (the exact same CMake code works perfectly on my WIndows PC so it can't by my CMakeLists.txt file).

Specs:
- Ubuntu 20.04
- CMake 3.16.3

Repro:
- Install CMake using sudo apt install CMake
- Install JUCE using sudo apt install juce-tools
- Create a simple CMakeLists.txt file and call find_package(JUCE CONFIG REQUIRED)
- Note the message from CMake that JUCE could not be found

Additional info:
On my Windows machine, to get CMake finding JUCE, I simply placed the JUCE install in my CMAKE_PREFIX_PATH folder and followed the CMake build instructions on the GitHub help page. I could do the same on Linux, however I prefer to install my packages and libraries on Linux using apt.

EDIT: After searching my computer for JUCEConfig.cmake, no file could be found. Should this not have been copied during the apt installation?

**Comment by McMartin** [comment]
The `juce-tools` apt package is not the official way of getting the JUCE code and is not maintained by the JUCE team.

AFAICS, the `juce-tools` apt package on Ubuntu 20.04 is providing JUCE 5.4.7, which doesn't have CMake support.

**Comment by gvcallen** [comment]
@McMartin That does make sense. What is the recommended path to install JUCE 6 then on my Ubuntu system?

**Comment by McMartin** [comment]
The same as on Windows.
