### ISSUE TITLE
VST3 Plugin bundle path invalid on Linux aarch64.

### ISSUE THREAD

**Issue by hfiguiere** [juce-framework/JUCE#819]
The VST3 Plugin bundle path is invalid on Linux aarch64.

According to:
https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3loc.html#linuxformat

It should be `Plugin.vst3/Contents/aarch64-linux/Plugin.so`

But the JUCE auto-detection makes it `arm64` instead of `aarch64`.

See: https://github.com/juce-framework/JUCE/blob/6f22faf29d769ffd7f2ec5eaa643a0da2a0c60b1/extras/Build/CMake/juce_runtime_arch_detection.cpp#L4

**Comment by hfiguiere** [comment]
The issue actually in `extras/Projucer/JuceLibraryCode/BinaryData.cpp` that is used to generate the helper.

I solve the problem by running this sed command before running Projucer:

```shell
sed -e s/arm64/aarch64/g -i extras/Build/CMake/juce_runtime_arch_detection.cpp extras/Projucer/JuceLibraryCode/BinaryData.cpp
```

**Comment by tpoole** [comment]
Thank you for reporting. This has been fixed in https://github.com/juce-framework/JUCE/commit/717774b6483d1a231eabc1fef2bc316721d429f5.
