### ISSUE TITLE
Add a function to return the number of added audioCallbacks

### ISSUE THREAD

**Issue by davens** [juce-framework/JUCE#825]
https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.h#L489

**Comment by davens** [comment]
Another idea would be to have: `bool isRegisteredForCallbacks(juce::AudioIODeviceCallback* callbackListener)`

**Comment by tpoole** [comment]
I've moved this feature request to the JUCE forum: https://forum.juce.com/t/add-a-function-to-return-the-number-of-added-audiocallbacks/50442
