### ISSUE TITLE
Projucer bug:   ComponentEditor ToggleButonHandler missing "juce::"  in code generation of the enumeration 

### ISSUE THREAD

**Issue by sukoi26** [juce-framework/JUCE#826]
Must be:    juce::dontSendNotification 

https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/extras/Projucer/Source/ComponentEditor/Components/jucer_ToggleButtonHandler.h#L88

**Comment by ed95** [comment]
https://github.com/juce-framework/JUCE/pull/842#issuecomment-770790251
