### ISSUE TITLE
DemoRunner 6.05: cursor hidden 

### ISSUE THREAD

**Issue by sukoi26** [juce-framework/JUCE#827]
1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code
1a)select DemoRunner utlities javascript
1b) mouse down in texteditor demo
1c) change to see code tab code
1d) come back to demo tab
1)no cursor
in case of text selection same behavior 

  2) the expected behaviour
retrieve the cursor at  the same location

  3) the operating system Window 10x64  / Linux x64

![image](https://user-images.githubusercontent.com/23014567/104387377-3bd04800-5537-11eb-920d-ec1204adcd55.png)

**Comment by Archie3d** [comment]
The `juce::CodeEditorComponent` component has a bug when handling look-and-feel change:
```cpp
void CodeEditorComponent::lookAndFeelChanged()
{
    caret.reset (getLookAndFeel().createCaretComponent (this));
}
```
It resets the caret but does not add it to the component hierarchy, which is causing the caret component having no parent, and so it never gets painted. The correct code should be:

```cpp
void CodeEditorComponent::lookAndFeelChanged()
{
    caret.reset (getLookAndFeel().createCaretComponent (this));
    addAndMakeVisible (caret.get());
}
```

This will also make redundant the call to `addAndMakeVisible` call in `CodeEditorComponent` constructor.

**Comment by ed95** [comment]
Thanks for reporting. This has now been fixed on the `develop` branch here https://github.com/juce-framework/JUCE/commit/bcb85bc752f6fce28c50abe22cfa5baf853eee74
