### ISSUE TITLE
JUCE_BEGIN_IGNORE_WARNINGS_GCC_LIKE is incompatible with "-Weverything"

### ISSUE THREAD

**Issue by danra** [juce-framework/JUCE#843]
On Clang, switching some manually written blocks:
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"
...
#pragma clang diagnostic pop
```

with 
```
JUCE_BEGIN_IGNORE_WARNINGS_GCC_LIKE("-Weverything")
...
JUCE_END_IGNORE_WARNINGS_GCC_LIKE
```

Stopped ignoring warnings as expected. The root cause seems to be `JUCE_BEGIN_IGNORE_WARNINGS_GCC_LIKE` expects `__has_warning("-Weverything")` to be true, and it isn't, probably because `-Weverthing` isn't considered a *real* warning (not specified in https://clang.llvm.org/docs/DiagnosticsReference.html, and documented elsewhere as a special case).

Would be nice to have the JUCE macro work with this even though `__has_warning("-Weverything")` is false, to be able to more easily suppress all warnings from external headers, for instance.

**Comment by tpoole** [comment]
I'd prefer that we didn't add special-casing to any particular compiler flags. Though a bit awkward, once you've disabled all the individual warnings they are unlikely to change, so this shouldn't be a continuous effort. You would also be notified if newer compilers pick up additional problems, which might be useful.

**Comment by tpoole** [comment]
We want to retain the ability to suppress warning flags that are only present on newer compilers, without introducing additional warnings on older compilers
