### ISSUE TITLE
Write access violation in AudioDeviceManager

### ISSUE THREAD

**Issue by Ogudikov** [juce-framework/JUCE#851]
1) Steps to reproduce.
- clone repository (6.0.7)
- build Projucer using MS VS 2019 Community version
- create Audio project using just built Projucer, save and open IDE (MS VS 2019)
- build project and start in debug (F5 key)
- get exception
Exception thrown: write access violation.
**this** was 0x7FF66BB171E0.
![image](https://user-images.githubusercontent.com/11859567/106943911-a9cef000-672e-11eb-932a-a0c59413786c.png)

  3) the operating system  Windows 10 Enterprise  20H2
  4) the architecture (32-bit or 64-bit)   64bit
  5) a stack trace - if the bug causes a crash
>	AudioApp.exe!juce::AudioDeviceManager::scanDevicesIfNeeded() Line 434	C++
 	AudioApp.exe!juce::AudioDeviceManager::initialise(int numInputChannelsNeeded, int numOutputChannelsNeeded, const juce::XmlElement * xml, bool selectDefaultDeviceOnFailure, const juce::String & preferredDefaultDeviceName, const juce::AudioDeviceManager::AudioDeviceSetup * preferredSetupOptions) Line 243	C++
 	AudioApp.exe!juce::AudioAppComponent::setAudioChannels(int numInputChannels, int numOutputChannels, const juce::XmlElement * const xml) Line 70	C++
 	AudioApp.exe!MainComponent::MainComponent() Line 20	C++
 	AudioApp.exe!AudioAppApplication::MainWindow::MainWindow(juce::String name) Line 68	C++
 	AudioApp.exe!AudioAppApplication::initialise(const juce::String & commandLine) Line 28	C++
 	AudioApp.exe!juce::JUCEApplicationBase::initialiseApp() Line 297	C++
 	AudioApp.exe!juce::JUCEApplication::initialiseApp() Line 92	C++
 	AudioApp.exe!juce::JUCEApplicationBase::main() Line 256	C++
 	AudioApp.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 105	C++

**Comment by tpoole** [comment]
We're unable to reproduce this issue. Do you have an unusual audio device connected to your computer, or some other non-standard audio configuration?

**Comment by Ogudikov** [comment]
Head phones through audio out only. 
Usb hub in monitor Dell U2415 is recognized as sound device. But it is not used as such. I just disconnected it and tried. The issue persists.
Computer Nettop Asus Vivo VM65.

**Comment by tpoole** [comment]
OK, I was hoping that might be the key to things.

Unfortunately without being able to reproduce the problem it's difficult to say what might be going wrong. The best suggestion I have is to use the debugger to step though application start up until you see something amiss with the AudioDeviceManager. With these kinds of problems it might be something other than the AudioDeviceManager that's misfiring, but certainly the AudioDeviceManager is a sensible place to start looking.

**Comment by Ogudikov** [comment]
Ok. Thank you for advice.
