### ISSUE TITLE
Poor performance when moving a window, (Windows HIDPI with scaling)

### ISSUE THREAD

**Issue by Archie3d** [juce-framework/JUCE#855]
Hi,
I experience a very poor performance on Windows 10 when dragging a desktop window (`juce::DocumentWindow`) with native header enabled. The problem occurs on 4K display with 150% scaling. The window moves are sluggish, especially in Debug build.

This does not happen when native header is disables or scaling factor is set to 100%. The problem also does not manifest itself when a window constrainer is set to `nullptr`.

I've tracked the problem down to the `LRESULT handlePositionChanging (WINDOWPOS& wp)` implementation which is in `juce_win32_Windowing.cpp`

First of all it is not clear why constrain is applied to the current position and not the one received in the message:
```cpp
auto pos = ScalingHelpers::unscaledScreenPosToScaled (component, convertPhysicalScreenRectangleToLogical (rectangleFromRECT ({ wp.x, wp.y, wp.x + wp.cx, wp.y + wp.cy }), hwnd));
auto current = getCurrentScaledBounds();  // <---- Should we do current = pos here?

constrainer->checkBounds (pos, current,
                          Desktop::getInstance().getDisplays().getTotalBounds (true),
                          pos.getY() != current.getY() && pos.getBottom() == current.getBottom(),
                          pos.getX() != current.getX() && pos.getRight()  == current.getRight(),
                          pos.getY() == current.getY() && pos.getBottom() != current.getBottom(),
                          pos.getX() == current.getX() && pos.getRight()  != current.getRight());
```

And a second issue is the float/integer precision loss because of the window rectangle downscaling and upscaling (using the display scaling factor). This results in the `WINDOWPOS` to be updated by at least one pixel most of the time.

The following code change fixes the issue for me:

```cpp
auto pos = ScalingHelpers::unscaledScreenPosToScaled (component, convertPhysicalScreenRectangleToLogical (rectangleFromRECT ({ wp.x, wp.y, wp.x + wp.cx, wp.y + wp.cy }), hwnd));
const auto current = pos;

constrainer->checkBounds (pos, current,
                          Desktop::getInstance().getDisplays().getTotalBounds (true),
                          pos.getY() != current.getY() && pos.getBottom() == current.getBottom(),
                          pos.getX() != current.getX() && pos.getRight()  == current.getRight(),
                          pos.getY() == current.getY() && pos.getBottom() != current.getBottom(),
                          pos.getX() == current.getX() && pos.getRight()  != current.getRight());

if (current != pos)
{
    pos = convertLogicalScreenRectangleToPhysical (ScalingHelpers::scaledScreenPosToUnscaled (component, pos), hwnd);

    wp.x  = pos.getX();
    wp.y  = pos.getY();
    wp.cx = pos.getWidth();
    wp.cy = pos.getHeight();
}
```

**Comment by ed95** [comment]
Thanks for reporting, I was able to reproduce this but the proposed fix won't work. Assigning `current = pos` defeats the purpose of the constrainer `checkBounds()` call which compares the proposed new bounds from the `WINDOWPOS` structure to the current peer bounds retrieved using ` getCurrentScaledBounds()`. If `current == pos` then the constrainer won't be able to check the proposed bounds changes.

What we can do to prevent unnecessary move and resize events is to check whether the scaled bounds are within a rounding-error threshold and avoid setting `WINDOWPOS` in that case. We've added this in https://github.com/juce-framework/JUCE/commit/3d378d03846264d0e1ed7b9dc4bc438418a3fca9 and from my tests it seems to get rid of the spurious events being sent. Please let us know if it also fixes things for you.

**Comment by Archie3d** [comment]
It's all good now, thanks!
