### ISSUE TITLE
Support for external/system copies of dependencies

### ISSUE THREAD

**Issue by musicinmybrain** [juce-framework/JUCE#860]
The project bundles quite a few dependencies. The following is my best-effort list, based on JUCE 6.0.4:

- “Oboe”, https://github.com/google/oboe
- libogg
- libvorbis
- flac/libFLAC
- Core Audio Utility Classes
- VST3 SDK
- Box2D
- zlib
- “The Independent JPEG Group's JPEG software” / libjpeg
- libpng

Most Linux distributions, such as Fedora, are opposed to bundling [for various reasons](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries). In order to potentially package this software in Fedora, I am [required](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) to ask about a path to supporting builds with external or system copies of these libraries, and to record any response.

Is there any interest in providing a way to build with system copies of these libraries?

**Comment by tpoole** [comment]
I'm afraid we are not going to offer an official path for unbundling the libraries included in JUCE.
