### ISSUE TITLE
MidiKeyboardState::noteOn jassert check is incorrect

### ISSUE THREAD

**Issue by modosc** [juce-framework/JUCE#863]
`MidiKeyboardState::noteOn` allows 0 as a `midiChannel`:
https://github.com/juce-framework/JUCE/blob/b8206e3604ebaca64779bf19f1613c373b9adf4f/modules/juce_audio_basics/midi/juce_MidiKeyboardState.cpp#L45
but it then calls `MidiMessage::noteOn` which requires `midiChannel > 0`
https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/modules/juce_audio_basics/midi/juce_MidiMessage.cpp#L595

**Comment by ed95** [comment]
Thanks for reporting, we've fixed this in https://github.com/juce-framework/JUCE/commit/ba2027497b348a7fbe14f89cfde6666cb963983c.
