### ISSUE TITLE
URL::launchInDefaultBrowser truncates Query String after ampersand in Linux

### ISSUE THREAD

**Issue by ZioGuido** [juce-framework/JUCE#866]
If the query string contains more than one parameter, everything is truncated after the first ampersand syumbol:

```
URL w("https://www.mysite.com/?parameter1=value&parameter2=value");
w.launchInDefaultBrowser();
```

This opens only: `https://www.mysite.com/?parameter1=value`

I found the problem in the function `Process::openDocument (const String& fileName, const String& parameters)` in the file  **/modules/juce_core/native/juce_linux_Files.cpp** and the cause is the fact that the URL (in String format) is passed to bash command as argument, but the ampersand is a control symbol used by bash, so the query string is truncated and the rest of the command produces errors.

The fix is to add `.quoted()` to the line # 206 so that it changes from:

`cmdLines.add (String (browserName) + " " + cmdString.trim();`

to:

`cmdLines.add (String (browserName) + " " + cmdString.trim().quoted());`

This way, the argument to the bash command is passed between quotes and the ampersand in the query string is not seen as a bash control symbol.

**Comment by ed95** [comment]
Thanks for reporting! We've added a fix for this to `develop` in https://github.com/juce-framework/JUCE/commit/fe9493867ede4eec22087a80717c47e8d28ae6b1.
