### ISSUE TITLE
Cannot scan / initiate 3rd-party AU plugins when opening macOS app from command line other than Terminal.app

### ISSUE THREAD

**Issue by deermichel** [juce-framework/JUCE#872]
System: macOS Big Sur 11.2.3
JUCE v6.0.7 (also on current develop branch)

I'm creating a JUCE GUI application (a kind of plugin host) and use the PluginDirectoryScanner to scan for existing AU plugins on a macOS system. When developing, I usually start the executable right from the terminal to see the stdout logs (e.g. `./bundle.app/Contents/MacOS/executable`). Doing so yields only plugins which are shipped with macOS (the ones by Apple), whereas if I start the bundle.app by double-clicking it, all AU plugins will be found (Apple stock ones + 3rd-party). If I try to create an instance of a 3rd-party plugin when the application was started via terminal, it fails with `No compatible plug-in format exists for this plug-in`. This behavior is reproducible with the AudioPluginHost example shipped with JUCE.

**Comment by reuk** [comment]
Which terminal app are you using to run your program? If you haven't tried launching your app from `Terminal.app` it might be worth trying that. `auval` will only find all Audio Units when launched from `Terminal.app`, and can only find Apple plugins when launched from a third-party terminal such as iTerm. Perhaps the behaviour is similar for other command-line apps which load Audio Units.

**Comment by deermichel** [comment]
Wow, how did you find that out 😅 ? Yes, I was using iTerm and can confirm that it works as expected with the Apple Terminal. It also seems to work within the VS Code console. However, this brings up the next question... why does it behave that way and is there something we can do about it?

**Comment by reuk** [comment]
Unfortunately I'm not sure why third-party terminal apps seem to hide third-party audio units, and I'm not aware of any workarounds (other than using the built-in Terminal.app).

**Comment by deermichel** [comment]
I might have found a workaround for iTerm: [Turning off Prefs/Advanced/Allow sessions to survive logging out and back in](https://stackoverflow.com/questions/56993800/some-audio-unit-code-incl-auval-does-not-work-in-iterm). But I'm really interested why this option influences the behavior of `auval`. At least, doesn't look like a JUCE issue.

(ref: https://developer.apple.com/forums/thread/117695)
