### ISSUE TITLE
JUCE_BUILD_EXTRAS=ON doesn't install extras, only builds them?

### ISSUE THREAD

**Issue by yurivict** [juce-framework/JUCE#876]
I've built with ```-DJUCE_BUILD_EXTRAS:BOOL=ON```, it built Projucer, AudioPluginHost, etc. but didn't install them.

Is there another cmake option that installs them?

Version 6.0.8

**Comment by reuk** [comment]
No, there is no install configuration for the extras.

**Comment by yurivict** [comment]
Ok, thanks.
