### ISSUE TITLE
bad xcode project (Projucer 6.0.8 regression !!!) if Post Build script has specific string

### ISSUE THREAD

**Issue by devnull0000** [juce-framework/JUCE#884]
All you need to get a non working Xcode project (which cannot be opened) is to add to "Post-Build Shell Script" section a string in form  #word "another_word_in_quotes"
that's it. it becomes broken. See the screenshot:
<img width="1051" alt="broken_xcode" src="https://user-images.githubusercontent.com/6594616/112886373-86934200-90da-11eb-8dec-2c78823a3e79.png">

It is very confusing because I just had in .projucer file last string of the shell script commented out and failed to understand why Projucer became completely broken for one project while still working for another. 

This appeared with 6.0.8 version, works fine in 6.0.7 I suspect it is one of the commits:
https://github.com/juce-framework/JUCE/commit/882be260692486cedec64f31718a06ed3e4e5bad
or
https://github.com/juce-framework/JUCE/commit/2ef9899818c4888e6a4d70b96d684989be589e2d

but I'm lazy to try to revert them and build.

I attach the most basic hello world non-working project.
[bad_xcode.zip](https://github.com/juce-framework/JUCE/files/6223904/bad_xcode.zip)

**Comment by ed95** [comment]
Thank you for reporting. This has been fixed on the `develop` branch in https://github.com/juce-framework/JUCE/commit/282ad8fa9c8a1ebd744d1ec971e727f2d5206ba2.
