### ISSUE TITLE
TextEditor issues

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#888]
Hello,

it seems that recent changes in the JUCE TextEditor's code have broken UI (I suspect commit 7c96f1866320d166588973ba7bf1d3f608027a07 )

- When not using multiline with fixed bounds, the text will not follow the caret position, which leads to not seeing text outside of the editor's bounds, it's only showing the first part of the text -> This is even visible in the Projucer, any non-multiline field has this problem
- When using multiline and trying to adapt the bounds of the parent component to the size of the edited text, textEditor.getTextWidth() returns its given size, whereas it used to return the theoretical size (no wordwrap). Is there another way of automatically adjusting the size component to its child texteditor depending on the its content ?

mainly testing on Windows 10 but exporting on all platform (macOS, linux x64, raspberry) with same behaviour, working on develop branch

**Comment by ed95** [comment]
Thanks for reporting. This should be fixed on the `develop` branch in https://github.com/juce-framework/JUCE/commit/a533e86044e9db3cbc097b1b5af93a26f83c4e8e.
