### ISSUE TITLE
SnapToZero never called in juce::dsp filters

### ISSUE THREAD

**Issue by xlbly** [juce-framework/JUCE#889]
Since c138bf91b4, the snapToZero method in dsp filters is never called on macOS and iOS, because of an erroneous preprocessor directive.

For example, in StateVariableFilter.h:

```
#if JUCE_SNAP_TO_ZERO
snapToZero();
#endif
```

Unless I'm missing something, the condition is never true, it should be changed to:

```
#if JUCE_DSP_ENABLE_SNAP_TO_ZERO
snapToZero();
#endif
```

or

```
#ifdef JUCE_SNAP_TO_ZERO
snapToZero();
#endif
```

**Comment by reuk** [comment]
Thanks, this should be resolved by this commit: https://github.com/juce-framework/JUCE/commit/c3a98d44c5d6c167d9450704a26c1c913fab03d1
