### ISSUE TITLE
Build error when building the examples of the plugins category

### ISSUE THREAD

**Issue by MINDoSOFT** [juce-framework/JUCE#890]
Hi there !

I am trying to run the examples under the plugins category.

![image](https://user-images.githubusercontent.com/890368/115040289-f165bb00-9ed9-11eb-8203-395a9ec226d5.png)

And I am using Windows 10, Visual Studio 2019 version 16.9.4, and x64 architecture.

But when I try to build the example project I get the following **build error**

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3025	The source file "x64\Debug\Shared Code\\" is actually a directory.  The "Copy" task does not support copying directories.	MIDILogger_SharedCode	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	1480	
```

This problem does not appear with example projects of other categories e.g. the audio category.
![image](https://user-images.githubusercontent.com/890368/115040683-5a4d3300-9eda-11eb-9a0d-99a3d56fe151.png)

Has anyone else faced this build error and how did you overcome it ?

Thank you for your time and effort !

**Comment by ed95** [comment]
This appears to be a bug in the latest version of Visual Studio, see [this forum thread](https://forum.juce.com/t/projucer-6-0-8-and-vs-16-9-4-error/45514/) for more information and some potential workarounds.

**Comment by MINDoSOFT** [comment]
Thank you for your instant reply! Have a great day. :)
