### ISSUE TITLE
No audio from SamplerPluginDemo Example in Legacy MPE mode

### ISSUE THREAD

**Issue by DBraun** [juce-framework/JUCE#893]
I'm using the SamplerPlugin Demo with an old MIDI controller, not MPE. With legacy mode enabled I still don't hear audio.

![image](https://user-images.githubusercontent.com/2096055/115974864-bb958780-a514-11eb-9fdf-d1547c7133c6.png)

1) I compiled the plugin:
`cmake --build cmake-build --target DemoRunner`
`cmake . -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON`
Built with Visual Studio 2019
  2) I expect to hear audio, but I don't. I can use MIDI and I see the animation of the sample being played, but I don't hear audio. I can use the Test Audio to hear the standard sine tone.
  3) Windows 10
  4) 64-bit
  5) Stack trace: N/A
  6) Standalone and VST3 don't work. Haven't tested others.
  7) Ableton Live and standalone

In order to hear audio I have to change this line https://github.com/juce-framework/JUCE/blob/90e8da0cfb54ac593cdbed74c3d0c9b09bad3a9f/examples/Plugins/SamplerPluginDemo.h#L275

from 
```level    .setTargetValue (currentlyPlayingNote.pressure.asUnsignedFloat());```

to
```level    .setTargetValue (currentlyPlayingNote.noteOnVelocity.asUnsignedFloat());```

Same issue as https://forum.juce.com/t/samplerplugin-demo-no-audio/32584

**Comment by szarvas** [comment]
Thank you for reporting this. We added a change to how the voice volumes are calculated in [61619ec0](https://github.com/juce-framework/JUCE/commit/61619ec0d52ac79e3d5d57674b80161096fb6dc1) so now you should hear sound even with plain MIDI devices. This change is not related to the MPE legacy mode, so you should hear the sound with either setting.
