### ISSUE TITLE
MemoryBlock::replaceWith doesn't handle size 0 correctly

### ISSUE THREAD

**Issue by polyspectral** [juce-framework/JUCE#894]
When passed data of size 0, MemoryBlock::replaceWith does nothing at all.

The expected behavior is to clear the MemoryBlock.

**Comment by ed95** [comment]
`replaceWith()` should only be used to replace the contents of the `MemoryBlock` with some valid data - the docs state:

```
Resizes this block to the given size and fills its contents from the supplied buffer.
The data pointer must not be null.
```

If you want to clear the block, you can use `reset()` or `setSize (0)`.

**Comment by polyspectral** [comment]
Are you sure?

Please note I'm not talking about a null pointer, I'm talking about data of length 0, which is treated as perfectly valid by most C/C++ APIs, including other methods in JUCE which take a pointer and a length as parameters (e.g. in Array, String).

Consider this example:

`void FillWithString(MemoryBlock& block, const String& string)
{
    block.replaceWith(string.toRawUTF8(), string.getNumBytesAsUTF8());
}`

Is the behavior "fills the contents of block with string encoded as UTF8, except if string is empty, in which case block is untouched" really what you'd expect? And is it helpful to have to treat this case separately? Why should MemoryBlock be inconsistent with Array, String, etc. in this regard?

**Comment by ed95** [comment]
Ah I see what you mean now, sorry. Yes the behaviour of `replaceWith()` is slightly confusing but we don't want to break existing code that may be relying on this. We've added a new `replaceAll()` method to `develop` in https://github.com/juce-framework/JUCE/commit/433750941be00972957a2a1ab919173ba58a450f which will behave this way and deprecated the old method to encourage people to use this new one whilst preserving behaviour.

Thanks for reporting!
