### ISSUE TITLE
MidiBuffer only accepts messages to a max size of 64k each, else corrupts memory

### ISSUE THREAD

**Issue by christofmuc** [juce-framework/JUCE#898]
The MidiBuffer seems to be built around the assumption that no MidiMessage has a RAW size bigger than 64k, if we look at juce_MidiBuffer.cpp:

`void MidiBuffer::addEvent (const void* newData, int maxBytes, int sampleNumber)
{
    auto numBytes = MidiBufferHelpers::findActualEventLength (static_cast<const uint8*> (newData), maxBytes);

    if (numBytes > 0)
    {
        auto newItemSize = (size_t) numBytes + sizeof (int32) + sizeof (uint16);
        auto offset = (int) (MidiBufferHelpers::findEventAfter (data.begin(), data.end(), sampleNumber) - data.begin());

        data.insertMultiple (offset, 0, (int) newItemSize);

        auto* d = data.begin() + offset;
        writeUnaligned<int32>  (d, sampleNumber);
        d += sizeof (int32);
        writeUnaligned<uint16> (d, static_cast<uint16> (numBytes));
        d += sizeof (uint16);
        memcpy (d, newData, (size_t) numBytes);
    }
}
`
The culprit is the static_cast<uint16> of the numBytes, which might be bigger than you expect.

However, there is neither documentation about this behavior nor any asserts/checks that tell you when you're doing something stupid. 

I would assume the documentation states that somewhere (couldn't find it), or the addEvent asserts at least. Would even be better it would allow larger sizes, but I can work around this I think. 

In my case, I use MidiBuffers to aggregate sysex data to be sent out to a HW synth, and believe it or not some of these can grow beyond 64k.

**Comment by reuk** [comment]
Thanks for the suggestion, I've updated `addEvent` so that it can report success or failure: https://github.com/juce-framework/JUCE/commit/a7ce9aab9850193bd4e29dd202d5ad8cc1baefd6
