### ISSUE TITLE
MPE is broken in VST host

### ISSUE THREAD

**Issue by benkuper** [juce-framework/JUCE#899]
Hello,
I've been working on the develop branch of JUCE and noticed that my latest versions of my DAW ( http://benjamin.kuperberg.fr/lgml ) is not working with Seaboard and ROLI Studio Player.

I have then tested the AudioPluginHost example :
 - JUCE develop branch from april 7th => working (MPE is behaving as expected and works inside ROLI studio player loaded vst)
 - JUCE develop branch from april 20th => not working anymore

I'm sorry I don't have more insight right now, but something broke the MPE handling between those 2 dates. I'll try and investigate further and add infos here.

**Comment by benkuper** [comment]
UPDATE :
after testing every commit in this range, I found out that the commit where this gets broken is 9f03bbc358d67a3e0d0e3d7082259a4155aebd85

This commit has quite a lot going on so I'm not sure if I'll be able to find out exactly what makes the MPE break but I hope it helps !

**Comment by reuk** [comment]
Thanks, I can reproduce the issue, and applying the following patch seems to resolve the problem. Could you give this a go and confirm whether it fixes the issue for you? If it does, I'll get this merged asap.

```
From 02ab983a903f9a05e60605956f6204d081518653 Mon Sep 17 00:00:00 2001
From: reuk <reuk@users.noreply.github.com>
Date: Sun, 2 May 2021 14:06:50 +0100
Subject: [PATCH] VST3 hosting:  Fix issue where MIDI controller changes were
 not propagated to plugins

---
 .../format_types/juce_VST3PluginFormat.cpp                  | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp b/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp
index 771d7c935..acf41abca 100644
--- a/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp
+++ b/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp
@@ -2450,12 +2450,12 @@ public:
         for (int i = getTotalNumInputChannels(); i < buffer.getNumChannels(); ++i)
             buffer.clear (i, 0, numSamples);
 
+        inputParameterChanges->clear();
+        outputParameterChanges->clear();
+
         associateWith (data, buffer);
         associateWith (data, midiMessages);
 
-        inputParameterChanges ->clear();
-        outputParameterChanges->clear();
-
         cachedParamValues.ifSet ([&] (size_t index, float value)
         {
             inputParameterChanges->set (cachedParamValues.getParamID (index), value);
-- 
2.31.1
```

**Comment by benkuper** [comment]
yep, it works !

**Comment by benkuper** [comment]
Wait ! now I get a lot of exception when pluggin my seaboard to the VST.
If I connect another non-MPE midi device it's actually ok, but as soon as I'm sending midi from the Mpe, I get this error (win 10 x64) : 

Exception thrown at 0x00007FF78BFFD08C in LGML.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
Exception thrown at 0x00007FF931D34B59 (KernelBase.dll) in LGML.exe: 0x80010105: The server threw an exception.
Exception thrown at 0x00007FF931D34B59 (KernelBase.dll) in LGML.exe: 0x40080202: WinRT transform error (parameters: 0x0000000080010105, 0x0000000000000000, 0x0000000000000027, 0x0000003AFEAFF100).

The program is not breaking so not sure what it is. I'll try and find more info

**Comment by reuk** [comment]
Thanks for reporting. Should be fixed in https://github.com/juce-framework/JUCE/commit/15305e69af41f1b3b15ebb62f472f383eaeafc01
