### ISSUE TITLE
Modify juce_AudioProcessor.h and juce_VST3_Wrapper.cpp to allow registering custom VST3 interfaces + provide user AudioProcessor with "hostContext" pointer

### ISSUE THREAD

**Issue by GavinRay97** [juce-framework/JUCE#902]
# Overview 
Following several weeks of discussion with @reuk in the Discord server.

- VST2 has `hostCallback`, `canDo()` and `effVendorSpecific()` for defining custom and/or host-specific behavior
- VST3 uses COM-like `queryInterface()` instead, setting an `in` pointer value to class instances that implement interfaces
- JUCE provides support for custom VST2 functionality, but VST3 is limited to the classes + interfaces hardcoded in `juce_VST3_Wrapper.cpp`

**Personal usecase:**
- REAPER has both a VST2 and VST3 implementation that allow you to embed your plugin UI in tracks/mixers, and to interact with REAPER's C++ API.
- I'd really like to be able to provide a generic utility library to allow plugin authors to choose to enable UI embedding in REAPER (and to interact with the C++ API if they want).

It looks like this:

![image](https://user-images.githubusercontent.com/26604994/117744054-f286c100-b1d5-11eb-9b89-d4152f7e2942.png)

# Architecture

Reuk's idea was roughly:
- Add a function, `std::vector<std::pair<IID, T>> AudioProcessor::registerVst3Extensions(location)` that gets called on the user audio processor if it's implemented.
- Each component, `JuceVST3EditController`, `JuceVST3Component`, will call `pluginInstance->registerVst3Extensions()` passing a different `location` value to identify themselves
- The `registerVst3Extensions()` function should return the array of `IID <-> Class instance` pairs
- The results get added to an internal `std::unordered_map<IID, FUnknown*>`, and during `queryInterface()` the `targetIID` is checked for in the map + returned if exists.

# Implementation

Here's a working implementation that tries to be minimally invasive, as conversation starter.
I don't really have a clue what I'm doing with C++ so bear with me here.

**Also I want to acknowledge that I bugged a lot of people in the process of figuring this out.**
Credit, and sincerest thanks to:
- Robbert van der Helm
	- Bunch of random questions, tip about `FUnknownPtr<T>` for casting between VST3 interfaces
- Xenakios
	- Tips on REAPER specific stuff he had learned
- baconpaul from the Surge synth team
	- Many C++ and VST3 questions
- Reuk
	- A lot (most of?) the feedback and questions, came up with the architecture
- Ben Vining
	- Misc feedback, code for the static/thread-local singleton audio processor pointer
- Schwa from Cockos
	- Helping me debug & telling me what REAPER was seeing
	- Sharing the section of REAPER code that does the `queryInterface()` for `IReaperUIEmbed` and then calls the `embed_message()`
	- Patching the VST3 interface to fix a small issue then releasing, a day after reporting a bug

## `juce_AudioProcessor.h`
```cpp
class JUCE_API  AudioProcessor
{
public:
#ifdef JUCE_VST3_ENABLE_PASS_HOST_CONTEXT_TO_AUDIO_PROCESSOR_ON_INITIALIZE
    #include "utility"
    #include "vector"

    using SteinbergFUnknown = void; // Opaque, cast to FUnknown in userland
    virtual void handleVST3HostContext(SteinbergFUnknown* /* hostContext */) {}

    enum VST3InterfaceInstallLocation { Component, EditController };

    using FUID_ = void;
    using VST3Interface = void;

    virtual std::vector<std::pair<FUID_*, VST3Interface*>> getVST3ExtensionsForInterface(VST3InterfaceInstallLocation /* location */) {
        return std::vector<std::pair<FUID_*, VST3Interface*>>();
    };
#endif
```

## `PluginProcessor.cpp`
```cpp
using SteinbergFUnknown = void;

void MyPluginAudioProcessor::handleVST3HostContext(SteinbergFUnknown* hostContext)
{
    // Credit: Robbert van der Helm (https://github.com/robbert-vdh)
    auto reaper = FUnknownPtr<IReaperHostApplication>(static_cast<Steinberg::FUnknown*>(hostContext));
    auto showConsoleMsg = static_cast<void (*)(const char* msg)>(reaper->getReaperApi("ShowConsoleMsg"));
    showConsoleMsg("Test from IReaperHostApplication");
}

using FUID_ = void;
using VST3Interface = void;

std::vector<std::pair<FUID_*, VST3Interface*>>
MyPluginAudioProcessor::getVST3ExtensionsForInterface(VST3InterfaceInstallLocation location)
{
    switch (location) {
    case EditController:
        return std::vector<std::pair<FUID_*, VST3Interface*>>({
            {
                const_cast<FUID*>(&IReaperUIEmbedInterface::iid),
                static_cast<VST3Interface*>(new ReaperVST3EditController(this))
            }
        });
    default:
        return std::vector<std::pair<FUID_*, VST3Interface*>>();
    }
}
```

## `juce_VST3_Wrapper.cpp`
```cpp
std::string tuidToFUIDString(const TUID iid) {
    const auto targetFUID = FUID::fromTUID(iid);
    char tmpBuf[128];
    targetFUID.toString(tmpBuf);
    return std::string(tmpBuf);
}

class VST3InterfaceContainer {
public:
  using TUIDRegString = std::string;
  std::unordered_map<TUIDRegString, Steinberg::FUnknown*> vst3InterfaceMap;

  static std::string fuidToRegistryString(const FUID& iid) {
    char iidBuf[126];
    iid.toRegistryString(iidBuf);
    return std::string(iidBuf);
  }

  template<class T>
  void registerInterface(const FUID& iid, T klazz) {
    jassert (klazz != nullptr);
    this->vst3InterfaceMap[fuidToRegistryString(iid)] = static_cast<FUnknown*>(klazz);
  }

  Steinberg::FUnknown* findInterface(const FUID& iid) {
    auto klazz = this->vst3InterfaceMap[fuidToRegistryString(iid)];
    if (klazz != nullptr)
        return klazz;
    return nullptr;
  }
};

// Credit: Ben Vining
struct AudioProcessorInitializerHelper
{  
    inline static juce::ThreadLocalValue<juce::AudioProcessor*> lastProcessorCreated;

    static void JUCE_CALLTYPE setLastCreatedAudioProcessor (juce::AudioProcessor* p) {
        lastProcessorCreated =  p;
    }

    static juce::AudioProcessor* JUCE_CALLTYPE getLastCreatedAudioProcessor () {
        return lastProcessorCreated.get();
    }
};

//==============================================================================

class JuceVST3EditController : // ...
                               public VST3InterfaceContainer
{
public:
    JuceVST3EditController (Vst::IHostApplication* host)
    {
        if (host != nullptr)
            host->queryInterface (FUnknown::iid, (void**) &hostContext);

      auto pluginInstance = AudioProcessorInitializerHelper::getLastCreatedAudioProcessor();
      if (pluginInstance == nullptr) return;

      for (auto it : pluginInstance->getVST3ExtensionsForInterface(AudioProcessor::VST3InterfaceInstallLocation::EditController)) {
        auto [fuidVoidPtr, vst3Interface] = it;
        const auto fuidPtr = static_cast<FUID*>(fuidVoidPtr);
        this->registerInterface(*fuidPtr, vst3Interface);
      }
    }

    //==============================================================================

    tresult PLUGIN_API queryInterface (const TUID targetIID, void** obj) override
    {
        TEST_FOR_AND_RETURN_IF_VALID (targetIID, FObject)
        TEST_FOR_AND_RETURN_IF_VALID (targetIID, JuceVST3EditController)
		// ... etc
		
        auto klazz = this->findInterface(FUID::fromTUID(targetIID));
        if (klazz != nullptr)
        {
            klazz->addRef();
            *obj = klazz;
            return Steinberg::kResultOk;
        }

        if (doUIDsMatch (targetIID, JuceAudioProcessor::iid))
        {
            audioProcessor->addRef();
            *obj = audioProcessor;
            return kResultOk;
        }

        *obj = nullptr;
        return kNoInterface;
    }

    // ...
}

//==============================================================================

class JuceVST3Component : // ...
                          public VST3InterfaceContainer
{
public:
    JuceVST3Component (Vst::IHostApplication* h)
      : pluginInstance (createPluginFilterOfType (AudioProcessor::wrapperType_VST3)),
        host (h)
    {
        //  etc...
        pluginInstance->setPlayHead (this);

        AudioProcessorInitializerHelper::setLastCreatedAudioProcessor(pluginInstance);
        for (auto it : pluginInstance->getVST3ExtensionsForInterface(AudioProcessor::VST3InterfaceInstallLocation::Component)) {
          auto [fuidVoidPtr, vst3Interface] = it;
          const auto fuidPtr = static_cast<FUID*>(fuidVoidPtr);
          this->registerInterface(*fuidPtr, vst3Interface);
        }
    }
}
```

![](https://i.imgur.com/7hQQlCt.png)

**Comment by sandy999999** [comment]
That Reaper theme is absolutely gorgeous tho. Care to upload it?

**Comment by GavinRay97** [comment]
I will trade one REAPER theme in exchange for `reuk`'s finished implementation of this being reviewed and merged 😂 

Jk, here u go friend
https://forum.cockos.com/showthread.php?t=230905

The color palette I used with it is attached here at the bottom of the post, both as a normal color palette and as an SWS color pallete:
https://forum.cockos.com/showpost.php?p=2414850&postcount=37

![](https://i.imgur.com/cGABCezh.png)

**Comment by sandy999999** [comment]
Haha :) Thanks alot bud

**Comment by reuk** [comment]
I've merged this feature now. An example of the functionality can be found in the `ReaperEmbeddedViewPluginDemo`: https://github.com/juce-framework/JUCE/commit/4b0b245b55429b33a638ccea94aaa300baf5d524

Please try this out and let us know if you run into any problems. For now I'm going to close this issue, but I'll reopen it if you report any issues.

**Comment by GavinRay97** [comment]
REUK MVP!!!

**Comment by nofishonfriday** [comment]
Thanks for this.
Currently checking it out and I noticed I can trigger an assertion failure with the stock example code when resizing Reaper's mixer (see gif).
Though I'm not sure if the example plugin code is meant to take care of these details or is just meant as a basic starting point.
Thought I'll let you know anyway, just in case...

![ReaperEmbedded](https://user-images.githubusercontent.com/7658194/121789455-6998e600-cbd6-11eb-981f-41fb1c812c9b.gif)

**Comment by reuk** [comment]
Thanks for reporting these assertions, the issue should be fixed here: https://github.com/juce-framework/JUCE/commit/7020495a4e605a511082cc1c69f0f53d0a9b960e
