### ISSUE TITLE
VST3 plugins made with JUCE 6.0.8 do not support frame rates of 29.97 and 29.97df

### ISSUE THREAD

**Issue by chancesend** [juce-framework/JUCE#906]
**Steps to reproduce:**

1. Use JUCE 6.0.8 to create a VST3 plugin that calls getCurrentPosition() from the playhead:

```
void MyPluginProcessor::processBlock(AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    ...
   AudioPlayHead::CurrentPositionInfo currentPosition;
    auto playHead = this->getPlayHead();
    if (playhead)
        this->getPlayHead()->getCurrentPosition(currentPosition);
}
``` 
2. Load up the plugin in a VST3 host that supports framerates, such as Nuendo.
3. Set the frame rate setting of the VST3 host to 29.97.
4. Set a breakpoint after the call to `getCurrentPosition()` and start playback.

**Expected behavior:**
The `currentPosition.frameRate` member variable is equal to AudioPlayHead::fps2997.

**Actual behavior:**
The `currentPosition.frameRate` member variable is equal to AudioPlayHead::fps30.

**Plugin format:**
VST3

**DAW observed in:**
Nuendo 10.3.

Bug also seen in the latest develop branch of JUCE.

**Comment by chancesend** [comment]
Pull request which fixes the issue:
https://github.com/juce-framework/JUCE/pull/905

**Comment by reuk** [comment]
Thanks for reporting. This issue should be resolved by https://github.com/juce-framework/JUCE/commit/77ad8b23bb01bcf23339ef812fdab30ce4757b53
