### ISSUE TITLE
Memory leak in WebBrowserComponent on Mac

### ISSUE THREAD

**Issue by OskarSigvardsson** [juce-framework/JUCE#907]
Hello Juce:ers!

I was reading the source code for WebBrowserComponent, and I thought this thing looked very suspicious: https://github.com/juce-framework/JUCE/blob/90e8da0cfb54ac593cdbed74c3d0c9b09bad3a9f/modules/juce_gui_extra/native/juce_mac_WebBrowserComponent.mm#L275

To me, that sure looks like a heap-allocated object that is never cleaned up. I admittedly don't know a lot about Objective-C, so I thought that it might be possible that either the webView took ownership of the object, or maybe that Xcode did some magic ARC thing, even though that looks like a raw C pointer (I don't know enough about how ownership works in Objective-C to know how that works). 

However, the memory debugger in Xcode seems to agree with me. If I create a new project and a single WebBrowserComponent and turn on the memory debugger, you get this: 

<img width="1539" alt="Screenshot 2021-06-04 at 15 28 39" src="https://user-images.githubusercontent.com/7059777/120808855-c7c82800-c549-11eb-9ded-780318d41c9d.png">

Same thing in Instruments: 

<img width="858" alt="Screenshot 2021-06-04 at 15 31 46" src="https://user-images.githubusercontent.com/7059777/120809058-fe9e3e00-c549-11eb-99a5-e86aa11bb293.png">

So I do think this is in fact a genuine leak. I think the rest of the leaked objects are part of the WKWebViewConfiguration, but I'm not sure.

**Comment by ed95** [comment]
Thanks for the report. We can avoid using the `WKWebViewConfiguration` altogether, I've added this to `develop` in https://github.com/juce-framework/JUCE/commit/27ead031c0570b1fe4a4045bd7c2ae28cc014856.
