### ISSUE TITLE
Uncompilable function in GenericInterpolator

### ISSUE THREAD

**Issue by SamuelBeland** [juce-framework/JUCE#910]
Trying to compile any interpolator will fail if the function `GenericInterpolator::processAdding(double, const float*, float*, int, int, int, float)` is used.

The compilation error occurs in the function `GenericInterpolator::interpolateAdding(double, const float*, float*, int, int, int, float)` :

```cpp
*output++ += gain * InterpolatorTraits::valueAtOffset ((float) pos);
```

No interpolator traits defines `valueAtOffset()` with a single argument.

**Comment by reuk** [comment]
Thanks for reporting, I've fixed this issue here: https://github.com/juce-framework/JUCE/commit/03b86d3fb881784ca7161262b4381572c6df5a6a
