### ISSUE TITLE
Plug-in Editor Window Resizing via Child AffineTransform Using OpenGLContext Breaks with Develop Commit f73f8ee

### ISSUE THREAD

**Issue by TimArt** [juce-framework/JUCE#914]
## Bug Description
_A code example is included at the bottom of this post._

To resize my entire `PluginEditor` window so that it scales all components uniformly, the editor has a child component (`childUIContainer`) containing the entire UI which gets scaled using an AffineTransform. When the actual PluginEditor window gets `resized()`, I manually call `childUIContainer.setTransform (juce::AffineTransform().scaled (zoomFactor));` where `zoomFactor` is calculated based on the width of the `PluginEditor` window.

Additionally, my plugin chooses to render JUCE painting using OpenGL, so I attach an OpenGLContext to the `childUIContainer`. I specifically chose to attach the OpenGLContext to the `childUIContainer` instead of the entire `PluginEditor` because, if my memory serves correct, I remember seeing a JUCE forum post where Fabian (@hogliux) had said attaching the OpenGLContext to the `PluginEditor` would cause glitches in plugins and, instead, the OpenGLContext should be attached to a child component of the `PluginEditor`. I cannot find this original post at the moment but will be searching for it.

At [this commit on develop](https://github.com/juce-framework/JUCE/commit/f73f8ee8497d2ec7f158226ecc0266e30cdb1ea3) f73f8ee8497d2ec7f158226ecc0266e30cdb1ea3, a bug was introduced which causes this method of UI resizing and GL rendering to produce unpredictable and inaccurate visual results. After resizing the UI, it remains in a state of visually repeating UI image patterns and fragmented UI layout.

**The bug specifically happens when all three conditions are present:** 
1. Resizing with the AffineTransform technique
2. OpenGL rendering of UI attached to a child of the editor
3. JUCE develop commit f73f8ee8497d2ec7f158226ecc0266e30cdb1ea3 and later

## Expected Behavior
When resizing, the Plug-in UI should scale uniformly. This is the behavior in JUCE commits prior to f73f8ee8497d2ec7f158226ecc0266e30cdb1ea3.

## Specs when Observing Bug
- Latest tested JUCE Develop commit: fe4ba9071be037bbed58268e1f4139f1dd23e15c (Jun 30, 2021)
- OS: MacOS 10.15.7
- IDE: Xcode 12.4
- Architecture: 64-Bit
- DAW: Ableton Live (no others tested)
- Plugin Format: Standalone and VST3 (AU untested)
- JUCE Graphics Rendering Method: OpenGL (OpenGL Context is attached to `childUIContainer`)

## Code Example
**UIContainer.h** - A child of the `PluginEditor` that contains the entirety of the UI and draws stuff
```cpp
#pragma once

#include <JuceHeader.h>

class UIContainer : public juce::Component
{
public:
    UIContainer() {}
    virtual ~UIContainer() {}
    
    // Draws some red rectangles to get scaled uniformly
    void paint (juce::Graphics & g) override
    {
        g.fillAll (juce::Colours::grey);
        g.setColour (juce::Colours::red);
        
        g.fillRect (100, 100, 20, 20);
        g.fillRect (100, 180, 80, 80);
        g.fillRect (200, 100, 20, 20);
        g.fillRect (200, 180, 80, 80);
    }
};
```

**PluginEditor.h** - The default PluginEditor class with a child UIContainer and OpenGLContext
```cpp
#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"
#include "UIContainer.h"

//==============================================================================
/**
*/
class NewProjectAudioProcessorEditor  : public juce::AudioProcessorEditor
{
public:
    NewProjectAudioProcessorEditor (NewProjectAudioProcessor&);
    ~NewProjectAudioProcessorEditor() override;

    //==============================================================================
    void paint (juce::Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    NewProjectAudioProcessor& audioProcessor;
    
    UIContainer childUIContainer; // Holds the UI
    
    juce::OpenGLContext openGLContext; // Gets attached to child UI container
    
    // Initial Plugin width, height, aspect
    static constexpr int DEFAULT_WIDTH = 400;
    static constexpr int DEFAULT_HEIGHT = 300;
    static constexpr double ASPECT_RATIO = (float) DEFAULT_WIDTH / (float) DEFAULT_HEIGHT;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NewProjectAudioProcessorEditor)
};

```

**PluginEditor.cpp** - Connects child component and OpenGLContext, uses AffineTransform to size editor
```cpp
#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
NewProjectAudioProcessorEditor::NewProjectAudioProcessorEditor (NewProjectAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
    openGLContext.setOpenGLVersionRequired (juce::OpenGLContext::OpenGLVersion::openGL3_2);
    openGLContext.attachTo (childUIContainer);
    openGLContext.setContinuousRepainting (true);

    setResizable (true, true);
    setSize (DEFAULT_WIDTH, DEFAULT_HEIGHT);
    getConstrainer()->setFixedAspectRatio (ASPECT_RATIO);
    
    childUIContainer.setBounds (0, 0, DEFAULT_WIDTH, DEFAULT_HEIGHT);
    addAndMakeVisible (childUIContainer);
}

NewProjectAudioProcessorEditor::~NewProjectAudioProcessorEditor()
{
}

//==============================================================================
void NewProjectAudioProcessorEditor::paint (juce::Graphics& g) {}

void NewProjectAudioProcessorEditor::resized()
{
    float zoomFactor = (float) getWidth() / DEFAULT_WIDTH;
    childUIContainer.setTransform (juce::AffineTransform().scaled (zoomFactor));
}
```

**Comment by reuk** [comment]
Thanks for reporting this issue and for providing detailed steps to repro the problem.

This should be fixed by https://github.com/juce-framework/JUCE/commit/6c46512e8bb458b70b92d483c41fe1bdf82f8521. Please let me know if you run into further issues
