### ISSUE TITLE
Don't allow creating projects that share name with existing system libraries

### ISSUE THREAD

**Issue by codecat** [juce-framework/JUCE#916]
I was struggling with a specific project for the longest time which I called `DComp`. Apparently the Windows API already contains a library `dcomp.lib`, which it preferred linking to instead of the shared code project's `DComp.lib`, because system libraries are higher in the library search paths.

Perhaps it would save some other people the headache I just went through by not allowing projects to share the same name as system libraries. But maybe there's already too little of a chance for a filename collision to happen?

**Comment by tpoole** [comment]
If we were going to introduce a feature like that we would need to maintain a list of all Windows system components (as you can save a project from any other operating system). I'm afraid that's just not viable.
