### ISSUE TITLE
AudioProcessorGraph shouldn't connect processor node automatically to output

### ISSUE THREAD

**Issue by deermichel** [juce-framework/JUCE#918]
Hey there, I played around with AudioProcessorGraph and stumbled across some imo weird behavior:
If you add an output node and a processor node, it will automatically output the processed sound even if there are no explicit connections. I'm a bit puzzled whether this is intended (and if so, why & where it's documented) or whether it's a bug.

You can find a minimal example [here](https://gist.github.com/deermichel/f0aa581948df8883600991427e8b4b97). If you start it as-is, you'll hear osc2 (note here, that it "automatically" connects the most recently added node osc2). My expectation here would've been that unless I add a connection from osc2 to output, nothing will be played.

Some additional observations: When adding an explicit connection (uncomment l.26) from osc1 to the left output channel, osc2 no longer outputs sound, and osc1 outputs on the left channel as expected. Then, remove that connection (uncomment l.27 as well) and you'll get silence. Oh and if you just uncomment l.27 (disconnect the output without adding a connection at first), it will play osc2.

I tracked it down to the `buildRenderingSequence()` method, but from there I don't know where to go.

I'm on macOS Big Sur 11.4, Intel using JUCE 6.0.8 - though I was able to reproduce this behavior on 6.0.7 and the current develop branch too.

Thanks for all the effort you put in this awesome framework :)

**Comment by reuk** [comment]
I took a look at this. I think the cause is something like:

- The oscillator has no active channels when it is added to the graph. The graph rendering sequence is built as though the oscillator has no ins/outs.
- During processing, each processor is given an audio buffer with at least one channel, so that the block duration can be determined.
- The graph uses a single "read-only" empty buffer as the input to all disconnected ins/outs. This same buffer is used as the input to the oscillator, and to the audio output node. As long as the buffer remains empty, this will have the intended effect (producing silence at the output of the graph).
- During processing, the Oscillator does not check `getTotalNumInputChannels` or `getTotalNumOutputChannels` before accessing the AudioBuffer. It then writes audio to the shared buffer which is supposed to remain empty.

This being the case, I think the bug is in your example. The Oscillator processor should store the expected channel count during `prepareToPlay`, and make sure not to read more than this number of channels during processing:

```cpp
class Oscillator : public juce::AudioProcessor
{
public:
    Oscillator (float freq)
    {
        mOscillator.setFrequency (freq);
        mOscillator.initialise ([] (float x) { return std::sin (x); });
    }

    void prepareToPlay (double sampleRate, int bufferSize) override
    {
        preparedChannels = std::min (2, std::max (getMainBusNumInputChannels(), getMainBusNumOutputChannels()));

        juce::dsp::ProcessSpec spec { sampleRate, static_cast<juce::uint32> (bufferSize), (juce::uint32) preparedChannels };
        mOscillator.prepare (spec);
    }

    void processBlock (juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages) override
    {
        buffer.clear();
        juce::dsp::AudioBlock<float> block (buffer.getArrayOfWritePointers(), preparedChannels, buffer.getNumSamples());
        juce::dsp::ProcessContextReplacing<float> context (block);
        mOscillator.process (context);
    }

    // other functions...

private:
    juce::dsp::Oscillator<float> mOscillator;
    int preparedChannels = 0;
};
```

**Comment by deermichel** [comment]
Yeah, you're right - thanks for the detailed explanation - using the other `AudioBlock` constructur with a specified channel count fixed my "issue".

Maybe it's a good idea to add the channel count to the [AudioProcessorGraph tutorial](https://docs.juce.com/master/tutorial_audio_processor_graph.html) as well? The `ProcessorBase` class uses the default `AudioProcessor` constructor as I did which means that inputs and outputs are disabled by default.

**Comment by reuk** [comment]
That's a good idea, thanks. I'll update the tutorial as suggested. This may take a few days to reach the public website.

**Comment by deermichel** [comment]
I have a follow-up question: You store the `preparedChannels` in the `prepareToPlay()` method which only gets called when the node is added (no connections yet, `preparedChannels == 0`). How can I trigger `prepareToPlay()` again after adding a connection, so that the channels count will be updated?

The alternative is to call `getMainBusNumOutputChannels()` during `processBlock()`, but I'm not sure if that's a safe thing to do on the audio thread.

**Comment by reuk** [comment]
Could you enable the buses before adding the node to the graph? i.e. rather than doing:
```cpp
auto node = graph.addNode (...);
node->getProcessor()->enableAllBuses();
```
You could do this, ensuring that the processor has the correct channel count at the point that it is inserted into the graph:
```cpp
auto myProcessor = std::make_unique<MyProcessor> (...);
myProcessor->enableAllBuses();
graph.addNode (std::move (myProcessor));
```

**Comment by deermichel** [comment]
Yes, that works - thank you very much 👍🏽 . I guess I have to learn a little bit more about how buses work 💯
