### ISSUE TITLE
crossover mac psylab 

### ISSUE THREAD

**Issue by Pospik2705** [juce-framework/JUCE#919]
Please include:

Hi, i tried install new version of music software called Psylab from fx23 vie Crossover on mac but i havent  a succes .
I tried old version instalation and it worked perfectly.

I contacted that developer what he changed and he told me the installer is still not much changed but he told me maybe something is diferent with JUICE.  Because  old installer had 6.0 version of juice and new installer has 6.1 and maybe something is wrong with framework...

So im contacting you because i realy would like to fix this problem . 

i tried install with software visual c++ and net 5.0 framework but still the application in mac only pop up and than disapear ...

**Comment by tpoole** [comment]
I'm afraid that we can't do much to help. You'll need to keep communicating with the app developer who has access to much more information than we do.
