### ISSUE TITLE
Thread::setThreadPriority for posix is severely broken

### ISSUE THREAD

**Issue by kmatheussen** [juce-framework/JUCE#923]
Even for priority 1, SCHED_RR is used. (priority 5 is supposed to be normal). I would guess this could have caused many computer lock-ups. Offending commit: 71ee73ead19ba1a66ae3808463dbca404ff51f31
I informed about this on the forum many years ago too, but it seems like it's not been fixed.

Here's an attempt at a proper fix:
https://github.com/kmatheussen/radium/blob/master/pluginhost/thread_priorities_fixes.diff

**Comment by kmatheussen** [comment]
Also, priority==realtimeAudioPriority is not checked in set in Thread::setCurrentThreadPriority and Thread::startThread. I've fixed that in my patch, but now the number 9 is used three different places so it should be replaced by a constant.

**Comment by kmatheussen** [comment]
Also, on mac, thread_policy_set should probably be used instead of SCHED_RR to get audio realtime priority. In my experience, you get glitches only using SCHED_RR or SCHED_FIFO.

**Comment by kmatheussen** [comment]
Just to clarify what's happening: All JUCE threads run with SCHED_RR realtime priority. And by default, a JUCE thread runs with priority 50, which is what you normally use for audio processing threads. On Linux this means that the computer can easily lock up. On Mac, I don't think SCHED_RR is that intrusive (if it even does anything at all). I would be surprised if this bug hasn't caused many lockups on Linux.

**Comment by reuk** [comment]
Thanks for reporting, this issue should be resolved by these commits:

https://github.com/juce-framework/JUCE/commit/802f33b0e865011aca07058fe5644cae27a46b8f
https://github.com/juce-framework/JUCE/commit/1de762218a0b78ad41e7e8609694a27ce5903e6b
