### ISSUE TITLE
xcode analysis issue in juce_core/text/juce_Base64.cpp:111

### ISSUE THREAD

**Issue by modosc** [juce-framework/JUCE#925]
thanks for the [last fix](https://github.com/juce-framework/JUCE/issues/921), here's one more new one

```
Bot Issue for ID700 Desktop (analysis issue in juce_Base64.cpp:111)
Integration #134 of ID700 Desktop on build
Open Integration in Xcode: xcbot://build/botID/962fd8a493ade489d50e0350c2002bb4/integrationID/0b433445a3e3809cb5ea93e9bf096df1
Static Analysis Issue: Value stored to 'ok' during its initialization is never read
File: InstrumentDesigner/Vendor/JUCE/modules/juce_core/text/juce_Base64.cpp:111
Introduced by reuk (3c68581)
```

**Comment by ed95** [comment]
Are you able to reproduce this on the latest `develop`? I've tried running Product->Archive using the latest Xcode 13.0 beta 3 but am not seeing the warning. It should be silenced by the use of `jassertquiet` that was added in https://github.com/juce-framework/JUCE/commit/3c68581.

**Comment by modosc** [comment]
i am still seeing it - i'm at 802f33b0e on my branch of develop and i verified i have 3c68581

**Comment by ed95** [comment]
Do you have any non-default build settings enabled? What architecture are you building for? Can you see if you can reproduce it by just running Product->Analyze on the DemoRunner project from a fresh clone of `develop`?

**Comment by modosc** [comment]
> Do you have any non-default build settings enabled? 
i'm not sure? would this be obvious from my jucer file?

> What architecture are you building for?
i'm building for desktop and it's on a m1, maybe that's causing the issue?

>  Can you see if you can reproduce it by just running Product->Analyze on the DemoRunner project from a fresh clone of develop?
i'll try tonight, thanks!

**Comment by modosc** [comment]
weird, it only happens on my m1 build server, and then only for x86_64:
![image](https://user-images.githubusercontent.com/2231664/127724226-d859b052-2c7f-4f33-a80c-7ce230f61a3f.png)

analyzing on an intel mac doesn't trigger it 🤷🏽

**Comment by tpoole** [comment]
This is no longer being flagged in more recent versions of Xcode.
