### ISSUE TITLE
new warning in juce_AUv3_Wrapper.mm in xcode 13 beta

### ISSUE THREAD

**Issue by modosc** [juce-framework/JUCE#926]
```
Vendor/JUCE/modules/juce_audio_plugin_client/AU/juce_AUv3_Wrapper.mm:1410:21: Enumeration value 'AURenderEventMIDIEventList' not explicitly handled in switch
```

**Comment by ed95** [comment]
Thanks for reporting, fixed in https://github.com/juce-framework/JUCE/commit/bdc2334c9851f82420978d39507a9816bcc25690 and https://github.com/juce-framework/JUCE/commit/6d53ed3fec07474a91f07ab7ea0c9655330044fa
