### ISSUE TITLE
non-public ios api usage

### ISSUE THREAD

**Issue by modosc** [juce-framework/JUCE#928]
just updated develop and got this from the app store. i'm not using accessibility yet.

```
ITMS-90338: Non-public API usage - The app references non-public selectors in PlugIns/ID700.appex/ID700: accessibilityHitTest:,The app references non-public selectors in ID700: accessibilityHitTest:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition,
```

**Comment by sseyod** [comment]
I have this problem as well!

See also https://forum.juce.com/t/juce-accessibility-on-develop/45142/186

Pete

**Comment by sseyod** [comment]
There is also a similar problem with sessionRuntimeError:

iOS apps submitted with these calls in them will fail app store submission...

HTH! Pete

**Comment by ed95** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/9446f6317c6d41330da836681a7021a2c115ce12 and https://github.com/juce-framework/JUCE/commit/17fe5a54d8c4f9174192a6a51c9d2439e3529267. Thanks for reporting!

**Comment by sseyod** [comment]
Thanks @ed95 ! Pete
