### ISSUE TITLE
AUAudiofilesPlayer Plugin can not work on iOS

### ISSUE THREAD

**Issue by realsnake** [juce-framework/JUCE#929]
![simulator_screenshot_FF1E992A-0F6F-4206-97ED-F63C27E32F8B](https://user-images.githubusercontent.com/1198818/127994256-f4b442d6-a02b-4d78-9d42-3f2cb90e5f2e.png)

Use extra/ AudioPluginHost to run on iPad simulator, double click AUAudiofilesPlayer shows empty UI.
The same mac app works fine.

**Comment by ed95** [comment]
This has been fixed on the `develop` branch in https://github.com/juce-framework/JUCE/commit/d589f65b368bb76c02469e15ee94429f42d55368.
