### ISSUE TITLE
New bugfix release?

### ISSUE THREAD

**Issue by segfault16** [juce-framework/JUCE#933]
Hi,

there's an issue on JUCE 6.0.8 when using juce::BluetoothMidiDevicePairingDialogue:
````
JUCE Assertion failure in juce_ios_UIViewComponentPeer.mm:274
````
The issue doesn't occur on develop.
Is there a plan for the next release so we can switch back to using a non-develop version of Juce?

Thanks, best regards

**Comment by ed95** [comment]
6.1.0 was released yesterday and contains this fix - https://github.com/juce-framework/JUCE/releases/tag/6.1.0
