### ISSUE TITLE
URL::downloadToFile() doesn't work on AUv3 plugins that are using App Groups

### ISSUE THREAD

**Issue by dhilowitz** [juce-framework/JUCE#936]
Hi, 

I have an iOS App / AUv3 plugin that downloads sample libraries using the `URL::downloadToFile()` function. It works really well when running the standalone app, but finishes with an error when I try to run the same function from within an AUv3 plugin. I looked and the specific error that iOS is returning is "The operation couldn’t be completed. (NSURLErrorDomain error -995.)"

I researched what this error means, and I came across this response on StackOverflow: https://stackoverflow.com/a/42611740/479540. As it happens, my App Extension does make use of AppGroups so that I can have a common storage area that is shared between my Standalone app and my App Extension. That StackOverflow response links to this Apple Page: https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW2

That page says that in a case like mine – where one is using an AppExtension with an AppGroup – one needs to specify a `sharedIdentifier` for the `NSURLSessionConfiguration`. Unfortunately, JUCE's doesn't allow one to do this. I would need to do something like this (juce_mac_Network.mm, line 448):

```objective-c
NSURLSessionConfiguration* config = config = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier: juceStringToNS (uniqueIdentifier)];
config.sharedContainerIdentifier = @"group.MyApp";
session =
            [NSURLSession sessionWithConfiguration: config
                                          delegate: delegate
                                     delegateQueue: nullptr];
```
I tried using this code above with my App Group identifier, and the download worked correctly...but there is no way to set this without modifying the JUCE code. I would love to have this added into the JUCE library somehow.

**Comment by dhilowitz** [comment]
I've added a PR for this issue above.

**Comment by reuk** [comment]
Thanks for the feature request. I've added the requested functionality here:

https://github.com/juce-framework/JUCE/commit/f87582a01311efbad249cab2340c6d63f4e53d65

**Comment by dhilowitz** [comment]
Yay! This is great news. Thanks.
