### ISSUE TITLE
URL not namespaced in GUI editor's code output

### ISSUE THREAD

**Issue by jpcima** [juce-framework/JUCE#944]
Steps
- create a new GUI component in the Projucer
- add a hyperlink button
- assign the hyperlink button an URL
- save

Expectation
The `URL([...])` is expected to be namespaced as `juce::URL` in the code output, but isn't.
Likely related: https://git.io/JEoMa

Environment
JUCE 6.1.0 Linux Intel 64bit

**Comment by tpoole** [comment]
This has been fixed on the `develop` branch: https://github.com/juce-framework/JUCE/commit/dbbf5cfe6dbd5f711b1991bdc0706780d5930311

Thank you for reporting.
