### ISSUE TITLE
Manufacturer and Plugins codes with less than 4 chars are random

### ISSUE THREAD

**Issue by joaquinsaavedra** [juce-framework/JUCE#951]
These codes must be 4 chars, if not, now random bits are introduced. 

To solve that, I changed this method https://github.com/juce-framework/JUCE/blob/6.1.1/extras/Projucer/Source/Project/jucer_Project.cpp#L2577-L2582 in the following way (spaces are introduced if the code used is shorter)

```
    const auto toCharLiteral = [] (const String& v)
    {
        juce::String v_Lenght4 = v;
        
        while (v_Lenght4.length() < 4)
            v_Lenght4.append(" ", 1);
        
        auto fourCharCode = v_Lenght4.substring (0, 4);
        uint32 hexRepresentation = 0;

        for (int i = 0; i < 4; ++i)
            hexRepresentation = (hexRepresentation << 8u)
                                |  (static_cast<unsigned int> (fourCharCode[i]) & 0xffu);

        return "0x" + String::toHexString (static_cast<int> (hexRepresentation));
    };
```

**Comment by reuk** [comment]
Thanks for reporting, the issue should be resolved here: https://github.com/juce-framework/JUCE/commit/d13a23ad14a3a9208887070043c2ec3dde06ef97
