### ISSUE TITLE
Projucer: generating project in cache and moving to final location BREAKS all RELATIVE PATHS to JUCE folder

### ISSUE THREAD

**Issue by mgood7123** [juce-framework/JUCE#962]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code

        global paths

        ![image](https://user-images.githubusercontent.com/26642847/139737266-8854e70f-ccb9-40d5-8d5b-754bdd41805c.png)

      * open Example > Audio > AudioAppDemo
      * export to Android
      * assume `~` is `/Users/smallville7123` and `JUCE` is installed to `/Users/smallville7123/JUCE` and `AudioAppDemo` to `/Users/smallville7123/Desktop/Juce/AudioAppDemo`
      * open `/Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/app/CMakeLists.txt`
      * `"../../../../../../../../JUCE` when resolved from `/Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/app` points to the following, in which `../../../../../../../../JUCE` contains 8 `../`
      * START
      * 0 `.` > /Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/app
      * 1 `../` > /Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/
      * 2 `../` > /Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/
      * 3 `../` > /Users/smallville7123/Desktop/Juce/AudioAppDemo/
      * 4 `../` > /Users/smallville7123/Desktop/Juce/
      * 5 `../` > /Users/smallville7123/Desktop/
      * 6 `../` > /Users/smallville7123/
      * 7 `../` > /Users/
      * 8 `../` > /
      * 9 `JUCE` > /JUCE
      * END
      * also resulting in the following cmake error
      * ```
        C/C++: /Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/app/CMakeLists.txt debug_Debug|armeabi-v7a : CMake Error at /Users/smallville7123/Desktop/Juce/AudioAppDemo/Builds/Android/app/CMakeLists.txt:33 (add_library):
          Cannot find source file:
        
            ../../../../../../../../JUCE/modules/juce_audio_basics/audio_play_head/juce_AudioPlayHead.h
        
          Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx
        ```
      * this also happens when the project is located elsewhere such as `/Users/smallville7123/AudioAppDemo`
      * open `/Users/smallville7123/OpenGLDemo/Builds/Android/app/CMakeLists.txt`
      * `"../../../../../../../../JUCE` when resolved from `/Users/smallville7123/OpenGLDemo/Builds/Android/app` points to the following, in which `../../../../../../../../JUCE` contains 8 `../`
      * START
      * 0 `.` > /Users/smallville7123/OpenGLDemo/Builds/Android/app
      * 1 `../` > /Users/smallville7123/OpenGLDemo/Builds/Android/
      * 2 `../` > /Users/smallville7123/OpenGLDemo/Builds/
      * 3 `../` > /Users/smallville7123/OpenGLDemo/
      * 4 `../` > /Users/smallville7123/
      * 5 `../` > /Users/
      * 6 `../` > /
      * 7 `../` > /
      * 8 `../` > /
      * 9 `JUCE` > /JUCE
      * END
      * again resulting in the same cmake error
      * ```
        C/C++: /Users/smallville7123/OpenGLDemo/Builds/Android/app/CMakeLists.txt debug_Debug|armeabi-v7a : CMake Error at /Users/smallville7123/OpenGLDemo/Builds/Android/app/CMakeLists.txt:29 (add_library):
          Cannot find source file:
        
            ../../../../../../../../JUCE/modules/juce_core/containers/juce_AbstractFifo.c
        
          Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx
        ```

this also happens when JUCE is located in a non-heirarchical directory

~/git/JUCE

generated path `"../../../../../../../../git/JUCE`

resolved path given `/Users/smallville7123/k/AudioPlaybackDemo/Builds/Android/app` > `/git/JUCE`

  2) the expected behaviour
        * the paths to correctly point to the JUCE set in global paths
  3) the operating system
        * macOS Catalina
  4) the architecture (32-bit or 64-bit)
        * 64 bit
  5) a stack trace - if the bug causes a crash
        * none
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
        * none
  7) which DAW you observed the bug in - if applicable
        * none

Make sure you have pulled the latest commits from the `develop` branch of the
JUCE repo and have re-compiled the Projucer before you submit your bug. Often
we have already fixed the issue but it hasn't yet been released on the `master`
branch. If it's a major bug, which must be hot-fixed immediately, then we will
also accept bug reports for tagged release versions.

this issue persists in develop branch

**Comment by mgood7123** [comment]
this appears to be due to `getTargetFolder().getChildFile ("app")` returning   `/Users/smallville7123/Library/Caches/Projucer/PIPs/AudioSynthesiserDemo/Builds/Android/app`

in which     `/Users/smallville7123/Library/Caches/Projucer/PIPs/AudioSynthesiserDemo/Builds/Android/app/../../../../../../../../`     resolves to `~/` which is correct path

HOWEVER it is generating project for location `/Users/smallville7123/k/AudioPlaybackDemo/AudioPlaybackDemo.jucer`

**Comment by mgood7123** [comment]
or rather it appears that Projucer generates a temporary project in cache and then copies that project over to its final destination, making all relative paths to JUCE break since they are only valid from inside the cache folder since they are relative to the cache folder

**Comment by ed95** [comment]
Thanks for reporting. This has been fixed on the `develop` branch in https://github.com/juce-framework/JUCE/commit/67dfc1975c6315ae9e4540b3b515b863a960be44
