### ISSUE TITLE
Add a #define to BinaryData.h to indicate the namespace exists

### ISSUE THREAD

**Issue by codecat** [juce-framework/JUCE#963]
In one of my Juce modules, I make use of `BinaryData::getNamedResource`, but when there is no BinaryData cpp/h files, then the compilation will fail. It would be nice if I could add a precompiler guard to my module code so I can avoid this. For example:
```cpp
#if JUCE_BINARY_DATA_INCLUDED
  int dataSize = 0;
  auto data = BinaryData::getNamedResource("test", dataSize);
  if (data != nullptr) {
    // do something with data
  }
#endif
```
Should be pretty straightforward to just add a define here, I think:
https://github.com/juce-framework/JUCE/blob/fbe95b0b073ccb589e28255cb0cd56e1382dc2c9/extras/Build/juce_build_tools/utils/juce_BinaryResourceFile.cpp#L82-L89

**Comment by reuk** [comment]
I think there's no need for a define here. You can do something like this:

```cpp
// Fallback binary data definitions
namespace BinaryDataFallbacks {
const int namedResourceListSize = 0;
const char* namedResourceList[]{};
const char* originalFilenames[]{};
const char* getNamedResource(const char*, int&) { return nullptr; }
const char* getNamedResourceOriginalFilename(const char*) { return nullptr; }
}  // namespace BinaryDataFallbacks

// Import fallback definitions into the BinaryData namespace
namespace BinaryData {
using namespace BinaryDataFallbacks;
}
```

Now, when you use a symbol like `BinaryData::getNamedResource`, the version declared directly inside the BinaryData namespace will be preferred, if it is available. If the "real" declarations aren't available, the fallbacks will be used instead.

**Comment by codecat** [comment]
That's a very interesting approach.

I'm not familiar with the language rules here - is this standards compliant? Kinda feels like it should be throwing ambiguity errors when the real declerations are available.

**Comment by codecat** [comment]
Sorry for the delay in closing this issue - it worked! Thanks 👍
