### ISSUE TITLE
Add Visual Studio 2022 exporter

### ISSUE THREAD

**Issue by codecat** [juce-framework/JUCE#964]
Visual Studio 2022 [came out today](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-now-available/) with the platform toolset `v143`.

My projects seems to build correctly on this new toolset out of the box if I switch to it.

**Comment by ed95** [comment]
We've added VS2022 support to the Projucer on the `develop` branch in https://github.com/juce-framework/JUCE/commit/8aabde768006214e1f7e91bc6ace1a59ed34dc45.
