### ISSUE TITLE
DemoRunner on Fedora 34 is constantly resetting its audio output, trashing quality

### ISSUE THREAD

**Issue by ferdnyc** [juce-framework/JUCE#968]
Sorry if this isn't really the right venue for this, I should maybe take it to the forum instead. Could be this is only happening to me (HOPEFULLY this is only happening to me), but:

After building the DemoRunner off any recent commit (going back months, at least) on my Fedora 34 system:

```sh
cd /path/to/JUCE
cmake -B build -S . -DJUCE_BUILD_EXAMPLES=1
cmake --build build --target DemoRunner -j4
```
...and then launching `build/examples/DemoRunner/DemoRunner_artefacts/DemoRunner`, the sound quality in "AudioPlaybackDemo.h" or any other audio-playback demo is **terrible**. (It sounds like a scratchy 1937 phonograph, but not in a fun way.) A situation I finally tracked down to the fact that its connection to the audio output is being reset **HUNDREDS** of times per minute, even when sitting idle. 

Here's a screencast of the PulseAudio Device Manager tool running on top of an idle DemoRunner, open and not even playing. After a few seconds I hit Play, and the situation afterwards does not change (except that the MP3 being played back sounds horrible). In reality it's even worse than shown here, the GIF is only 20fps so it doesn't have the frame rate to reproduce the resetting at full speed.

![JUCE-DemoRunner-Linux_edit](https://user-images.githubusercontent.com/538020/142055454-4fbef0ff-4d87-4600-aa65-2fe433b2f00c.gif)

I made no changes to the code, the build was as simple as I've illustrated, and I left all settings at the defaults which appear to be correct. Is anyone else experiencing this on Linux with PulseAudio, or is it an issue with my system? (Note that Fedora 35 moves from PulseAudio to PipeWire which _might_ affect this; I haven't upgraded yet.)

**Comment by ferdnyc** [comment]
(As another data point / symptom, the latency test demo can't even complete, as the rapid resetting causes the test to abort.)

**Comment by ferdnyc** [comment]
I spent a little time trying to track this down, with no luck so far. Valgrind shows no sign of any sort of leaks or issues with memory, as expected. An `strace` shows system calls flying fast and furious the entire time the DemoRunner process is alive, but that's obvious just from looking at what it's doing, and nothing visible in the trace is really much help in tracking down the source of the problem. A run inside `sysprof` doesn't seem to point to any **particular** threads or calls hogging the CPU, though CPU consumption is quite a bit higher than it should be for an idle application.

**Comment by ferdnyc** [comment]
Spotted the `JUCE_ALSA_LOGGING` flag in the code, so I rebuilt the DemoRunner with that defined `=1`. Not _too_ shockingly, as soon as it launches the console output is flooded with these:
```text
 ALSA lib pcm.c:8564:(snd_pcm_recover) underrun occurred
```
Here's the full output from start all the way up until it goes into its endless "recovery" loop:
```text
JUCE v6.1.2
ALSA: scanForDevices()

ALSA: ID: null; desc: Discard all samples (playback) or generate zero samples (capture); ioid: 

ALSA: ID: pipewire; desc: PipeWire Sound Server; ioid: 

ALSA: ID: pulse; desc: PulseAudio Sound Server; ioid: 

ALSA: ID: default; desc: Default ALSA Output (currently PulseAudio Sound Server); ioid: 

ALSA: ID: sysdefault:CARD=PCH; desc: HDA Intel PCH, ALC662 rev1 Analog
Default Audio Device; ioid: 

ALSA: ID: front:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
Front output / input; ioid: 

ALSA: ID: surround21:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
2.1 Surround output to Front and Subwoofer speakers; ioid: Output

ALSA: ID: surround40:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
4.0 Surround output to Front and Rear speakers; ioid: Output

ALSA: ID: surround41:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
4.1 Surround output to Front, Rear and Subwoofer speakers; ioid: Output

ALSA: ID: surround50:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
5.0 Surround output to Front, Center and Rear speakers; ioid: Output

ALSA: ID: surround51:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
5.1 Surround output to Front, Center, Rear and Subwoofer speakers; ioid: Output

ALSA: ID: surround71:CARD=PCH,DEV=0; desc: HDA Intel PCH, ALC662 rev1 Analog
7.1 Surround output to Front, Center, Side, Rear and Woofer speakers; ioid: Output

ALSA: ID: hdmi:CARD=NVidia,DEV=0; desc: HDA NVidia, HDMI 0
HDMI Audio Output; ioid: Output

ALSA: ID: hdmi:CARD=NVidia,DEV=1; desc: HDA NVidia, HDMI 1
HDMI Audio Output; ioid: Output

ALSA: ID: hdmi:CARD=NVidia,DEV=2; desc: HDA NVidia, HDMI 2
HDMI Audio Output; ioid: Output

ALSA: ID: hdmi:CARD=NVidia,DEV=3; desc: HDA NVidia, HDMI 3
HDMI Audio Output; ioid: Output

ALSA: ID: hdmi:CARD=NVidia,DEV=4; desc: HDA NVidia, HDMI 4
HDMI Audio Output; ioid: Output

ALSA: ID: sysdefault:CARD=Device; desc: USB Audio Device, USB Audio
Default Audio Device; ioid: 

ALSA: ID: front:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
Front output / input; ioid: 

ALSA: ID: surround21:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
2.1 Surround output to Front and Subwoofer speakers; ioid: Output

ALSA: ID: surround40:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
4.0 Surround output to Front and Rear speakers; ioid: Output

ALSA: ID: surround41:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
4.1 Surround output to Front, Rear and Subwoofer speakers; ioid: Output

ALSA: ID: surround50:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
5.0 Surround output to Front, Center and Rear speakers; ioid: Output

ALSA: ID: surround51:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
5.1 Surround output to Front, Center, Rear and Subwoofer speakers; ioid: Output

ALSA: ID: surround71:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
7.1 Surround output to Front, Center, Side, Rear and Woofer speakers; ioid: Output

ALSA: ID: iec958:CARD=Device,DEV=0; desc: USB Audio Device, USB Audio
IEC958 (S/PDIF) Digital Audio Output; ioid: Output

ALSA: ID: iec958:CARD=Device,DEV=1; desc: USB Audio Device, USB Audio #1
IEC958 (S/PDIF) Digital Audio Output; ioid: Output

ALSA: getDeviceProperties(default)

ALSA: getDeviceNumChannels: 1 32

ALSA: getDeviceProperties(default)

ALSA: getDeviceNumChannels: 1 32

ALSA: snd_pcm_open (default, forInput=1)

ALSA: ALSADevice::setParameters(default, 44100, 1, 512)

ALSA: format: bitDepth=32, isFloat=1, isLittleEndian=1, numChannels=1

ALSA: frames: 512, periods: 4, samplesPerPeriod: 512

ACCESS:  RW_INTERLEAVED
FORMAT:  FLOAT_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 32
CHANNELS: 1
RATE: 44100
PERIOD_TIME: (11609 11610)
PERIOD_SIZE: 512
PERIOD_BYTES: 2048
PERIODS: 4
BUFFER_TIME: (46439 46440)
BUFFER_SIZE: 2048
BUFFER_BYTES: 8192
TICK_TIME: [0 0]
tstamp_mode: NONE
tstamp_type: GETTIMEOFDAY
period_step: 1
avail_min: 512
start_threshold: 512
stop_threshold: 4611686018427387904
silence_threshold: 0
silence_size: 4611686018427387904
boundary: 4611686018427387904
ALSA: snd_pcm_open (default, forInput=0)

ALSA: ALSADevice::setParameters(default, 44100, 2, 512)

ALSA: format: bitDepth=32, isFloat=1, isLittleEndian=1, numChannels=2

ALSA: frames: 512, periods: 4, samplesPerPeriod: 512

ACCESS:  RW_INTERLEAVED
FORMAT:  FLOAT_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 64
CHANNELS: 2
RATE: 44100
PERIOD_TIME: (11609 11610)
PERIOD_SIZE: 512
PERIOD_BYTES: 4096
PERIODS: 4
BUFFER_TIME: (46439 46440)
BUFFER_SIZE: 2048
BUFFER_BYTES: 16384
TICK_TIME: [0 0]
tstamp_mode: NONE
tstamp_type: GETTIMEOFDAY
period_step: 1
avail_min: 512
start_threshold: 512
stop_threshold: 4611686018427387904
silence_threshold: 0
silence_size: 4611686018427387904
boundary: 4611686018427387904
ALSA lib pcm.c:8564:(snd_pcm_recover) underrun occurred
```
...and then Message Repeats™ thousands of times. Although it did pop in one of these at one point, randomly:
```text
ALSA: Did not write all samples: numDone: -32, numSamples: 512
```
Which is a bit weird because it wasn't even playing anything. In fact, it _**never**_ played anything. I just launched it, grabbed the logspew, and closed it again without ever starting any of the demos, but still it was having kittens the entire time.

**Comment by ferdnyc** [comment]
Finally tracked this down to a bad `.asoundrc` I didn't even know was there! (Probably like 10 years old, too.) Whoops!

**Comment by shuhaowu** [comment]
I'm also hearing a bunch of pops and cracks using PulseAudio with the demo runner. However, I solved the problem by disabling mic input. I suspect the priority is not setup correctly so the two threads are interfering with each other somehow? Probably not the same problem, tho.
