### ISSUE TITLE
Time::getUTCOffsetString() returns incorrect offset string

### ISSUE THREAD

**Issue by JordanSkousen** [juce-framework/JUCE#969]
### Steps to reproduce
Set computer time to a timezone with a negative offset from UTC and one with a minute-specific offset (for example, Newfoundland with UTC-03:30). Then run `Time::getUTCOffsetString` or `Time::toISO8601`. 
### Expected result
The UTC offset will be incorrectly reported as "-hr:-min" (for example, "-03:-30" for Newfoundland) when it should be "-hr:min" ("-03:30" for Newfoundland) according to the ISO8601 specification.
### Potential easy fix
Just change the `minutes % 60` argument in the `String::formatted` call to `abs(minutes % 60)`.

**Comment by reuk** [comment]
Thanks for raising this. I've added a fix and a few tests here: https://github.com/juce-framework/JUCE/commit/69aa461be1d54b43234f64ddf8f219ab208e9403

I'm closing this issue as I believe it should be resolved. If you encounter further problems please let us know and I can reopen the issue if necessary.
