### ISSUE TITLE
please add  LSHandlerRank to document file extensions plist

### ISSUE THREAD

**Issue by modosc** [juce-framework/JUCE#971]
i started getting these emails from apple when i submit a build to the store:

> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "ID700" 1.12.0 (1519). Your delivery was successful, but you > may wish to correct the following issues in your next delivery:
> 
> ITMS-90788: Incomplete Document Type Configuration - The CFBundleDocumentTypes dictionary array in the 'sc.modo.instrumentdesigner.ios' Info.plist should contain an LSHandlerRank value for the CFBundleTypeName 'idwave' entry. Refer to https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW1 for more information on the LSHandlerRank key.
>
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.

i think something like this would work:
```diff
diff --git a/extras/Build/juce_build_tools/utils/juce_PlistOptions.cpp b/extras/Build/juce_build_tools/utils/juce_PlistOptions.cpp
index 97a3815fd..2e347a958 100644
--- a/extras/Build/juce_build_tools/utils/juce_PlistOptions.cpp
+++ b/extras/Build/juce_build_tools/utils/juce_PlistOptions.cpp
@@ -206,6 +206,7 @@ namespace build_tools
                     addPlistDictionaryKey (*dict2, "CFBundleTypeRole", "Editor");
                     addPlistDictionaryKey (*dict2, "CFBundleTypeIconFile", "Icon");
                     addPlistDictionaryKey (*dict2, "NSPersistentStoreTypeKey", "XML");
+                    addPlistDictionaryKey (*dict2, "LSHandlerRank", "Owner");
                 }

                 arrayTag->createNewChildElement ("string")->addTextElement (ex);
```

**Comment by reuk** [comment]
Thanks, I've added that here: https://github.com/juce-framework/JUCE/commit/6468088100689663804bac2444487d077c5879c5

Please try out the change and let us know if you encounter any new issues. I'm closing this issue for now.
