### ISSUE TITLE
Race condition on Device Start-Shutdown

### ISSUE THREAD

**Issue by AlexandreF-SP** [juce-framework/JUCE#976]
How to reproduce:

Start DemoRunner with bluetooth device.
Application seems to switch settings to accommodate both input/output devices.

Issue:

During the startup a race condition is found between: `AudioIODeviceCombiner::start` and `AudioIODeviceCombiner::shutdown`

[_/juce_audio_devices/native/juce_mac_CoreAudio.cpp_](https://github.com/juce-framework/JUCE/blob/develop/modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp#:~:text=void-,start,-(AudioIODeviceCallback*%20newCallback)%20override)

Seems that `callback` is expected to be protected by `const ScopedLock sl (callbackLock);`.
But  at line 1534 `if (callback != newCallback)` I found it to be an unsafe comparison.

Simple fix would be to move the lock to be before the comparison.

Thanks for the hard work,
Alexandre F.

On MacOS - arm64

**Comment by reuk** [comment]
Thanks, I've fixed some threading concerns in this commit: https://github.com/juce-framework/JUCE/commit/f1b6bbc92130a1927727d10008973e2296add356

Could you try updating and check whether the problem is resolved for you? Thanks!

**Comment by AlexandreF-SP** [comment]
Thx for the quick reply!
I had a bit older version of develop :)

It seems to be fixed now.
