### ISSUE TITLE
`AudioProcessorLoadMeasurer` returns NaN when called without `numSamplesInBlock`

### ISSUE THREAD

**Issue by jatinchowdhury18** [juce-framework/JUCE#982]
In JUCE 6.1.4, `AudioProcessorLoadMeasurer` can be used with or without providing the number of samples in each block.

When providing the number of samples in the block, the load measurer behaves as expected:
```cpp
AudioProcessorLoadMeasurer loadMeasurer;

void MyPlugin::processBlock (AudioBuffer<float>& buffer, MidiBuffer& midi)
{
    AudioProcessorLoadMeasurer::ScopedTimer loadTimer { loadMeasurer, buffer.getNumSamples() };
    ...
}
```

However, when using the load measurer without providing the number samples in the block (as was the only way to use it in JUCE 6.1.2 and earlier), the load measurer will return NaN when calling `AudioProcessorLoadMeasurer::getLoadAsProportion()`.
```cpp
AudioProcessorLoadMeasurer loadMeasurer;

void MyPlugin::processBlock (AudioBuffer<float>& buffer, MidiBuffer& midi)
{
    AudioProcessorLoadMeasurer::ScopedTimer loadTimer { loadMeasurer };
    ...
}

void checkLoadIsNotNaN()
{
    // this assertion is failing!
    jassert (! std::isnan (loadMeasurer.getLoadAsProportion()));
}
```

In looking at [the code](https://github.com/juce-framework/JUCE/blob/develop/modules/juce_audio_basics/buffers/juce_AudioProcessLoadMeasurer.cpp#L72), it looks like the single-argument constructor uses the `AudioProcessLoadMeasurer::samplesPerBlock` field as the number of samples in the block, but that field is never initialised.
```cpp
AudioProcessLoadMeasurer::ScopedTimer::ScopedTimer (AudioProcessLoadMeasurer& p)
    : ScopedTimer (p, p.samplesPerBlock)
{
}
```

I suppose the "expected behaviour" could either be to initialise `AudioProcessLoadMeasurer::samplesPerBlock`, or to remove the single-argument constructor.

**Comment by reuk** [comment]
Thanks for reporting, the issue should be fixed on develop now:

https://github.com/juce-framework/JUCE/commit/b0e689eaf4b170f8e693f4183534d7ab896db406
