### ISSUE TITLE
Compile errors with latest master/develop branch with CMake and MinGW

### ISSUE THREAD

**Issue by josephsaldutti1** [juce-framework/JUCE#987]
Compiling JUCE both on the master and develop branch with CMake and MinGW results in compile error:

```
************/JUCE/modules/juce_core/native/juce_win32_ComSmartPtr.h:32:35:
  error: type/value mismatch at argument 1 in template parameter list for
  'template<class Type> struct juce::UUIDGetter'

     32 |  #define __uuidof(x)  UUIDGetter<x>::get()
        |                                   ^

  c:\mingw\x86_64-w64-mingw32\include\combaseapi.h:84:30: note: in expansion
  of macro '__uuidof'

     84 | #define IID_PPV_ARGS(ppType) __uuidof (**(ppType)), IID_PPV_ARGS_Helper (ppType)
        |
```

I saw this post: https://gitanswer.com/juce-failed-to-build-from-source-from-msys2-with-cmake-c-849821150
So tried it out with version 6.0.7 and it compiles OK.

Reproduction steps:

Windows 10 Pro Version 2004 OS Build 19041.1348, 64bit
1) Installed MinGW/CMake and clone JUCE repo
2) Add CC and CXX environment variables:
```
$env:CC = "C:\MinGW\bin\gcc"
$env:CXX = "C:\MinGW\bin\g++"
```
3) Run cmake:
```
cmake -G "MinGW Makefiles" -B cmake-build-install
```

Full CMake Log file:
[CMakeOutput.log](https://github.com/juce-framework/JUCE/files/7826237/CMakeOutput.log)

**Comment by josephsaldutti1** [comment]
Similar/same as #985 #980

**Comment by Birch-san** [comment]
I've provided a way to reproduce it in Docker also:  
https://github.com/juce-framework/JUCE/issues/985#issuecomment-1008323559
