### ISSUE TITLE
[Feature Request] juce::CodeEditorComponent font styling tokens

### ISSUE THREAD

**Issue by ElandaOfficial** [juce-framework/JUCE#989]
Hello, I lately worked a lot with the juce::CodeEditorComponent, which sometimes was a hassle in and out.
But it took a week until I got accustomed to it, and now I am realising that you can only tokenise colours on the text, not however different font types and style.

It would be cool to, besides the colour, to also change how the font will look like, so as to that we have bold, italic, underlined fonts and so on.

My proposal would look something like a struct that is returned that contains a colour-id and an optional font as second object, so as to that the tokeniser can use both to format the text.

**Comment by tpoole** [comment]
I've moved this feature request to the JUCE forum: https://forum.juce.com/t/juce-codeeditorcomponent-font-styling-tokens/50440
