### ISSUE TITLE
Address sanitizer in GCC and Clang finds JUCE bugs.

### ISSUE THREAD

**Issue by keinstein** [juce-framework/JUCE#999]
Please include:

  1) detailed steps on how to reproduce the bug, preferably with already
     existing JUCE code such as the demo plugin or the demo code
Compile your Linux binary with CFLAGS, CXXFLAGS and LDFLAGS that contain “-g -pg -ggdb -fno-omit-frame-pointer -fno-common -fsanitize=address -static-libasan”.
Run the program like (e.g. Projucer). The program will likely crash as in https://github.com/RomanKubiak/ctrlr/issues/413
  2) the expected behaviour
The program works as expected.
  3) the operating system
Linux
  4) the architecture (32-bit or 64-bit)
64-bit
  5) a stack trace - if the bug causes a crash
See https://github.com/RomanKubiak/ctrlr/issues/413
  6) the plugin format (VST2, VST3, AU, AAX, RTAS) - if applicable
Standalone
  7) which DAW you observed the bug in - if applicable
not applicable.

I'd suggest to add “-g -pg -ggdb -fno-omit-frame-pointer -fno-common -fsanitize=address -static-libasan” to the above mentioned flags for builds done with clang and with gcc in Projucer. This will reveal many other bugs.

**Comment by tpoole** [comment]
There is no information about JUCE in the linked issue.

If you can produce any sanitizer errors (including tsan and the undefined behaviour checker) in any JUCE code please create a new issue with the corresponding stack trace.

**Comment by kmatheussen** [comment]
There is definitely JUCE information in the linked issue... :-)

```
==3069==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000036258 at pc 0x55f5cb471b3f bp 0x7fff1a5c1cb0 sp 0x7fff1a5c1ca8
WRITE of size 8 at 0x602000036258 thread T0
    #0 0x55f5cb471b3e in handleSelection ../../JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:1351
    #1 0x55f5cb4857b4 in operator() ../../JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3038
    #2 0x55f5cb4a8067 in __invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> /usr/include/c++/10/bits/invoke.h:60
    #3 0x55f5cb4a19ee in __invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> /usr/include/c++/10/bits/invoke.h:153
    #4 0x55f5cb49ca46 in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #5 0x55f5cb0a5443 in std::function<void (int)>::operator()(int) const /usr/include/c++/10/bits/std_function.h:622
    #6 0x55f5cb09b36e in juce::InternalRunLoop::dispatchPendingEvents() ../../JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:186
    #7 0x55f5cb08e78c in juce::MessageManager::dispatchNextMessageOnSystemQueue(bool) ../../JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:300
    #8 0x55f5cb083b40 in juce::MessageManager::runDispatchLoop() ../../JUCE/modules/juce_events/messages/juce_MessageManager.cpp:128
    #9 0x55f5cb0826bf in juce::JUCEApplicationBase::main() ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:262
    #10 0x55f5cb082501 in juce::JUCEApplicationBase::main(int, char const**) ../../JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
    #11 0x55f5caaae6cf in main ../../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp:47
    #12 0x7fd583cdcd09 in __libc_start_main ../csu/libc-start.c:308
    #13 0x55f5ca9e9319 in _start (/home/tom/build22/ctrlr/Builds/LinuxMakefile/build/Ctrlr-Debug+0x16bf319)
```

**Comment by tpoole** [comment]
Where can I find this information from the link?

How is this triggered?

What version of JUCE is this?

**Comment by tpoole** [comment]
I've been able to reproduce this copying some UTF-8 text to the system clipboard

**Comment by kmatheussen** [comment]
All the information is provided in the link to the issue. There's only 20 words, or something, in the issue, so it shouldn't be hard, at all, really, to find that information... :-)

**Comment by tpoole** [comment]
Thank you for reporting. Fixed in https://github.com/juce-framework/JUCE/commit/06db7f074e595f22be53a0cfc448011b88559ec4.

**Comment by keinstein** [comment]
The static assert should fail on i*86 linux systems. As Atom is neither 8byte nor 4 byte. It is “long int”.

**Comment by tpoole** [comment]
Fixed in https://github.com/juce-framework/JUCE/commit/3366ad4ed4fadbbf28600e887c6f12566e98d588.
